### ISSUE TITLE
希望支持amd架构

### ISSUE THREAD

**Issue by Fantuan-cell** [xhongc/music-tag-web#10]
希望将镜像上传到dockerhub,请求支持amd架构

**Comment by xhongc** [comment]
> 希望将镜像上传到dockerhub,请求支持amd架构

阿里云镜像 是支持amd架构

**Comment by xhongc** [comment]
> 希望将镜像上传到dockerhub,请求支持amd架构

阿里云镜像和dockerhub应该没区别吧

**Comment by xhongc** [comment]
镜像适配 linux/amd64,linux/arm64,linux/arm

**Comment by xhongc** [comment]
[请教一下怎么在docker上部署MusicTag Web #1](https://github.com/xhongc/music-tag-web/issues/1)
这个应该能解决你的问题。

**Comment by xhongc** [comment]
hi，我创建一个交流群（二维码在 readme页面），感兴趣可以加入。群里会谈论项目新进展，和玩nas的交流，你有需要增加的功能可也沟通交流，期待你的加入！

ps. 不想被打扰，不加群也没关系，issue提的问题我也会回答。
