### ISSUE TITLE
aac 文件不显示

### ISSUE THREAD

**Issue by 4ft35t** [xhongc/music-tag-web#104]
https://github.com/xhongc/music-tag-web/blob/a8db0b5fe172a861538e8a0f67f5660cdbaa408b/applications/task/constants.py#L1C1-L1C11 
没有 aac

**Comment by xhongc** [comment]
上传你的文件给我试试

**Comment by 4ft35t** [comment]
`yt-dlp -x https://www.bilibili.com/video/BV1ez411i7uR `下载 m4a

ffpeg 转 aac
`ffpeg -i input.m4a output.aac`

**Comment by 4ft35t** [comment]
版本信息
```bash
latest: Pulling from xhongc/music_tag_web
Digest: sha256:aef9b90ccc471f67effc7eae39308abfab2f4f722b368e910d5df938c1fba5f0
Status: Image is up to date for xhongc/music_tag_web:latest
```

**Comment by xhongc** [comment]
抱歉我没有你提到的这些工具，我将关闭这个 issue

**Comment by 4ft35t** [comment]
不依赖特定文件就能复现

```bash
touch a1.mp3 a2.flac a3.aac a4.m4a
```
![Screenshot_20231209-190108](https://github.com/xhongc/music-tag-web/assets/2051049/f93f5d56-1c59-4156-9753-3853ff9cbc01)

**Comment by xhongc** [comment]
收到，acc 格式目前确实没有支持，还需后续开发迭代
