### ISSUE TITLE
m4a 文件报错

### ISSUE THREAD

**Issue by 4ft35t** [xhongc/music-tag-web#105]
`"Mutagen type <class 'NoneType'> not implemented"`

**Comment by xhongc** [comment]
你可以上传你报错的 m4a 文件给我试试，我的 m4a 是可以工作的
请描述清晰你的具体操作，修改哪些标签。

**Comment by 4ft35t** [comment]
yt-dlp -x https://www.bilibili.com/video/BV1ez411i7uR

保存的就是 m4a 文件。
直接在文件夹里点文件名，就报错，都没进入修改流程。

xier ***@***.***> 于2023年12月7日周四 20:05写道：

**Comment by xhongc** [comment]
抱歉我没有你提到的这些工具，我将关闭这个 issue
