### ISSUE TITLE
IOS

### ISSUE THREAD

**Issue by MartinMa5157** [xhongc/music-tag-web#11]
可以开发一下ios端的音乐标签吗，这个网页版的好像不好搜索苹果文件里的音乐，我还是挺期待苹果可以使用这个网站的

**Comment by xhongc** [comment]
没有点 ios app 这个技能，你可以把刮削好的音乐传回到手机上。 @ @MartinMa5157

**Comment by xhongc** [comment]
hi，我创建一个交流群（二维码在 readme页面），感兴趣可以加入。群里会谈论项目新进展，和玩nas的交流，你有需要增加的功能可也沟通交流，期待你的加入！

ps. 不想被打扰，不加群也没关系，issue提的问题我也会回答。
