### ISSUE TITLE
[Enhance] 通过修改参数来获取清晰的封面

### ISSUE THREAD

**Issue by UnspokenSpell** [xhongc/music-tag-web#111]
## 问题
![cover 彼女、お借りします Original Character Song   Original Soundtrack CD Vol 3](https://github.com/xhongc/music-tag-web/assets/73733485/4c8f436a-d637-41bd-89f8-fbf5b9e2c52a)
我注意到刮削完后，出现了一张效果严重不理想的封面

![2023-12-13_22-22-58](https://github.com/xhongc/music-tag-web/assets/73733485/6979fddb-3a3f-4ecf-9713-61063f9947c4)
被Navidrome放大后有点辣眼睛

## 理论依据
![2023-12-13_22-57-02](https://github.com/xhongc/music-tag-web/assets/73733485/e71c7944-f92d-440c-b800-b55b25b34915)

我发现，在网易云音乐Web版中，默认展示小图，而小图都带有且仅带有参数"?param=130y130"。

## 改进方法
![qUEKUUL35S0yzAUxNpKShA==109951168853259782](https://github.com/xhongc/music-tag-web/assets/73733485/4496fdcd-85f1-4273-aff8-db8f5aabd2c1)
要获取大图，只需要去除此参数，不带参数。

### 例子
默认链接：`http://p2.music.126.net/qUEKUUL35S0yzAUxNpKShA==/109951168853259782.jpg?param=130y130`
大图链接：`http://p2.music.126.net/qUEKUUL35S0yzAUxNpKShA==/109951168853259782.jpg`

**Comment by xhongc** [comment]
收到，你可以把出现问题的 音乐名称发我， 方便我定位问题

**Comment by xhongc** [comment]
确实🌶️👀

**Comment by UnspokenSpell** [comment]
> 收到，你可以把出现问题的 音乐名称发我， 方便我定位问题

[前山田健一 - 本当に凄いよなあ...](https://music.163.com/#/song?id=1807004625)

**Comment by xhongc** [comment]
<img width="1371" alt="image" src="https://github.com/xhongc/music-tag-web/assets/29135056/8a20db48-f739-461a-8689-c30d97c628d0">
这张图并不小啊

**Comment by UnspokenSpell** [comment]
你的UI好像和我的不同。我用的是 music tag web V1的 [自动修改]，你也是吗？

![image](https://github.com/xhongc/music-tag-web/assets/73733485/aec0df8a-090f-460b-8296-f04eb09bbee6)

**Comment by UnspokenSpell** [comment]
![2023-12-14_00-07-39](https://github.com/xhongc/music-tag-web/assets/73733485/87427722-4fdc-4af0-89d9-68c8815f40be)
![2023-12-14_00-03-11](https://github.com/xhongc/music-tag-web/assets/73733485/c22f436b-7774-4428-ad79-b3dea34bdfaf)
这是我用与你相同的方式获取的结果

**Comment by xhongc** [comment]
我是手动修改，自动修改可能找到不是网易源的图片？

**Comment by xhongc** [comment]
发现问题， 这个接口图片随机返回，有时是高清，有时是模糊

**Comment by xhongc** [comment]
https://p1.music.126.net/qUEKUUL35S0yzAUxNpKShA==/109951168853259782.jpg 是模糊
https://p2.music.126.net/qUEKUUL35S0yzAUxNpKShA==/109951168853259782.jpg 是高清

**Comment by UnspokenSpell** [comment]
> 我是手动修改，自动修改可能找到不是网易源的图片？

当我指定图片源仅限网易云时，没获取过大图

**Comment by UnspokenSpell** [comment]
> https://p1.music.126.net/qUEKUUL35S0yzAUxNpKShA==/109951168853259782.jpg 是模糊
> https://p2.music.126.net/qUEKUUL35S0yzAUxNpKShA==/109951168853259782.jpg 是高清

似乎可以将域名中的"p1"替换成"p2"来解决问题🤔。当然，更换接口可能更加优雅。

**Comment by xhongc** [comment]
你先手动上传修复 这个专辑封面吧

**Comment by xhongc** [comment]
后续 在优化

**Comment by UnspokenSpell** [comment]
好
