### ISSUE TITLE
登录界面除了用户名、密码还有个邀请码？请问邀请码怎么获取

### ISSUE THREAD

**Issue by virtually321** [xhongc/music-tag-web#113]
部署docker容器后登录，登录界面多了项invitation输入框，请问如何获取这个invitation呢？还是我设置有问题？

**Comment by virtually321** [comment]
部署docker容器后登录，登录界面多了项invitation输入框，邀请码从何而来呢

**Comment by xhongc** [comment]
不需要填写invitation
