### ISSUE TITLE
玩客云部署成功后首次运行显示暂时不可用，刷新后就无法访问

### ISSUE THREAD

**Issue by Chi-Wingc** [xhongc/music-tag-web#114]
因为玩客云是arm32v7，所以是安装的1.2.5和1.2.6版本，两个版本都是安装完第一次打开时显示不可用，再次刷新就无法访问了，查看日志显示ImportError: libjpeg.so.62: cannot open shared object file: No such file or directory

**Comment by xhongc** [comment]
1.2.5 和 1.2.6 版本不 需要映射 /path/to/your/config:/app/data
映射了可能会报错
