### ISSUE TITLE
docker-compose 启动无法刮削

### ISSUE THREAD

**Issue by taizilongxu** [xhongc/music-tag-web#115]
启动后点击搜索请求这个地址 fetch_id3_by_title 无法访问
开启 network_mode: host 功能正常, 
可能是缺了什么端口？

**Comment by xhongc** [comment]
应该就是无法访问外部网络，一般开启 host 模式，是可以的

**Comment by taizilongxu** [comment]
感谢, 应该是网络问题, 先开 host
