### ISSUE TITLE
手动修改似乎不会添加到操作记录中

### ISSUE THREAD

**Issue by Qm-jmz** [xhongc/music-tag-web#117]
如题。手动修改似乎不会添加到操作记录中，这样无从看到批量手动修改的任务进度

**Comment by xhongc** [comment]
手动修改一般不会报错

**Comment by Qm-jmz** [comment]
主要是我在批量手动修改中经常碰到任务看起来完成了，但实际上只修改了一部分文件的情况。
比如我在某文件夹中有某综艺的100首歌曲，我批量手动修改专辑艺术家为综艺名字（不然因为每首歌歌手不同就会出现每首歌单独成为专辑的情况），但看着任务完成了，点进去发现只修改了30首左右的歌曲信息。

**Comment by xhongc** [comment]
执行是阻塞的，没执行完成前，不能去操作其他

**Comment by Qm-jmz** [comment]
我在web端没有进行任何操作。我曾经尝试在一局游戏开始前开始任务，在一局游戏过后，任务看起来停止了。但检查文件发现只有部分信息被修改。
ps：这也是我想要手动修改也记录到操作记录中（info等级），目前似乎只有error会被记录

没有操作记录的时间戳我无从得知修改一份文件需要多久，也就无法估计任务整体需要多久，这时就会导致我可能随便碰了一下网页（不一定要进行什么操作）就会导致任务中断的情况发生

以及我想知道切换网页焦点是否会导致任务阻塞？类似alt+tab切换窗口

**Comment by Qm-jmz** [comment]
另外就是，批量自动修改可否添加外文歌词自动翻译按钮？感觉会方便不少

**Comment by Qm-jmz** [comment]
![image](https://github.com/xhongc/music-tag-web/assets/50917637/70f4c21e-242e-4945-8f7f-f356da871c6a)
当从上图变为下图时，是否意味着任务结束？
![image](https://github.com/xhongc/music-tag-web/assets/50917637/0b21ae46-a3e1-4bda-8dd7-a3827770d419)

**Comment by xhongc** [comment]
100首歌 手动修改的话 10 秒之内就会完成的

**Comment by xhongc** [comment]
> ![image](https://private-user-images.githubusercontent.com/50917637/292382949-70f4c21e-242e-4945-8f7f-f356da871c6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMjc4NDksIm5iZiI6MTcwMzIyNzU0OSwicGF0aCI6Ii81MDkxNzYzNy8yOTIzODI5NDktNzBmNGMyMWUtMjQyZS00OTQ1LThmN2YtZjM1NmRhODcxYzZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDA2NDU0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1OTlkYWUxYjJkMTk4YmEzNTY3NTlhNTU1NGJmNjg4YjMzY2ExN2I4N2Y1N2FhNzRlNmMzMGIxNmM4Yzg0NGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Lvvu03R3XM6yey-ld91vHZaYFK0iABtgZTkbGxej3eg) 当从上图变为下图时，是否意味着任务结束？ ![image](https://private-user-images.githubusercontent.com/50917637/292382266-0b21ae46-a3e1-4bda-8dd7-a3827770d419.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMjc4NDksIm5iZiI6MTcwMzIyNzU0OSwicGF0aCI6Ii81MDkxNzYzNy8yOTIzODIyNjYtMGIyMWFlNDYtYTNlMS00YmRhLThkZDctYTM4Mjc3NzBkNDE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDA2NDU0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjZGVkOTNjMWM4Yjg1NDFhMjFjYzhmY2U0NGVmZTllNTFhMjU3OGI2ODBlYjA4MmE0YTI0ZWE1OGZlYzg3MDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.no3bomAXu7ZlmNlI_TqFRT7JoI08Y1t80drLNLUMzGM)

是的

**Comment by xhongc** [comment]
可能是中间一首歌报错导致 终止了吧

**Comment by Qm-jmz** [comment]
> 100首歌 手动修改的话 10 秒之内就会完成的

但事实上我这边要慢得多。并且确实有修改不完全的现象出现。

我的nas配置为cpu N5105，内存8G。我没有限制docker资源不过跑了不止一个docker

**Comment by Qm-jmz** [comment]
> 可能是中间一首歌报错导致 终止了吧

但是操作记录中和后台日志里都找不到相关信息。。。。

**Comment by xhongc** [comment]
不应该会这样吧，你可以尝试少量修改查看问题

**Comment by xhongc** [comment]
> > 可能是中间一首歌报错导致 终止了吧
> 
> 但是操作记录中和后台日志里都找不到相关信息。。。。

日志在容器里 /var/log 下

**Comment by Qm-jmz** [comment]
> > > 可能是中间一首歌报错导致 终止了吧
> > 
> > 
> > 但是操作记录中和后台日志里都找不到相关信息。。。。
> 
> 日志在容器里 /var/log 下

![image](https://github.com/xhongc/music-tag-web/assets/50917637/1c141652-738c-42ff-9123-aa171bade082)
我应该查看哪个文件
