### ISSUE TITLE
批量手动修改是否支持正则表达式？

### ISSUE THREAD

**Issue by Qm-jmz** [xhongc/music-tag-web#118]
如题，我的一些音乐文件的标题含有英文及中文翻译，如图。
![image](https://github.com/xhongc/music-tag-web/assets/50917637/a867fd09-e1fe-4da3-a705-598f14a26049)
这会影响刮削时的识别。所以我想知道有没有什么办法可以快速修改标题，只保留中文/英文

**Comment by xhongc** [comment]
拆分文件名功能 ，可以写正则表达式,将文件名称中的字段正则匹配后 赋值给标题使用
