### ISSUE TITLE
作者您好！请问下自动批量修改一直是灰色的，要怎么使用呢？

### ISSUE THREAD

**Issue by tttfffyyy** [xhongc/music-tag-web#12]
作者您好！我是布置在黑群上面的，请问下自动批量修改一直是灰色的，要怎么使用呢？谢谢……

**Comment by xhongc** [comment]
目前还不支持自动批量修改

**Comment by xhongc** [comment]
> 作者您好！我是布置在黑群上面的，请问下自动批量修改一直是灰色的，要怎么使用呢？谢谢……

现已经支持 自动批量修改，新的镜像版本为1.0.2

**Comment by xhongc** [comment]
hi，我创建一个交流群（二维码在 readme页面），感兴趣可以加入。群里会谈论项目新进展，和玩nas的交流，你有需要增加的功能可也沟通交流，期待你的加入！

ps. 不想被打扰，不加群也没关系，issue提的问题我也会回答。
