### ISSUE TITLE
整理文件夹功能，如果歌手或者唱片集出现特殊字符

### ISSUE THREAD

**Issue by RedCatJump** [xhongc/music-tag-web#122]
比如唱片集为：Kosmos 93.6: IV Songs Beyond Words
结果直接识别成为：S:\音乐\整理后\Acetre\KHZBA8~G\Acetre - MAE BRUXA.flac
因为专辑名字叫奇奇怪怪的还挺多的，遇到半角英文就错乱了。

**Comment by xhongc** [comment]
KHZBA8~G
是什么标签呢

**Comment by RedCatJump** [comment]
> KHZBA8~G 是什么标签呢
我自测了一下，这个可能是windows的bug，linux可以正常显示这些文件名，应该是windows无法显示特殊字符的原因
