### ISSUE TITLE
可以在外网访问music-tag吗

### ISSUE THREAD

**Issue by lintiger86** [xhongc/music-tag-web#123]
可以在外网访问music-tag吗？在内网可以正常访问，但在外网访问，无法打开网页，连通性测试正常，显示错误代码：-324，详细原因：EMPTY_RESPONSE

**Comment by xhongc** [comment]
可以外网访问，这只是 web 应用，大概率是你的网络配置问题

**Comment by lintiger86** [comment]
我还用docker部署了qbittorrent和audioshelf，都可以外网访问，只有musictag不行。大佬能帮我分析一下原因吗？发自我的手机-------- 原始邮件 --------发件人： xier ***@***.***>日期： 2024年1月5日周五 10:23收件人： xhongc/music-tag-web ***@***.***>抄送： lintiger86 ***@***.***>, Author ***@***.***>主    题： Re: [xhongc/music-tag-web] 可以在外网访问music-tag吗 (Issue #123)
可以外网访问，这只是 web 应用，大概率是你的网络配置问题

**Comment by xhongc** [comment]
查看防火墙规则 8001 端口是否允许
