### ISSUE TITLE
端口問題

### ISSUE THREAD

**Issue by yohaneowo** [xhongc/music-tag-web#125]
希望可以適配docker 環境的port,我的8001有項目在跑,docker直接設定其他port也沒用,代碼寫死8001端口了

想問一下這個項目使用什麼版本的python,因為fork下來發現安裝依賴會有問題!

**Comment by xhongc** [comment]
直接修改端口映射就可以，docker 内的端口不会影响宿主机端口的
-p xxx （你需要的端口）:8001

**Comment by yohaneowo** [comment]
原來我是缺少了映射音樂文件夾才無法啟動,我還以為是端口問題,謝謝!
