### ISSUE TITLE
[功能请求] 似乎没有找到手动编辑音轨号/CD号的地方

### ISSUE THREAD

**Issue by lwp2070809** [xhongc/music-tag-web#127]
虽然可以查看曲目的音轨编号, 但是在"手动修改"的功能中没有找到可以修改的地方. 如果没有这个功能的话, 请求作者能在后续版本中加入; 如果是我没有找到的话也烦请告知如何操作. 非常感谢😊

**Comment by lwp2070809** [comment]
找到了,  在配置里面可以添加更多元信息的修改

**Comment by Yirenxs** [comment]
@lwp2070809 你好，我也困惑于怎么修改CD号，没找到配置的地方，能否麻烦您说下在哪改，谢谢。

**Comment by lwp2070809** [comment]
@wqzvic88 

![屏幕截图 2024-01-23 095300](https://github.com/xhongc/music-tag-web/assets/15991672/8fff895a-0b54-49d9-a90f-669e1a00e8f1)
点击音乐文件, 点击齿轮, 在里面勾选需要展示的元信息字段即可.
