### ISSUE TITLE
【功能建议】移动端适配

### ISSUE THREAD

**Issue by gitbobobo** [xhongc/music-tag-web#129]
有时候在手机上听歌，发现歌曲标签信息不对，就想直接通过「音乐标签web版」修正一下。

个人感觉也不用做多大改动，三栏式页面在手机端显示成三个标签页，这样操作起来应该会流畅一些。

另外，如果能为每个页面添加不同的URL就更好了，这样特殊适配的播放器app可以直接通过URL跳转到这首歌的修改页面，就不需要用户再选择路径-选择歌曲的步骤了

**Comment by xhongc** [comment]
很好建议，在H5 端方面还没开始开发适配。
url上带上参数应该是满足，后续会考虑加上

另外：你是音流的作者吧，音流很好用

**Comment by gitbobobo** [comment]
哇没想到你也用过了，不过还是得继续完善，现在问题不少😂

**Comment by icandura** [comment]
没想到在这捕捉到音流的作者，我是从小众软件上面找过来的，昨天刚开始用  Navidrome+音流 的方案，正愁歌词怎么解决的时候发现了这个可以批量刮削写入

**Comment by cyril-cheng** [comment]
目击两位大神对话，我也在用音流，很好用。

**Comment by xhongc** [comment]
1.完成适配了移动端ui
<img width="1259" alt="image" src="https://github.com/xhongc/music-tag-web/assets/29135056/b0b6abd9-12f8-42a7-a9b0-24665befe3ca">
2. 可根据 url 跳转到编辑页面，例如：
http://42.193.218.103:8002/#/?target=detail&path=%2Fapp%2Fmedia%2F%E9%99%88%E6%A5%9A%E7%94%9F%2F%E6%8A%AB%E8%8D%86%E6%96%A9%E6%A3%983%20%E7%AC%AC4%E6%9C%9F%2F%E6%80%9D%E5%BF%B5%E4%B8%80%E4%B8%AA%E8%8D%92%E5%BA%9F%E7%9A%84%E5%90%8D%E5%AD%97.flac
