### ISSUE TITLE
django.db.utils.OperationalError: (2002, "Can't connect to MySQL server on '127.0.0.1' (115)")

### ISSUE THREAD

**Issue by xp9477** [xhongc/music-tag-web#13]
无法启动

**Comment by xhongc** [comment]
镜像版本是1.0.1，本地分支是dev_1.0 请确认是否正确

**Comment by xhongc** [comment]
hi，我创建一个交流群（二维码在 readme页面），感兴趣可以加入。群里会谈论项目新进展，和玩nas的交流，你有需要增加的功能可也沟通交流，期待你的加入！

ps. 不想被打扰，不加群也没关系，issue提的问题我也会回答。
