### ISSUE TITLE
要是有win版，就更好了

### ISSUE THREAD

**Issue by qiyue-sanye** [xhongc/music-tag-web#131]
方便快捷

**Comment by xhongc** [comment]
你搜索 音乐标签 ，有其他大佬开发的 Windows软件哦

**Comment by qiyue-sanye** [comment]
要不太老，要不没标签源，找了几个就一个用着还行。而且win的都是软件，没有你这种适合装nas上，可以网页远程用的，用虚拟机又太占资源了，能跟Navidrome的有个win版网页访问，我就不用连nas操作了

**Comment by xhongc** [comment]
装 nas 上用 docker 是最方便了，
windows 就是 exe 软件
你说着太冲突了
