### ISSUE TITLE
歌词功能建议

### ISSUE THREAD

**Issue by Yirenxs** [xhongc/music-tag-web#134]
我是Plex用户，因为plex无法读取到内嵌歌词，只能外挂lrc，有2个歌词建议：
1. 目前无法查看哪些歌在相同文件夹下是否有同名的lrc歌词文件，希望如果已经存在外挂lrc歌词文件，就增加1个标识。
2. 我如果要lrc外挂歌词，目前的操作是，专辑文件夹整体打勾，点击“自动修改”，修改范围仅勾选“歌词”，点确定（歌词就内嵌到mp3tag里了）。然后，点击“手动修改”，“歌词”那滑动到“导出LRC”，再保存。这样有点麻烦了，能否在“自动修改”—“歌词”那里就增加1个选项，仅另存为LRC文件，不内嵌mp3tag。（同时另存时可以再增加个功能，如果已经有LRC文件或忽略或覆盖）。

**Comment by xhongc** [comment]
<img width="278" alt="image" src="https://github.com/xhongc/music-tag-web/assets/29135056/19600abd-6b35-48da-8b3d-4c1aa95d279d">

**Comment by Yirenxs** [comment]
> <img alt="image" width="278" src="https://private-user-images.githubusercontent.com/29135056/299148059-19600abd-6b35-48da-8b3d-4c1aa95d279d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNjAzMjAsIm5iZiI6MTcwNjA2MDAyMCwicGF0aCI6Ii8yOTEzNTA1Ni8yOTkxNDgwNTktMTk2MDBhYmQtNmIzNS00OGRhLThiM2QtNGMxYWE5NWQyNzlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDAxMzM0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExMmM4N2FjNzFiMDI2NzdlMDZkNWQ2ZDM1NTQxZmFiOTQwM2Q0Y2ZiZmRkOTFmYWFjOGJiYTlkOGRmMTdiYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BbUrTx39je4OBkMoC7rRjxqILPuUvnztF0F2CmMAWBE">

原来如此，发现了。“自动修改”里新增功能，歌词仅导出到lrc文件，而不要内嵌进MP3TAG，这个功能能否成为待增加feature。

**Comment by xhongc** [comment]
不影响使用，近期不会增加这个 feature

**Comment by Yirenxs** [comment]
你好，我翻了下，发现还挺多人需要在”自动修改”里增加”另存为LRC文件”功能的，希望作者有余力时考虑下，谢谢。
https://github.com/xhongc/music-tag-web/issues/60#issue-1905980960
https://github.com/xhongc/music-tag-web/issues/22#issuecomment-1657885462
https://github.com/xhongc/music-tag-web/issues/3#issue-1675653692

**Comment by xhongc** [comment]
好的，年前没有太多精力搞了

**Comment by xhongc** [comment]
已经添加此功能

**Comment by rickywei** [comment]
> 已经添加此功能

V1吗还是V2
