### ISSUE TITLE
是不是删除文件夹有问题

### ISSUE THREAD

**Issue by xp9477** [xhongc/music-tag-web#135]
文件夹整理后，原文件夹没有删除

**Comment by xp9477** [comment]
![image](https://github.com/xhongc/music-tag-web/assets/36835224/8e465641-b9f0-4fad-93fa-6e1c31358cbe)
这个专辑被整理后加入了歌手文件夹下，但是media目录下依旧存在未整理前的文件夹
![image](https://github.com/xhongc/music-tag-web/assets/36835224/eab49c0c-774a-4314-9d1e-c572227907b0)
![image](https://github.com/xhongc/music-tag-web/assets/36835224/a97a03eb-d993-46ba-a774-afa4958d415d)

**Comment by xhongc** [comment]
用删除空文件夹功能删一下

**Comment by xp9477** [comment]
> 用删除空文件夹功能删一下

删过了，不是空的，里面文件都在

**Comment by xhongc** [comment]
不会吧

**Comment by xp9477** [comment]
> 不会吧

50多个文件夹大概，有十个没删，别的都正常，我也不知道咋回事

**Comment by xhongc** [comment]
你说的没删 是指 整理文件后没删
还是删除空文件夹没删
删除空文件没删 是因为 文件夹存在任何文件 都不会当成空文件夹

**Comment by xp9477** [comment]
> 整理文件后没删

整理文件后没删

**Comment by LemonSugar198** [comment]
旧文件夹还在，里面文件不在了的

**Comment by xhongc** [comment]
> 旧文件夹还在，里面文件不在了的

这是正常，文件夹还在需要 使用 删除空文件夹 功能
