### ISSUE TITLE
整理文件夹时能支持硬链接到其他目录吗？

### ISSUE THREAD

**Issue by shanyan-wcx** [xhongc/music-tag-web#138]
有时候PT下的音乐，想要能继续做种，就想在整理时能从下载目录硬链接到整理目录。
比方说我下了一张专辑到download目录下，而我的媒体库在media目录，整理的时候希望能实现download/xxx文件夹-->media/歌手/专辑 这样子

**Comment by xhongc** [comment]
整理是整体移动文件的

**Comment by shanyan-wcx** [comment]
不能增加硬链接功能吗

**Comment by xhongc** [comment]
没计划加入这个功能
