### ISSUE TITLE
在web页面中使用FFmpeg将WAV转换成FLAC格式的时候出错的问题

### ISSUE THREAD

**Issue by zoukai3412085** [xhongc/music-tag-web#140]
我从网上下载了黑胶的几首歌，文件格式是WAV，文件大小180MB，比特率、采样率、位深分别为9216、192、24，转换时直接报错，但是能够生成FLAC文件，如果批量转格式，则会报错终止，但是第一个转换得到的FLAC文件能正常打开播放

如果我转换比特率、采样率、位深分别为1411、44、16的约38MB的WAV文件，则一切正常，可以批量转换

作为对比，我尝试将转换错误的大码率WAV文件放到mac电脑进行单独命令转换，则能够正常完成，与在music tag web中得到的文件大小相近

**Comment by xhongc** [comment]
修复
