### ISSUE TITLE
bug: ffmpeg格式转换报错

### ISSUE THREAD

**Issue by hangvane** [xhongc/music-tag-web#141]
转换过程应该考虑对文件名及路径中的'"()[]空格等特殊字符进行转义或类似操作

转换失败:/app/download/n8n-temp/Who's Lovin' You-October-I'm In You.flacffmpeg version 6.1-static https://johnvansickle.com/ffmpeg/ Copyright (c) 2000-2023 the FFmpeg developers built with gcc 8 (Debian 8.3.0-6) configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg libavutil 58. 29.100 / 58. 29.100 libavcodec 60. 31.102 / 60. 31.102 libavformat 60. 16.100 / 60. 16.100 libavdevice 60. 3.100 / 60. 3.100 libavfilter 9. 12.100 / 9. 12.100 libswscale 7. 5.100 / 7. 5.100 libswresample 4. 12.100 / 4. 12.100 libpostproc 57. 3.100 / 57. 3.100 [in#0 @ 0x6b8f640] Error opening input: No such file or directory Error opening input file /app/download/n8n-temp/Whos. Error opening input files: No such file or directory

转换失败:/app/download/n8n-temp/Lemon Tree-Fool's Garden-Die Ultimative Chartshow (Die Erfolgreichsten One Hit Wonder).flac/bin/sh: 1: Syntax error: "(" unexpected

**Comment by xhongc** [comment]
修复
