### ISSUE TITLE
Feature Suggestion: Default filename format for difference sources

### ISSUE THREAD

**Issue by jyyyeung** [xhongc/music-tag-web#142]
简单来说是
1. 设置自定义全局文件名格式
2. 预设一些常用软件的文件名格式

首先感谢一下这个优秀的软件！

目前我看到好像文件命名格式是 Navidrome 的，可逛了一下以前的issues好像也有不少人是使用其他播放器，我感觉如果能让用户在 global settings 里更改 default naming format 就很方便。如果我没理解错，现在应该只能在每次“整理文件夹”的时候设置。

至于我提到的 预设常用软件命名格式是类似于这样：
```python 
{
  "default": "${artist}/${album}/${title}-${album}.${ext}",
  "common_1": "${albumArtist}/${album} (${year})/${title} - ${artist}.${ext}",
  "plex": "${albumArtist}/${album}/${trackNumber} - ${title}.${ext}",
  "navidrome": ...,
  ...
}
```

然后可以选择其中一个 或者 自定义

**Comment by jyyyeung** [comment]
如果你欢迎 Contribution 的话，你可以将 Development 步骤写在 `README.md`, 我也可以试着添加。

**Comment by xhongc** [comment]
能看出来你了解的很深入。

如果你是想要批量修改文件名称的话 ，可以批量手动修改 在文件名处填上你的变量模板。
你的意思是要提供到一些特定的模板，给用户进行选择吗。不是输入框 而是 下拉选择框

**Comment by xhongc** [comment]
哦，我理解错了
你是想预设一些 整理文件夹的 模板。
文件名称的部分可以 批量手动修改。
文件夹目录层级 大致是可以满足，就是缺少 ${album} (${year}) 两个变量组合的功能

**Comment by jyyyeung** [comment]
> 哦，我理解错了 你是想预设一些 整理文件夹的 模板。 文件名称的部分可以 批量手动修改。 文件夹目录层级 大致是可以满足，就是缺少 ${album} (${year}) 两个变量组合的功能

也没错 我的想法是整个文件路径的预设选择 包括了 文件夹 和 文件名 的模板 但好像目前软件里这两个是分开设置的，所以可能需要看看是分开当作是两个功能写 还是 一个结合的
