### ISSUE TITLE
【Bug-专辑封面】手动上传封面后，在Navidrome中不显示。

### ISSUE THREAD

**Issue by OcrSu** [xhongc/music-tag-web#145]
先看出问题的截图（三张）：
![image](https://github.com/xhongc/music-tag-web/assets/75876201/2beb9a86-c725-49a5-b360-442e4c19b7f9)
![image](https://github.com/xhongc/music-tag-web/assets/75876201/3395f69d-a43c-4431-9091-0a45032ab7db)
![image](https://github.com/xhongc/music-tag-web/assets/75876201/6bee1120-cc57-4eb0-9b9f-be8256260035)

在图一中，左边两个专辑封面是 OST自带的，可以正常显示；右边的是我手动上传的，都不能正常显示。

在图二中，这里是梦灯花OST专辑，是我手动上传的封面。
也就是这个图片。
![截图_2024-02-21_16-04-02](https://github.com/xhongc/music-tag-web/assets/75876201/d734af53-9dec-4718-a8ed-3995da317364)

图三的截图，是发生在图二后的，也就是上传完梦灯花OST专辑封面后。
我手动编辑了这个音乐会OST封面（什么都不上传），如下图：
但是Music Tag Web显示仍然上传的是梦灯花OST封面。
![image](https://github.com/xhongc/music-tag-web/assets/75876201/76925be7-a5da-4e51-9823-251cee880f2f)

但Navidrome中，在Music Tag Web上传的封面都不会显示出来。

麻烦各位大佬看一下这个issue，个人不懂代码，但我觉得这个手动上传封面的功能没有正常运作。

**Comment by xhongc** [comment]
图片正确写入音乐元数据后，需要 navidrome 中重新刷新一下，让 navi 重新读取一下封面

**Comment by OcrSu** [comment]
> 图片正确写入音乐元数据后，需要 navidrome 中重新刷新一下，让 navi 重新读取一下封面

试过了 :(  ，显然没起作用
![image](https://github.com/xhongc/music-tag-web/assets/75876201/a8821ed6-c130-4191-a900-49a59f36910b)

**Comment by xhongc** [comment]
完全扫描

**Comment by xhongc** [comment]
或者重建库

**Comment by OcrSu** [comment]
> 或者重建库

完全扫描也试过了，我试试重建库，重新建立个容器

**Comment by OcrSu** [comment]
感觉是navidrome的问题，Plex的封面显示是没问题的。Navidrome怎么也不显示 :(

可能navidrome对于wav格式的音乐封面 显示支持不好。

能显示的都是Flac格式的音乐封面，其他没显示的都是wav格式。

**Comment by xhongc** [comment]
是的，标签写进去了，其他得看各个平台的读取标签策略

**Comment by long2ice** [comment]
我也遇到了这个问题，请问解决了吗

**Comment by haslwind** [comment]
同样有这个问题，用的MusicTag添加音乐标签和封面，emby里显示封面了，但是音乐文件的标签全是乱码。navidrome音乐标签显示正常，但是封面不显示。

**Comment by sifenglib** [comment]
我也遇到了这个问题，会不会是跟格式有关系？好像我不行的是mp3格式的
