### ISSUE TITLE
识别的音乐文件有2个版本的。一个不能用，一个可以用。

### ISSUE THREAD

**Issue by sylar1203** [xhongc/music-tag-web#153]
进入识别界面后，每一个FLAC的文件，都会出现2对应的2个文件。
一个可以点了识别，一个点了会出错（文件名前面有个._）。
<a href="https://sm.ms/image/lu734bfSxrV6X5T" target="_blank"><img src="https://s2.loli.net/2024/03/02/lu734bfSxrV6X5T.jpg" ></a>

**Comment by xhongc** [comment]
你本地本就存在两个 flac，
本项目不会生成 flac 文件
