### ISSUE TITLE
如何在windows下使用？根据教程修改路径的话？

### ISSUE THREAD

**Issue by DRCX** [xhongc/music-tag-web#154]
如何在windows下使用？根据教程修改路径的话？
 
 从Docker Registry拉取镜像
docker pull xhongc/music_tag_web:latest
dokcer run
docker run -d -p 8001:8001 -v /path/to/your/music:/app/media -v /path/to/your/config:/app/data --restart=always xhongc/music_tag_web:latest
或者 使用portainer stacks部署（与2选一个方式即可）
version: '3'
services: music-tag: image: xhongc/music_tag_web:latest container_name: music-tag-web ports: - "8001:8001" volumes: - /path/to/your/music:/app/media:rw - /path/to/your/config:/app/data command: /start restart: always
ps. /path/to/your/music 改成你的音乐文件夹路径！
/path/to/your/config 改为配置文件路径！
修改默认密码（可选）
访问在127.0.0.1:8001/admin 默认账号密码 admin/admin 修改默认密码

此时你已经部署好了，你想知道具体怎么使用，请往下看吧。

**Comment by xhongc** [comment]
一样的 /path/to/your/music 就是 windows 的路径 例如 D:\\music
