### ISSUE TITLE
配合Audio Station下音乐文件信息读取问题

### ISSUE THREAD

**Issue by randy64** [xhongc/music-tag-web#156]
通过Music-Tag-Web能够成功修改音乐文件信息，然后文件下载下来也能看到信息已经修改了。
但是通过Audio Station无法读取修改后的音乐文件信息
我检查了一下通过Music-Tag-Web处理的音乐文件，修改前和修改后，文件所属人以及权限都没有变化（777）

**Comment by randy64** [comment]
看了之前closed issue，更换套件

**Comment by xhongc** [comment]
什么什么什么
