### ISSUE TITLE
威联通container 报错

### ISSUE THREAD

**Issue by MuMu360121** [xhongc/music-tag-web#157]
![image](https://github.com/xhongc/music-tag-web/assets/1499007/67d595dc-49ca-430f-82fa-6d91b730b67c)
![image](https://github.com/xhongc/music-tag-web/assets/1499007/45f1aa54-8b0d-444a-94db-030231d5799f)
![image](https://github.com/xhongc/music-tag-web/assets/1499007/e00cb4cc-6ef0-49e3-9e7f-57c9661f4a8c)

**Comment by xhongc** [comment]
报错显示你的磁盘满了
