### ISSUE TITLE
群晖上使用docker修改文件后，不能同步到drive

### ISSUE THREAD

**Issue by king-NB** [xhongc/music-tag-web#158]
使用[music-tag-web]修改的文件夹以及文件信息，不能同步到drive，不知道是否有增加类似  icloudpd中的synology_photos_app_fix这种参数的计划。music-tag修改文件及文件夹后触发将修改的文件同步到drive服务器，谢谢。
不知道我描述的是否清楚，目前icloudpd也是面临同样的问题，但是开发者增加了synology_photos_app_fix参数。
以下是我发给群晖工程师的技术支持。

亲爱的用户 您好,

感谢您的来信。

 

工程师有收到您的来信，关于您提到的“使用docker，musictag 里面的整理文件夹功能新建的”，由于这并不是synology drive所支持的方式，

通过docker或底层命令/脚本添加的文件，drive server是无法正常识别到这些变动的文件的，所以不会显示在您的drive网页或drive app中。

还请您改用其他方式，谢谢。

 
希望以上信息对您有所帮助，谢谢。

-------------
Gavin
技术支持工程师

**Comment by king-NB** [comment]
![Uploading 截屏2024-03-14 23.20.06.png…]()

**Comment by xhongc** [comment]
感谢你的反馈，我讲在后续研究这个同步方案，还希望到时候能得到你的测试回馈。
因为我没有群晖环境

**Comment by king-NB** [comment]
> 感谢你的反馈，我讲在后续研究这个同步方案，还希望到时候能得到你的测试回馈。 因为我没有群晖环境

如有同步方案，一定会第一时间测试，感谢🙏

**Comment by xhongc** [comment]
方便的话，加我微信，我还不太了解群晖的同步机制
