### ISSUE TITLE
拉取的封面图片好像比较模糊？

### ISSUE THREAD

**Issue by wangweitung** [xhongc/music-tag-web#16]
![Screenshot_2023-07-16-11-36-54-521_com mb android tg](https://github.com/xhongc/music-tag-web/assets/8080125/f5c26036-331c-4da0-a906-e690ef8180ac)

**Comment by xhongc** [comment]
> ![Screenshot_2023-07-16-11-36-54-521_com mb android tg](https://user-images.githubusercontent.com/8080125/253783824-f5c26036-331c-4da0-a906-e690ef8180ac.jpg)

可能被我缩略图了

**Comment by xhongc** [comment]
> ![Screenshot_2023-07-16-11-36-54-521_com mb android tg](https://user-images.githubusercontent.com/8080125/253783824-f5c26036-331c-4da0-a906-e690ef8180ac.jpg)

修复在1.0.8

**Comment by wangweitung** [comment]
> > ![Screenshot_2023-07-16-11-36-54-521_com mb android tg](https://user-images.githubusercontent.com/8080125/253783824-f5c26036-331c-4da0-a906-e690ef8180ac.jpg)
> 
> 修复在1.0.8

谢谢~

**Comment by xhongc** [comment]
hi，我创建一个交流群（二维码在 readme页面），感兴趣可以加入。群里会谈论项目新进展，和玩nas的交流，你有需要增加的功能可也沟通交流，期待你的加入！

ps. 不想被打扰，不加群也没关系，issue提的问题我也会回答。
