### ISSUE TITLE
接入音流后，歌手封面都是乱的！

### ISSUE THREAD

**Issue by jinfeng1985** [xhongc/music-tag-web#160]
接入音流后，歌手封面都是乱的！
![IMG_0770](https://github.com/xhongc/music-tag-web/assets/22148953/4896f470-480f-410d-a9a4-696f1dabd5e7)

**Comment by dididaguai** [comment]
![111](https://github.com/xhongc/music-tag-web/assets/140925064/f6d63c2c-e474-431d-aa74-6e924a5a89bb)
w确实是，我抓包后查看感觉是没有对应接口导致的

**Comment by gitbobobo** [comment]
1.2.7已经修复了封面混乱的问题，这个问题感觉可以关掉了。

另外确实缺少部分subsonic的接口，比如评分接口
