### ISSUE TITLE
无法修改网盘内文件

### ISSUE THREAD

**Issue by 1263478456** [xhongc/music-tag-web#167]
#### 提示[Errno 1] Operation not permitted
- 运行环境：docker
- 已经给了Puid=0和Pgid=0以及User=root
- 网盘使用Alist挂载的阿里云盘并且使用rclone挂载到本地的
- 同样环境下的Emby刮削正常

**Comment by 1263478456** [comment]
- 并且在V1下也不能修改网盘文件

**Comment by Asakushen** [comment]
您好解决了吗？
and 作者您好。这个问题有考虑实现吗？

**Comment by xhongc** [comment]
rclone 挂载，操作和本地文件一样，理论是可以的， 如果出现问题你应该首先排查rclone挂载是否正确，文件权限
