### ISSUE TITLE
V2关于小爱音响的功能请教

### ISSUE THREAD

**Issue by SV-jiang-guangming** [xhongc/music-tag-web#169]
![image](https://github.com/xhongc/music-tag-web/assets/94834308/d1cacff3-2c2b-4c70-aeb2-f9a7588f8024)
小爱音响中提到的MTW具体是什么？有没有针对这个功能稍微详细些的说明。
其他大佬也麻烦指导12

**Comment by xhongc** [comment]
MTW 是指 musictag web

**Comment by SV-jiang-guangming** [comment]
感谢，已经在群里得到帮助，此issue close
