### ISSUE TITLE
我在群晖部署成功，但无法使用

### ISSUE THREAD

**Issue by gzroc** [xhongc/music-tag-web#17]
在使用的时候，我选择音乐，然后自动批量修改，显示创建成功，但就是没法获取到任何歌曲信息，和封面。

**Comment by xhongc** [comment]
> 在使用的时候，我选择音乐，然后自动批量修改，显示创建成功，但就是没法获取到任何歌曲信息，和封面。

没匹配到吧，要根据歌曲名称去匹配的

**Comment by xhongc** [comment]
hi，我创建一个交流群（二维码在 readme页面），感兴趣可以加入。群里会谈论项目新进展，和玩nas的交流，你有需要增加的功能可也沟通交流，期待你的加入！

ps. 不想被打扰，不加群也没关系，issue提的问题我也会回答。
