### ISSUE TITLE
后台刮削能否增加排重？

### ISSUE THREAD

**Issue by hi-mcwolf** [xhongc/music-tag-web#173]
后台刮削能否增加排重，就是发现库里已有的歌曲就不再刮削单独放到一个文件夹里，或者给个选项保留质量高的。不然会有很多很多重复的歌曲，而且没有记录快速查询这批导入了哪些，只能一个文件夹1个文件夹处理，太痛苦了

**Comment by LAN-Cliv** [comment]
强烈赞同
有时候都是下一整个专辑，下多了重复就多。。
要是能手动或者自动去重复就好了
