### ISSUE TITLE
希望增加收藏数据更新功能

### ISSUE THREAD

**Issue by fire05060135** [xhongc/music-tag-web#177]
目前导入收藏的歌曲不会更新，调整文件夹中歌曲保存的位置，在音乐收藏中还是指向原来的路径，点击歌曲无法播放，点击编辑按钮会指向空的路径。同时，如将调整后的歌曲再次导入，收藏中同一个专辑下会出现2首同样的歌曲，其中一首是空的，无法播放，这条空的歌曲也无法单独删除，只能删除整个专辑，再重新导入。
![360截图20240404161005199](https://github.com/xhongc/music-tag-web/assets/165994632/7e6ab737-a05a-4169-b71f-1179508eb364)
![360截图20240404161110398](https://github.com/xhongc/music-tag-web/assets/165994632/5529f883-fd14-4f89-bf93-b12c9944d5bf)

**Comment by xhongc** [comment]
拉最新版本
