### ISSUE TITLE
首页右下角音乐收藏的显示问题

### ISSUE THREAD

**Issue by Zhigang27** [xhongc/music-tag-web#178]
我发现首页右下角的音乐收藏的播放统计似乎有些问题。我今天听了好半天刘德华和郑智化的，就在浏览器里听的，但刷新后这个面板的歌曲、专辑、艺术家的次数统计都还是没变化。

建议：
1、检查一下播放次数的统计；
2、这部分多一些别的显示，如：最近添加的歌曲，播放次数最多的
3、考虑这里可以显示歌单；
4、这里放个播放器界面，可以选择随机播放等。

**Comment by xhongc** [comment]
暂不考虑

**Comment by Zhigang26** [comment]
2、3、4不考虑，1可以考虑检查一下吗？次数统计好像现在就没有变化了。
