### ISSUE TITLE
请问web是不是不能获取到翻译的歌词

### ISSUE THREAD

**Issue by fhkfds** [xhongc/music-tag-web#18]
请问web是不是不能获取到翻译的歌词

**Comment by xhongc** [comment]
> 请问web是不是不能获取到翻译的歌词

什么是翻译的歌词

**Comment by fhkfds** [comment]
就是pc版获取歌词可以有翻译 web端我试了下好像只有原文 没有翻译

**Comment by xhongc** [comment]
> 就是pc版获取歌词可以有翻译 web端我试了下好像只有原文 没有翻译

是的，那确是没有

**Comment by fhkfds** [comment]
请问有计划更新一下这个功能吗

**Comment by xhongc** [comment]
> 请问有计划更新一下这个功能吗

是指什么样的功能？你可以向我展示你需要的功能，例如从繁体翻译成简体，英文翻译成中文

**Comment by fhkfds** [comment]
主要是是日语和英语翻译到中文 然后可以选择只要翻译不要原文

**Comment by xhongc** [comment]
> 主要是是日语和英语翻译到中文 然后可以选择只要翻译不要原文

很好的提议，我将考虑加入这个功能 @fhkfds

**Comment by fhkfds** [comment]
好的 感谢 请问可以赞助吗

**Comment by fhkfds** [comment]
好的 感谢 请问可以赞助吗

**Comment by xhongc** [comment]
> 好的 感谢 请问可以赞助吗
哇，目前还没赞助渠道，同样感谢你

**Comment by xhongc** [comment]
支持翻译 ，在新版本1.1.1

**Comment by xhongc** [comment]
hi，我创建一个交流群（二维码在 readme页面），感兴趣可以加入。群里会谈论项目新进展，和玩nas的交流，你有需要增加的功能可也沟通交流，期待你的加入！

ps. 不想被打扰，不加群也没关系，issue提的问题我也会回答。
