### ISSUE TITLE
域名访问问题

### ISSUE THREAD

**Issue by Logan-Longman** [xhongc/music-tag-web#181]
在Nginx配置反代后，通过域名访问会出现 Bad Request 400的问题，IP:Port的形式可以正常访问，请问是否django的配置禁止了域名访问吗？

**Comment by xhongc** [comment]
是的，django 禁止了这一行为

**Comment by deardeer7** [comment]
如果解决啊，反代不行，只能通过ip访问

**Comment by xhongc** [comment]
> 如果解决啊，反代不行，只能通过ip访问

只是后台管理，反代进不去，页面是可以的

**Comment by Hansetar** [comment]
> > 如果解决啊，反代不行，只能通过ip访问
> 
> 只是后台管理，反代进不去，页面是可以的

现在只能用上一个版本了，不仅是后台进不去，主页面一样也进不去

**Comment by Hansetar** [comment]
> 在Nginx配置反代后，通过域名访问会出现 Bad Request 400的问题，IP:Port的形式可以正常访问，请问是否django的配置禁止了域名访问吗？

先用上一个版本用着吧
