### ISSUE TITLE
刮削失败（已入vip）

### ISSUE THREAD

**Issue by wintsa123** [xhongc/music-tag-web#182]
匹配失败:/app/media/陈奕迅/2003国语 陈奕迅.-.[黑白灰.-.Black，White.&.Grey].专辑.(APE)/陈奕迅.-.[黑白灰.-.Black，White.&.Grey].专辑.(APE).ape;未匹配到资源

全部都显示类似的，我就是网上找无损种子后下载后直接刮削，我应该怎么做？

**Comment by xhongc** [comment]
查看是否带有 专辑，艺术家信息，没有的话把文件名中的拆分给它

**Comment by wintsa123** [comment]
> 查看是否带有 专辑，艺术家信息，没有的话把文件名中的拆分给它
文件名是这样的
陈奕迅.-.[黑白灰.-.Black，White.&.Grey].专辑.(APE).ape

**Comment by wintsa123** [comment]
@xhongc
