### ISSUE TITLE
希望支持智能歌单

### ISSUE THREAD

**Issue by sabully** [xhongc/music-tag-web#185]
navidrome支持智能歌单,music tag的音乐收藏后台用的subsonic,应该也能支持智能歌单吧?

**Comment by xhongc** [comment]
智能歌单是什么

**Comment by sabully** [comment]
> 智能歌单是什么

https://sspai.com/post/40384\
这个链接介绍了苹果智能歌单的功能和制作

https://www.bilibili.com/read/cv30484857/
这个链接介绍了navidrome如何生成智能歌单

https://github.com/navidrome/navidrome/issues/1417
这个链接是上面的扩展用法

**Comment by xhongc** [comment]
收到，智能歌单在我的计划单中，我会认真考虑
