### ISSUE TITLE
汇报一个前端bug

### ISSUE THREAD

**Issue by wintsa123** [xhongc/music-tag-web#188]
![image](https://github.com/xhongc/music-tag-web/assets/47288630/ae70c831-2a19-4606-863e-f5d669a293a1)
点击歌曲后详细页打开后返回不了。点键盘esc或者鼠标点击右边都是弹出一个新的nav框出来

**Comment by xhongc** [comment]
是 bug

**Comment by xhongc** [comment]
修复在 2.0.6
