### ISSUE TITLE
歌手统一中文/英文名也匹不出来

### ISSUE THREAD

**Issue by wintsa123** [xhongc/music-tag-web#189]
> 歌手 又有中文名又有英文名会匹配不是，最好统一一下

真的气，大佬每次都要新开一个issues才回信息

第一次改成作者改成容祖儿
搜索结果有三首匹配成功，但是明明痛爱，争气这些都是热门歌，没匹配到
![image](https://github.com/xhongc/music-tag-web/assets/47288630/1bcf7134-3e28-4907-9455-5a82c2277f03)
第二次作者改成Joey Yung
![image](https://github.com/xhongc/music-tag-web/assets/47288630/37e8bdd8-1a8c-468c-86ce-8f2da334e4b5)
直接全军覆没

**Comment by xhongc** [comment]
手动匹配看能不匹配到
