### ISSUE TITLE
专辑艺术家

### ISSUE THREAD

**Issue by yuan93** [xhongc/music-tag-web#19]
请问这个功能后期打算支持吗

**Comment by xhongc** [comment]
> 请问这个功能后期打算支持吗

专辑艺术家跟艺术家是什么区别

**Comment by yuan93** [comment]
艺术家是这个人唱的所有的歌，专辑艺术家是这个歌手唱的这一个专辑里面的歌

**Comment by yuan93** [comment]
主要是有的歌，歌手是2个人或者多人，歌手那里写太多，创建歌手文件夹就会很长，专辑艺术家能把这个规整一下

**Comment by xhongc** [comment]
加一个输入框呗

**Comment by yuan93** [comment]
你看吧，能弄就弄一下😂

**Comment by yuan93** [comment]
# docker-compose -f local.yml up
y_db_1 is up-to-date
music_redis is up-to-date
Creating music_celerybeat   ... done
Creating music_celeryworker ... error
Creating music-tag-web      ... 

Creating music-tag-web      ... error

ERROR: for music-tag-web  Cannot start service django: Bind mount failed: '/Users/macbookair/Music/my_music' does not exists

ERROR: for celeryworker  Cannot start service celeryworker: Bind mount failed: '/Users/macbookair/Music/my_music' does not exists

ERROR: for django  Cannot start service django: Bind mount failed: '/Users/macbookair/Music/my_music' does not exists
ERROR: Encountered errors while bringing up the project.

**Comment by yuan93** [comment]
你能帮我打包更新一下吗😂，我打包报错了

**Comment by xhongc** [comment]
> 你能帮我打包更新一下吗😂，我打包报错了

现在线上的版本的分支是dev_1.0这个分支，非master
另外我打包了新版本 镜像在 1.1.0

**Comment by xhongc** [comment]
这个版本新增 专辑艺术家 功能。 我将关闭这个issue

**Comment by xhongc** [comment]
hi，我创建一个交流群（二维码在 readme页面），感兴趣可以加入。群里会谈论项目新进展，和玩nas的交流，你有需要增加的功能可也沟通交流，期待你的加入！

ps. 不想被打扰，不加群也没关系，issue提的问题我也会回答。

**Comment by x1ao4** [comment]
目前的 `专辑艺术家` 设计的是用户自行输入或者通过下拉菜单选择，而不是默认自动刮削（写入）的，能否改为默认自动刮削 `专辑艺术家` 并自动写入 `专辑艺术家` 字段？

因为一些软件比如 Plex 是通过 `专辑艺术家` 来判断专辑所属艺术家的，而 `艺术家` 仅被用于判断歌曲的艺术家，如果 `专辑艺术家` 为空，会造成匹配错误，比如 Plex 会自动将没有 `专辑艺术家` 标签的歌曲的专辑艺术家补充为 `VARIOUS ARTISTS`。

现在的 `艺术家` 实际上是指歌曲的演唱者/艺术家，有时候歌手甲的专辑里可能存在一些合作歌曲，这时候这些歌曲的 `艺术家` 可能有多个，但是 `专辑艺术家` 应该只有歌手甲一个人，否则就会造成匹配错误或者无法匹配的情况。

所以希望可以自动刮削 `专辑艺术家` 并写入标签。
