### ISSUE TITLE
手动匹配看能不匹配到

### ISSUE THREAD

**Issue by wintsa123** [xhongc/music-tag-web#190]
手动匹配看能不匹配到

_Originally posted by @xhongc in https://github.com/xhongc/music-tag-web/issues/189#issuecomment-2065583297_
           
如何手动匹配，我这里只有手动修改的选项

**Comment by xhongc** [comment]
https://xiers-organization.gitbook.io/music-tag-web
https://xiers-organization.gitbook.io/music-tag-web-v2
这是文档
