### ISSUE TITLE
V1输入激活码显示错误，已被激活

### ISSUE THREAD

**Issue by ycxsw** [xhongc/music-tag-web#191]
话说每次使用时都要输入激活码

是因为使用过多这个原因吗。
![1](https://github.com/xhongc/music-tag-web/assets/62132323/2fca1f9c-8b83-44c3-a54e-23f1eeaae07a)

**Comment by xhongc** [comment]
不用每次使用都输入啊，你有映射 /app/data 吗

**Comment by ycxsw** [comment]
> 不用每次使用都输入啊，你有映射 /app/data 吗

好像没有，，，我把这段删了

**Comment by xhongc** [comment]
> > 不用每次使用都输入啊，你有映射 /app/data 吗
> 
> 好像没有，，，我把这段删了


没有这段就需要每次输入激活码的，你激活码前几位发我，我帮你清除激活记录

**Comment by ycxsw** [comment]
> > > 不用每次使用都输入啊，你有映射 /app/data 吗
> > 
> > 
> > 好像没有，，，我把这段删了
> 
> 没有这段就需要每次输入激活码的，你激活码前几位发我，我帮你清除激活记录

MTkzLTIwM   感谢大佬

**Comment by xhongc** [comment]
> > > > 不用每次使用都输入啊，你有映射 /app/data 吗
> > > 
> > > 
> > > 好像没有，，，我把这段删了
> > 
> > 
> > 没有这段就需要每次输入激活码的，你激活码前几位发我，我帮你清除激活记录
> 
> MTkzLTIwM 感谢大佬

好了，有时候没及时看 issue ，可以加我微信
