### ISSUE TITLE
手动匹配也没有，就是平台上没有

### ISSUE THREAD

**Issue by wintsa123** [xhongc/music-tag-web#193]
手动匹配也没有，就是平台上没有

_Originally posted by @xhongc in https://github.com/xhongc/music-tag-web/issues/192#issuecomment-2068648716_
            
我确定网易云平台是有的，容祖儿的歌还是很普遍的

**Comment by xhongc** [comment]
加我微信看看吧

**Comment by wintsa123** [comment]
> 加我微信看看吧

大佬微信号在哪？

**Comment by xhongc** [comment]
github 页面有
