### ISSUE TITLE
是否考虑延伸到普通的桌面端平台，比如 macOS？

### ISSUE THREAD

**Issue by ghost** [xhongc/music-tag-web#194]
如题。大佬的项目很强啊，虽然说我只是当一个元数据刮削器使用。

但是我的音乐大部分在我的 MacBook 上，而目前 macOS 几乎没有什么对国内歌曲支持良好的自动刮削器（Windows 有音乐标签应用），如果在 macOS 跑 Docker 的话实在是太笨重了。

所以大佬有没有兴趣救广大 macOS 音乐爱好者于水火之中呢？ qwq

**Comment by xhongc** [comment]
你可能不清楚，web 和 桌面端的开发是完全不同的技术，我还没有掌握桌面端的开发技能
