### ISSUE TITLE
V2 docker部署后服务报错

### ISSUE THREAD

**Issue by zoverdoser** [xhongc/music-tag-web#198]
music-tag-web  | 2024-05-15 10:28:35,610 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
music-tag-web  | 2024-05-15 10:28:35,688 INFO RPC interface 'supervisor' initialized
music-tag-web  | 2024-05-15 10:28:35,693 CRIT Server 'unix_http_server' running without any HTTP authentication checking
music-tag-web  | 2024-05-15 10:28:35,717 INFO supervisord started with pid 1
music-tag-web  | 2024-05-15 10:28:36,729 INFO spawned: 'xiaoai' with pid 7
music-tag-web  | 2024-05-15 10:28:36,738 INFO spawned: 'beat' with pid 8
music-tag-web  | 2024-05-15 10:28:36,752 INFO spawned: 'worker' with pid 9
music-tag-web  | 2024-05-15 10:28:36,822 INFO spawned: 'redis' with pid 10
music-tag-web  | 2024-05-15 10:28:36,857 INFO spawned: 'nginx' with pid 11
music-tag-web  | 2024-05-15 10:28:36,880 INFO spawned: 'gunicorn' with pid 12
music-tag-web  | 2024-05-15 10:28:37,789 INFO success: xiaoai entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
music-tag-web  | 2024-05-15 10:28:37,793 INFO success: beat entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
music-tag-web  | 2024-05-15 10:28:37,796 INFO success: worker entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
music-tag-web  | 2024-05-15 10:28:37,802 INFO success: redis entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
music-tag-web  | 2024-05-15 10:28:37,805 INFO exited: redis (exit status 0; expected)
music-tag-web  | 2024-05-15 10:28:38,818 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
music-tag-web  | 2024-05-15 10:28:38,821 INFO success: gunicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
music-tag-web  | 2024-05-15 10:30:02,308 INFO exited: beat (exit status 1; not expected)
music-tag-web  | 2024-05-15 10:30:02,365 INFO spawned: 'beat' with pid 28
music-tag-web  | 2024-05-15 10:30:03,449 INFO success: beat entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
music-tag-web  | 2024-05-15 10:30:13,291 INFO exited: gunicorn (exit status 1; not expected)
music-tag-web  | 2024-05-15 10:30:15,911 INFO spawned: 'gunicorn' with pid 33
music-tag-web  | 2024-05-15 10:30:17,204 INFO success: gunicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
music-tag-web  | 2024-05-15 10:31:56,938 INFO exited: beat (exit status 1; not expected)
music-tag-web  | 2024-05-15 10:31:57,995 INFO spawned: 'beat' with pid 37

**Comment by xhongc** [comment]
是不是内存分配不够啊

**Comment by zoverdoser** [comment]
没限制内存，刚才试了最少保留512MB内存也报这个错误

**Comment by xhongc** [comment]
更多的内存试试，v2 要占用 600 多

**Comment by zoverdoser** [comment]
![image](https://github.com/xhongc/music-tag-web/assets/863481/c0436aea-25d5-4f12-b4d2-39362aab34ce)

改成最少800M内存，还是报错

**Comment by xhongc** [comment]
部署命令有没错误



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月22日(周三) 中午11:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xhongc/music-tag-web] V2 docker部署后服务报错 (Issue #198)




 
image.png (view on web)
 
改成最少800M内存，还是报错

**Comment by zoverdoser** [comment]
部署命令不会有错误吧 都是图形化界面操作的

**Comment by xhongc** [comment]
V2 是 8002 端口

**Comment by zoverdoser** [comment]
哦 刚才弄成V1的部署了，V1 V2都不行

**Comment by xhongc** [comment]
也有可能启动慢，性能较低的情况

**Comment by jyyyeung** [comment]
@zoverdoser 你成功了没？我也是docker部署 虽然log没报错 但是去网站显示 `This site can’t be reached`。用的8002，换回8001就能显示，但是【收藏】就一直 loading

**Comment by zoverdoser** [comment]
@jyyyeung 没成功，容器启动完一访问页面日志就报错“gunicorn (exit status 1; not expected)”，页面是nginx的“An error occurred”报错

**Comment by xhongc** [comment]
> This site can’t be reached

可能是浏览器问题，或者代理问题

**Comment by xhongc** [comment]
> @jyyyeung 没成功，容器启动完一访问页面日志就报错“gunicorn (exit status 1; not expected)”，页面是nginx的“An error occurred”报错

不应该啊，你的部署命令是什么呢

**Comment by zoverdoser** [comment]
> 不应该啊，你的部署命令是什么呢

version: '3'

services:
  music-tag:
    image: xhongc/music_tag_web:latest
    container_name: music-tag-web
    ports:
      - "5710:8002"
    volumes:
      - /shared/music:/app/media:rw
    restart: unless-stopped

**Comment by xhongc** [comment]
> > 不应该啊，你的部署命令是什么呢
> 
> version: '3'
> 
> services: music-tag: image: xhongc/music_tag_web:latest container_name: music-tag-web ports: - "5710:8002" volumes: - /shared/music:/app/media:rw restart: unless-stopped

app/data 没有挂载

**Comment by zoverdoser** [comment]
> app/data 没有挂载

对我去掉了，app/data 必须要挂载么？不挂载不能用容器里的目录么？

挂载上app/data 之后可以正常启动了
