### ISSUE TITLE
v2 什么时候支持armv8呢

### ISSUE THREAD

**Issue by chen1204-st** [xhongc/music-tag-web#199]
v2 什么时候支持armv8呢

**Comment by xhongc** [comment]
armv8是什么设备啊

**Comment by waf2311** [comment]
软路由，我的是友善R5C。

**Comment by kingsey** [comment]
不支持linux/arm64/v8是没想到的，更没想到作者不知道armv8……

**Comment by xhongc** [comment]
> 不支持linux/arm64/v8是没想到的，更没想到作者不知道armv8……

🫣

**Comment by LeJTao** [comment]
项目很棒，希望尽快支持。这样我的mac mini也能使用这个功能了

**Comment by xhongc** [comment]
> 项目很棒，希望尽快支持。这样我的mac mini也能使用这个功能了

arm64 是支持的

**Comment by LeJTao** [comment]
> > 项目很棒，希望尽快支持。这样我的mac mini也能使用这个功能了
> 
> arm64 是支持的

前几天没仔细看，直接docker pull 最新的镜像是没有匹配的，今天看docker hub 2.0.9和之前的版本是有的

**Comment by xhongc** [comment]
> > > 项目很棒，希望尽快支持。这样我的mac mini也能使用这个功能了
> > 
> > 
> > arm64 是支持的
> 
> 前几天没仔细看，直接docker pull 最新的镜像是没有匹配的，今天看docker hub 2.0.9和之前的版本是有的

是， latest 不小心被覆盖掉，原先也是有的
