### ISSUE TITLE
CD号功能能否提供

### ISSUE THREAD

**Issue by cnlaok** [xhongc/music-tag-web#20]
首选感谢您提供这么好得程序，我也是用navidrome建音乐课放在远程服务端，用MP3tag等搜刮实在速度太慢。
用music tag web真得速度非常快也非常好用。
我有很多多碟得音乐，如果能提供CD号修改就太好了。
还有一个我发现某些乱码的wav文件，标签虽然能修改，却在navidrome里被识别为乱码。
再次感谢提供如此好的应用。谢谢

**Comment by xhongc** [comment]
> 碟得音乐，如果能提供
音乐CD号号是指哪个？
乱码的wav文件 识别后所有字段都是乱码吗，是不是有些字段没修改到的是

**Comment by cnlaok** [comment]
我的意思是某专辑有5CD，如果不设置CD号，navidrome里是根据歌曲序号排的，会比较乱。
乱码的wav，这个个别文件是这样，我自己花了2天找不到原因。mp3tag里看已经全是英文了。

**Comment by xhongc** [comment]
> 

tracknumber是你所说的cd号吧
![image](https://github.com/xhongc/music-tag-web/assets/29135056/caef2bda-5dd2-4ee7-b982-e97b1bdde97b)

**Comment by cnlaok** [comment]
我主要想要的是discnumber，如果tracknumber也有就更好了。

**Comment by xhongc** [comment]
> 我主要想要的是discnumber，如果tracknumber也有就更好了。


支持修改光盘编号和音轨号 ，镜像版本在1.1.2
