### ISSUE TITLE
关于emby没有识别music-tag-web写入的年代问题求助

### ISSUE THREAD

**Issue by baibai1989** [xhongc/music-tag-web#203]
我是使用音流链接emby来使用的，但我发现music-tag-web写入的年代，没有被emby自动识别，就空着，导致音流默认显示了1970，大家有遇到这个问题么，能怎么解决
因为我收藏的音乐比较小小众，所以很多信息是自动削刮不到的，所以我是手动在本项目写入保存的，刚刚发电升到了v2，重新保存试了试，emby还是没识别

**Comment by xhongc** [comment]
写入一般就是有的，emby 没识别 可能是还没同步
