### ISSUE TITLE
源码与docker不一致

### ISSUE THREAD

**Issue by lixiaoyu0123** [xhongc/music-tag-web#205]
开源的源码与docker的版本不一致
docker中有的接口， 开放的源码中没有。  比如replace_text这个接口。
docker容器中进行了py转so的处理。  
挂着开源的名义而已。其实并没有真正的开源。

**Comment by xhongc** [comment]
v2 部分没有开源，只开源了 v1版本

**Comment by lixiaoyu0123** [comment]
> v2 部分没有开源，只开源了 v1版本

非常理解辛苦投入不易。 也理解v2不开源的初衷。
只是我部署的是v1的docker， 但里面的replace_text接口。 却没有github上的实现。

**Comment by lixiaoyu0123** [comment]
replace_text功能不支持正则，我想正则替换掉title里面乱七八糟的数字。但是不支持正则，所以想去源码改一下。
发现源码与docker的容器不一致。

**Comment by xhongc** [comment]
> replace_text功能不支持正则，我想正则替换掉title里面乱七八糟的数字。但是不支持正则，所以想去源码改一下。 发现源码与docker的容器不一致。

目前确实是不支持正则替换，后续会考虑添加的
