### ISSUE TITLE
alist链接配置正确但播放地址被加了/d导致无法播放

### ISSUE THREAD

**Issue by Adolph-Adolf** [xhongc/music-tag-web#206]
mtw内路径:
![image](https://github.com/xhongc/music-tag-web/assets/58133035/5744eac4-5a2d-4959-9345-25a6fd097ef7)
实际路径:
![image](https://github.com/xhongc/music-tag-web/assets/58133035/186bdd11-cd61-40f1-b4a6-6683ae85900c)
mtw添加的alist'地址：
http://192.168.1.104:5244/volume1/CloudNAS/CloudDrive/115/volume1/music/
但播放时无法播放，看请求地址为:
![image](https://github.com/xhongc/music-tag-web/assets/58133035/f3992a8e-e422-4136-9a5b-ba7c05138b3c)
实测去掉/d可以正常播放

**Comment by xhongc** [comment]
mtw内路径:要是 volume1/CloudNAS/CloudDrive/115/volume1/music/
mtw添加的alist'地址：http://192.168.1.104:5244
这样的
