### ISSUE TITLE
请问有没有登录用户和密码功能呀

### ISSUE THREAD

**Issue by terryyj** [xhongc/music-tag-web#21]
因为好像直接访问就能进去了，但是因为是有公网ip的，怕别人登录上去乱搞，所以想问问是不是有需要用户名和密码才能登录刮削界面的功能？

**Comment by xhongc** [comment]
可以有

**Comment by terryyj** [comment]
多谢大佬，期待~

**Comment by xhongc** [comment]
> 多谢大佬，期待~


新增登录功能 ，镜像版本1.1.2

**Comment by xhongc** [comment]
默认账号密码是 admin/admin

修改密码在后台地址：/admin/
<img width="643" alt="image" src="https://github.com/xhongc/music-tag-web/assets/29135056/99cebe80-1313-4f39-865f-325999e29ebf">

**Comment by xhongc** [comment]
hi，我创建一个交流群（二维码在 readme页面），感兴趣可以加入。群里会谈论项目新进展，和玩nas的交流，你有需要增加的功能可也沟通交流，期待你的加入！

ps. 不想被打扰，不加群也没关系，issue提的问题我也会回答。
