### ISSUE TITLE
整理文件夹时根目录填写问题

### ISSUE THREAD

**Issue by WtXeLd** [xhongc/music-tag-web#215]
Windows 批量整理文件夹时，根目录手动修改成了本地磁盘目录，整理后本地资源全部消失，不知道是移动到哪里了，是目录错误被删除了，还是存到了奇怪的地方，求解答~

![Snipaste_2024-06-17_00-01-09](https://github.com/xhongc/music-tag-web/assets/14245687/7b05eb37-e8eb-4177-8650-145789304cab)

**Comment by xhongc** [comment]
拉最新的版本

**Comment by xhongc** [comment]
之前的一个 bug 来的
