### ISSUE TITLE
内置歌词

### ISSUE THREAD

**Issue by yuan93** [xhongc/music-tag-web#22]
大佬内置歌词删不掉

**Comment by xhongc** [comment]
> 大佬内置歌词删不掉

用其他歌词替换 或 随便打个符号，现在逻辑是为空不修改

**Comment by yuan93** [comment]
嗯

**Comment by yuan93** [comment]
话说那个歌词，能不能加个单独保存歌词到本地的开关，不写入歌曲

**Comment by xhongc** [comment]
> 话说那个歌词，能不能加个单独保存歌词到本地的开关，不写入歌曲

话说 写入也没有关系吧

**Comment by yuan93** [comment]
有关系，写入了不能删，搞了符号进去，我这边歌词就显示符号了，不能显示歌词了

**Comment by yuan93** [comment]
其实最好是可以为空最好，写入歌词也不合适直接删了，合适了保留本地，tag就不需要保留了

**Comment by xhongc** [comment]
> 其实最好是可以为空最好，写入歌词也不合适直接删了，合适了保留本地，tag就不需要保留了

可以啊，我加上

**Comment by yuan93** [comment]
😂麻烦了

**Comment by xhongc** [comment]
> 😂麻烦了

更新在镜像版本1.1.3

**Comment by xhongc** [comment]
hi，我创建一个交流群（二维码在 readme页面），感兴趣可以加入。群里会谈论项目新进展，和玩nas的交流，你有需要增加的功能可也沟通交流，期待你的加入！

ps. 不想被打扰，不加群也没关系，issue提的问题我也会回答。
