### ISSUE TITLE
专辑类型 plex 无法识别，能加一个可自定义输入吗

### ISSUE THREAD

**Issue by bankroft** [xhongc/music-tag-web#222]

**Comment by xhongc** [comment]
plex 的专辑类型是什么

**Comment by bankroft** [comment]
> plex 的专辑类型是什么

plex没有明确给出类型支持，但是plex使用MusicBrainz来匹配资源，我用picard修改的专辑类型plex可以识别出来

[MusicBrainz Release Type](https://musicbrainz.org/doc/Release_Group/Type):

- album
- single
- broadcast
- ep
- other
- audio drama
- audiobook
- compilation
- dj-mix
- demo
- field recording
- interview
- live
- mixtape/street
- remix
- soundtrack
- spokenword

**Comment by xhongc** [comment]
可以上传一首识别到专辑类型的音乐给我

**Comment by bankroft** [comment]
plex可以识别为EP/单曲的音乐：https://github.com/bankroft/bankroft.github.io/releases/download/test/test.zip
