### ISSUE TITLE
请增加仅按文件名刮削DTS音乐功能

### ISSUE THREAD

**Issue by capsshift** [xhongc/music-tag-web#224]
现在系统不能识别扩展名为DTS的无损音乐格式，文件名已经按规范命名了。请让系统能读出DTS文件列表，而不需要读取标签信息，进行刮削。

**Comment by xhongc** [comment]
您好！感谢您使用我们的项目并提出问题。我注意到您的描述可能不够详细，这可能会影响到我们解决问题的效率。建议您参考以下模板补充信息：[问题发生的具体步骤、期望结果、实际结果、环境配置等]。这样我们可以更快地为您提供帮助。谢谢合作！
