### ISSUE TITLE
重新加载歌曲信息问题

### ISSUE THREAD

**Issue by sc962** [xhongc/music-tag-web#226]
有时候歌曲用其他方式修改了信息，不知道怎么重新载入信息。
尝试重新添加一边歌曲来刷新信息，结果之前修改好的艺术家缺失封面信息全都没了。

还有专辑重复问题，手机上的椒盐音乐也有这问题，跟开发者沟通后他说是专辑名称前后空格引起的问题，他修改后发的测试版就没有这个问题了。希望能查查这边是不是同样的问题引起的。

**Comment by xhongc** [comment]
1. 你是删除音乐收藏 再 重新添加一边歌曲来刷新信息 ，导致 艺术家缺失封面信息全都没了 吗？
2.ok

**Comment by sc962** [comment]
> 1. 你是删除音乐收藏 再 重新添加一边歌曲来刷新信息 ，导致 艺术家缺失封面信息全都没了 吗？
>        2.ok

没有删除音乐收藏，我是直接在操作台把所有歌曲全选后导入收藏，结果之前我弄的艺术家缺失封面信息就全没了，又要重新弄一遍
