### ISSUE TITLE
爱发电无法赞助

### ISSUE THREAD

**Issue by orion-tan** [xhongc/music-tag-web#227]
## 爱发电域名目前已经无法访问，希望能提供其他赞助方式。

[蓝点网消息15日消息](https://www.landiannews.com/archives/104953.html)

![1000003354](https://github.com/user-attachments/assets/d4d7573d-eb50-49f5-8837-2a2c347efa18)

**Comment by xhongc** [comment]
是的，爱发电最近挂掉了。
不建议的话可以添加我的微信 
微信号：charlesnowed

**Comment by orion-tan** [comment]
好的

xier ***@***.***> 于2024年7月16日周二 14:32写道：
