### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by liuran001** [xhongc/music-tag-web#228]
1. 操作台支持异步加载歌曲列表
在歌曲数足够多的时候（我这边有 2662 首）进入操作台会因加载歌曲列表而冻结页面几秒钟
2. 建议支持 Last.FM 同步播放记录
这个功能加上基本可以完全替代 Navidrome 了，我现在还留着一个 Navidrome 就是因为它可以把播放记录同步到 Last.FM
3. 建议增强小爱音箱功能
目前小爱音箱功能只有基础的播放，建议可以参考一下 https://github.com/hanxi/xiaomusic 加入更多功能
4. 后台刮削支持在歌词中加入翻译
目前我看好像只有控制台那里可以获取歌词翻译，而且获取的翻译外面有个括号，我个人觉得没什么必要，建议和音乐标签手机版一样可以自选翻译添加方式，然后后台刮削时也可以把翻译直接加进来
5. 建议支持获取艺术家头像
Subsonic 协议好像是可以获取艺术家头像的，Navidrome 那边是从 Spotify 拉头像然后 Subsonic 协议的软件都能正常显示
~~这倒不是什么大问题，隔壁 Navidrome 虽然支持显示头像，但是按艺术家分组也是废的，至今还不支持多艺术家~~

然后还有个小问题，V2的授权是可以多次激活还是新激活会把旧的给反激活了，到时候重装 Docker 了是不是直接用之前的激活码激活就行

感谢大佬的项目，这应该是我见到本地音乐库最好用的软件了

**Comment by xhongc** [comment]
1. 2662 首歌曲不算很多，应该不会卡死吧，机器性能怎么样？
2. Last.FM 后续可以考虑吧，比较少人有这个需求
3. 基本功能是有的，你说的更多指什么
4. 比较麻烦，后续考虑
5. 其他设置-刮削艺术家 ，或者 单个艺术家 edit 都可以获取到艺术家封面呢
6. 多次激活上一个设备就会失效了

**Comment by liuran001** [comment]
@xhongc 性能肯定是没问题的，看起来似乎就是加载歌曲列表的时候阻塞了点击事件
我录了个屏可以看下

https://github.com/user-attachments/assets/24d0a052-b708-4262-88f8-0ca29040ec2f

然后小爱的话，要说好像确实基础播放功能就够了
不过后台不是有音乐播放功能吗，可以考虑一下直接在网页后台向小爱或者内网DLNA设备推送歌曲进行播放
也可以考虑向上面的 xiaomusic 项目一样，在后台加一些小爱音箱控制功能
![Screenshot_2024-07-17-22-43-04-28_e4424258c8b8649f6e67d283a50a2cbc](https://github.com/user-attachments/assets/c7e54173-b2f5-469f-9da6-6c240a501f6b)
不过这倒不是什么刚需，看作者有没有兴趣研究一下吧

刮削艺术家之前没注意到这个功能，试了下没有问题了

**Comment by liuran001** [comment]
@xhongc 试了下点刮削艺术家之后，后台是能拉到艺术家图片了，但是 Subsonic 协议好像还是拉不到
比如我用 Symfonium 的时候，Navidrome 是这样的
（因为它是去 Spotify 拉图，速度太慢了我就没等它全部刮削完）
![Screenshot_2024-07-17-23-38-06-42_5a95cb7a76adf25e43f1cd66aca96a7a](https://github.com/user-attachments/assets/99526046-6b66-44b5-aa90-73e9454df982)
这是用本项目的
![Screenshot_2024-07-17-23-39-42-63_5a95cb7a76adf25e43f1cd66aca96a7a](https://github.com/user-attachments/assets/d645feba-90ec-43fc-af1d-509cc4a6d54f)

**Comment by xhongc** [comment]
本项目的 subsonic 在Symfonium 不显示艺术家封面是 bug，下个版本会修复

**Comment by liuran001** [comment]
@xhongc 还有个问题，这里的 Subsonic 我用 [棉花音乐](https://music.caij.xyz/zh/) 读到的音乐是空的，用 Navidrome 正常
但是我不确定是播放器的问题还是这边的问题，大佬要是方便的话可以看看，如果是播放器的问题我去看看能不能反馈下

**Comment by xhongc** [comment]
加我微信呗，charlesnowed
