### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Yumega** [xhongc/music-tag-web#23]
stderr:   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
stderr:     return _bootstrap._gcd_import(name[level:], package, level)
stderr:   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
stderr:   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
stderr:   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
stderr:   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
stderr:   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
stderr:   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
stderr:   File "/app/django_vue_cli/urls.py", line 5, in <module>
stderr:     from applications.task.urls import router as task_router
stderr:   File "/app/applications/task/urls.py", line 3, in <module>
stderr:     from . import views
stderr:   File "/app/applications/task/views.py", line 17, in <module>
stderr:     from applications.utils.translation import translation_lyc_text
stderr:   File "/app/applications/utils/translation.py", line 8, in <module>
stderr:     from component import translators as ts
stderr:   File "/app/component/translators/__init__.py", line 5, in <module>
stderr:     from .server import translate_text, translate_html, translators_pool, get_languages, preaccelerate_and_speedtest
stderr:   File "/app/component/translators/server.py", line 5310, in <module>
stderr:     tss = TranslatorsServer()
stderr:   File "/app/component/translators/server.py", line 5025, in __init__
stderr:     self.server_region = GuestSeverRegion().get_server_region
stderr:   File "/app/component/translators/server.py", line 328, in get_server_region
stderr:     raise TranslatorError('Unable to connect the Internet.\n\n')
stderr: component.translators.server.TranslatorError: Unable to connect the Internet.
stderr: 
stderr:

**Comment by xhongc** [comment]
> stderr: File "/usr/local/lib/python3.9/importlib/**init**.py", line 127, in import_module stderr: return _bootstrap._gcd_import(name[level:], package, level) stderr: File "", line 1030, in _gcd_import stderr: File "", line 1007, in _find_and_load stderr: File "", line 986, in _find_and_load_unlocked stderr: File "", line 680, in _load_unlocked stderr: File "", line 850, in exec_module stderr: File "", line 228, in _call_with_frames_removed stderr: File "/app/django_vue_cli/urls.py", line 5, in stderr: from applications.task.urls import router as task_router stderr: File "/app/applications/task/urls.py", line 3, in stderr: from . import views stderr: File "/app/applications/task/views.py", line 17, in stderr: from applications.utils.translation import translation_lyc_text stderr: File "/app/applications/utils/translation.py", line 8, in stderr: from component import translators as ts stderr: File "/app/component/translators/**init**.py", line 5, in stderr: from .server import translate_text, translate_html, translators_pool, get_languages, preaccelerate_and_speedtest stderr: File "/app/component/translators/server.py", line 5310, in stderr: tss = TranslatorsServer() stderr: File "/app/component/translators/server.py", line 5025, in **init** stderr: self.server_region = GuestSeverRegion().get_server_region stderr: File "/app/component/translators/server.py", line 328, in get_server_region stderr: raise TranslatorError('Unable to connect the Internet.\n\n') stderr: component.translators.server.TranslatorError: Unable to connect the Internet. stderr: stderr:

怎么复现，docker部署的吗

**Comment by Yumega** [comment]
是的

**Comment by xhongc** [comment]
我并没有测出这个问题

**Comment by xhongc** [comment]
hi，我创建一个交流群（二维码在 readme页面），感兴趣可以加入。群里会谈论项目新进展，和玩nas的交流，你有需要增加的功能可也沟通交流，期待你的加入！

ps. 不想被打扰，不加群也没关系，issue提的问题我也会回答。
