### ISSUE TITLE
批量处理tag遇到的麻烦

### ISSUE THREAD

**Issue by igs666** [xhongc/music-tag-web#230]
播放软件为roon，使用中有如下想法：

1.**希望有像musictag本地版类似的自动格式化时间轴、删除空白行、下载翻译功能**
批量自动刮削后，检索到的网易云歌词时间轴精确到毫秒（0.001s），而播放器只能识别到十毫秒（0.01s），需要自己手动格式化时间把三位毫秒转二位毫秒。
此外，注意到web端格式化时间按钮并非省略[00:00.abc]的最后一位小数c，而是直接删除掉了a保留了后两位bc，希望后续优化一下代码
![music](https://github.com/user-attachments/assets/65baeefb-a513-4b01-82c9-695d384666aa)

2.**希望歌词时间的正反向偏移可以精确到0.1秒**
这个功能很有帮助，就是一秒有点长
![music2](https://github.com/user-attachments/assets/fbd86b46-7d0a-4e7a-8a9b-754afe1ed189)

3.**希望自动刮削时，遇到艺术家/专辑艺术家有多人时能使用分号而非逗号隔开**
播放器只认英文分号，逗号会识别为一整个歌手名，分类管理起来比较麻烦，需要一个一个改
![music3](https://github.com/user-attachments/assets/56d5ae38-cccc-452e-8aea-c9d7dd70b971)

**Comment by xhongc** [comment]
1. [00:00.abc] 格式化，确实有这个问题，我将修改它
2. ok
3. 现在我用的分割就是 英文的逗号吧
