### ISSUE TITLE
扫描文件的时候，能不能过滤隐藏文件？或者给个通用匹配的选项填写？

### ISSUE THREAD

**Issue by EternalSunLhx** [xhongc/music-tag-web#231]
<img width="331" alt="image" src="https://github.com/user-attachments/assets/2b668f8e-fe87-4b3b-93af-93fffacaf021">
如图，.开头的文件是隐藏文件，也会被扫描出来，刮削的时候就会报错。
希望过滤掉隐藏文件，或者添加过滤文件的通用匹配选项

**Comment by xhongc** [comment]
好
