### ISSUE TITLE
导入图片的时候提示错误

### ISSUE THREAD

**Issue by 3377** [xhongc/music-tag-web#235]
环境为群晖下cd2挂载115
可以修改文件名，无法导入图片
![image](https://github.com/user-attachments/assets/712721ee-e251-4945-84ab-44942ffa91bd)

**Comment by ZhC0925** [comment]
请问有解决吗？

**Comment by xhongc** [comment]
> 请问有解决吗？

需要提供更多信息

**Comment by HelloMusician** [comment]
> 请问有解决吗？

下面专辑图片那选导出图片或者导入导出都去掉就能保存成功了
