### ISSUE TITLE
自动刮削任务进度始终为0 

### ISSUE THREAD

**Issue by Chopper-king** [xhongc/music-tag-web#236]
<img width="1085" alt="temp" src="https://github.com/user-attachments/assets/3cc4b3ec-f0b1-44fb-a1cc-23d478782c9b">
自动刮削过程，在操作记录查看刮削报告，进度始终为0

**Comment by xhongc** [comment]
先检查一下你是否按照文档部署。
https://xiers-organization.gitbook.io/music-tag-web-v2

**Comment by Chopper-king** [comment]
> 先检查一下你是否按照文档部署。 https://xiers-organization.gitbook.io/music-tag-web-v2

1、按照群晖部署方式部署的，只是并未配置 进阶部署mysql。
2、重复尝试了几次，最新的一次又正常了，需要再观察使用，如果有问题再反馈。
