### ISSUE TITLE
网盘音乐使用中遇到的问题

### ISSUE THREAD

**Issue by nsfw404** [xhongc/music-tag-web#238]
不管是使用rclone直接挂载od还是通过davfs2挂载webdav在选择歌曲的时候都提示“加载文件失败, 请检查文件是否损坏:invalid literal for int() with base 10: '' ”。
![image](https://github.com/user-attachments/assets/2cdc824b-d199-4419-b22c-1d5daf6edc76)

**Comment by xhongc** [comment]
已修复
