### ISSUE TITLE
unraid部署docker后，无法打开网页，页面和日志报错见附件

### ISSUE THREAD

**Issue by ltcsky2000** [xhongc/music-tag-web#239]
![1](https://github.com/user-attachments/assets/c8916e02-8b04-493b-9f75-e9b9184e6caa)
![2](https://github.com/user-attachments/assets/e18a23ca-a603-4801-bfd3-32daf3b4e109)
![3](https://github.com/user-attachments/assets/76175275-406b-4d2b-95b0-28c3a3749186)

**Comment by gldl137** [comment]
把特权打开
privileged,这个选项
<img width="596" alt="QQ拼音截图20240830183207" src="https://github.com/user-attachments/assets/7a33bb19-f740-4cbe-99fb-900ff32ae0c0">

**Comment by ltcsky2000** [comment]
打开后错误照旧:(

**Comment by gldl137** [comment]
我的没问题
<img width="1252" alt="11" src="https://github.com/user-attachments/assets/5206cc18-15c1-46b6-9577-fa27d3b5d64c">

**Comment by ltcsky2000** [comment]
重新拉取库，去掉:lateset，就没问题了，不过部署好是V1版本，jV2提示需要激活码
