### ISSUE TITLE
映射文件夹不显示文件

### ISSUE THREAD

**Issue by pubg-Eddie** [xhongc/music-tag-web#24]
我部署路径是这样的/path/to/opt/plex/music:/app/media，但是在music-tag-web获取不到音乐文件
![image](https://github.com/xhongc/music-tag-web/assets/70614635/38c6872d-a031-4e71-b56d-e09fa7d10ffa)
![image](https://github.com/xhongc/music-tag-web/assets/70614635/ad3ec244-ec06-4037-9f79-5ef9c306915d)

**Comment by pubg-Eddie** [comment]
这个是日志截图
![image](https://github.com/xhongc/music-tag-web/assets/70614635/b6173c34-0b1e-4f4e-ae76-186eafb76fe4)

**Comment by xhongc** [comment]
> /path/to/opt/plex/music:/app/media

/path/to/your/music 意思是把这一串都改为你的音乐路径，例如你的路径是/opt/plex/music:/app/media 即可

**Comment by pubg-Eddie** [comment]
> > /path/to/opt/plex/music：/app/media
> 
> /path/to/your/music 意思是把这一串都改为你的音乐路径，例如你的路径是/opt/plex/music：/app/media 即可

路径没问题
![image](https://github.com/xhongc/music-tag-web/assets/70614635/6c23a484-973f-4d00-b06d-8224abab5d8f)
![image](https://github.com/xhongc/music-tag-web/assets/70614635/34ba7fb4-7b1b-4711-bf61-2eed566a9148)
产生了报错，日志如下：
![image](https://github.com/xhongc/music-tag-web/assets/70614635/5cae084b-9719-4235-9b25-c418cb8d0305)

**Comment by xhongc** [comment]
> > > /path/to/opt/plex/music：/app/media
> > 
> > 
> > /path/to/your/music 意思是把这一串都改为你的音乐路径，例如你的路径是/opt/plex/music：/app/media 即可
> 
> 路径没问题 ![image](https://user-images.githubusercontent.com/70614635/258690550-6c23a484-973f-4d00-b06d-8224abab5d8f.png) ![image](https://user-images.githubusercontent.com/70614635/258690662-34ba7fb4-7b1b-4711-bf61-2eed566a9148.png) 产生了报错，日志如下： ![image](https://user-images.githubusercontent.com/70614635/258690606-5cae084b-9719-4235-9b25-c418cb8d0305.png)

看样子是 映射中有个文件的编码出现了问题

**Comment by xhongc** [comment]
试试 1.1.6 版本

**Comment by pubg-Eddie** [comment]
> 试试 1.1.6 版本
文件可以显示出来了，文件名称乱码是编码问题吗？还有就是点击修改没效果，日志如下
![image](https://github.com/xhongc/music-tag-web/assets/70614635/028560be-56d3-42ac-a75e-679e8f565503)
![image](https://github.com/xhongc/music-tag-web/assets/70614635/112c37d7-3acc-41db-bf61-9eafae941a3d)

**Comment by xhongc** [comment]
> > 试试 1.1.6 版本
> > 文件可以显示出来了，文件名称乱码是编码问题吗？还有就是点击修改没效果，日志如下
> > ![image](https://user-images.githubusercontent.com/70614635/258732263-028560be-56d3-42ac-a75e-679e8f565503.png)
> > ![image](https://user-images.githubusercontent.com/70614635/258732026-112c37d7-3acc-41db-bf61-9eafae941a3d.png)

发我一个你的mp3文件吧，我测试一下

**Comment by pubg-Eddie** [comment]
请查收
[背影 - 林宥嘉.zip](https://github.com/xhongc/music-tag-web/files/12279056/-.zip)

**Comment by pubg-Eddie** [comment]
> > > 试试 1.1.6 版本
> > > 文件可以显示出来了，文件名称乱码是编码问题吗？还有就是点击修改没效果，日志如下
> > > ![image](https://user-images.githubusercontent.com/70614635/258732263-028560be-56d3-42ac-a75e-679e8f565503.png)
> > > ![image](https://user-images.githubusercontent.com/70614635/258732026-112c37d7-3acc-41db-bf61-9eafae941a3d.png)
> 
> 发我一个你的mp3文件吧，我测试一下

已发

**Comment by xhongc** [comment]
<img width="517" alt="image" src="https://github.com/xhongc/music-tag-web/assets/29135056/5404d7d4-cc2b-4f31-ab1f-3aa8aadc8889">
确实存在文件名称 编码有问题，你需要先将名称进行修改，可以按图片所示手动批量改成 标题的值（如果有标题的话），
报错内容是文件名乱码 不能使用 音纹识别，不勾选就可以了

**Comment by xhongc** [comment]
hi，我创建一个交流群（二维码在 readme页面），感兴趣可以加入。群里会谈论项目新进展，和玩nas的交流，你有需要增加的功能可也沟通交流，期待你的加入！

ps. 不想被打扰，不加群也没关系，issue提的问题我也会回答。
