### ISSUE TITLE
文件加载失败

### ISSUE THREAD

**Issue by Rookiewan** [xhongc/music-tag-web#242]
看 icon 好像被识别成 script 文件了，但是在播放器是可以正常播放的

报错截图：
![image](https://github.com/user-attachments/assets/7c35ed54-63a8-42a7-91d9-5fa5cd46bd70)

音频文件：
[Uploading 男孩别哭 - 海龟先生.flac.zip…]()

**Comment by Rookiewan** [comment]
使用自动刮削看到日志了
![image](https://github.com/user-attachments/assets/1516028b-005b-4f56-8cf5-6162710e37a0)

**Comment by xhongc** [comment]
音乐的元数据是损坏的，读不出来，所以是能播放，不能改元数据

**Comment by Rookiewan** [comment]
原来是这样，那我看下有没有办法修复。大佬辛苦了
