### ISSUE TITLE
v2版本中缺失封面的艺术家无法打开

### ISSUE THREAD

**Issue by Nothend** [xhongc/music-tag-web#243]
v2版本中缺失封面的艺术家无法打开，进而无法删除。在操作台中进行了删除空文件夹、删除无音乐文件的目录两项操作还是无法进入 缺失封面的艺术家里面。我的目的是想删除，好像只能进入才能删除。

https://github.com/user-attachments/assets/b7cd7fdb-2a16-42c7-915e-8a616759347c

**Comment by xhongc** [comment]
在后台管理里面可以删除，你说的这个问题我排查一下
