### ISSUE TITLE
数据库换成MySQL后，music-tag-web网页就打不开了

### ISSUE THREAD

**Issue by Nothend** [xhongc/music-tag-web#245]
大佬你好，换成mysql数据库后，mtw网页打不开了，v2版本。mtw的日志如下：

`2024-09-13 02:28:39,099 INFO success: gunicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
-- | -- | --
2024/09/13 10:28:38 | stdout | 2024-09-13 02:28:37,842 INFO success: beat entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024/09/13 10:28:37 | stdout | 2024-09-13 02:28:37,842 INFO spawned: 'gunicorn' with pid 1099
2024/09/13 10:28:37 | stdout | 2024-09-13 02:28:37,606 INFO exited: gunicorn (exit status 1; not expected)
2024/09/13 10:28:36 | stdout | 2024-09-13 02:28:36,730 INFO spawned: 'beat' with pid 1096
2024/09/13 10:28:36 | stdout | 2024-09-13 02:28:36,685 INFO exited: beat (exit status 1; not expected)
2024/09/13 10:28:35 | stdout | 2024-09-13 02:28:35,941 INFO success: gunicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024/09/13 10:28:34 | stdout | 2024-09-13 02:28:34,695 INFO success: beat entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024/09/13 10:28:34 | stdout | 2024-09-13 02:28:34,695 INFO spawned: 'gunicorn' with pid 1093
2024/09/13 10:28:34 | stdout | 2024-09-13 02:28:34,458 INFO exited: gunicorn (exit status 1; not expected)
2024/09/13 10:28:33 | stdout | 2024-09-13 02:28:33,581 INFO spawned: 'beat' with pid 1090
2024/09/13 10:28:33 | stdout | 2024-09-13 02:28:33,533 INFO exited: beat (exit status 1; not expected)
2024/09/13 10:28:32 | stdout | 2024-09-13 02:28:32,789 INFO success: gunicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024/09/13 10:28:31 | stdout | 2024-09-13 02:28:31,545 INFO success: beat entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024/09/13 10:28:31 | stdout | 2024-09-13 02:28:31,545 INFO spawned: 'gunicorn' with pid 1087
2024/09/13 10:28:31 | stdout | 2024-09-13 02:28:31,308 INFO exited: gunicorn (exit status 1; not expected)
2024/09/13 10:28:30 | stdout | 2024-09-13 02:28:30,435 INFO spawned: 'beat' with pid 1084
2024/09/13 10:28:30 | stdout | 2024-09-13 02:28:30,391 INFO exited: beat (exit status 1; not expected)
2024/09/13 10:28:29 | stdout | 2024-09-13 02:28:29,648 INFO success: gunicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024/09/13 10:28:28 | stdout | 2024-09-13 02:28:28,397 INFO success: beat entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024/09/13 10:28:28 | stdout | 2024-09-13 02:28:28,397 INFO spawned: 'gunicorn' with pid 1081
2024/09/13 10:28:28 | stdout | 2024-09-13 02:28:28,162 INFO exited: gunicorn (exit status 1; not expected)
2024/09/13 10:28:27 | stdout | 2024-09-13 02:28:27,279 INFO spawned: 'beat' with pid 1078
2024/09/13 10:28:27 | stdout | 2024-09-13 02:28:27,232 INFO exited: beat (exit status 1; not expected)
2024/09/13 10:28:26 | stdout | 2024-09-13 02:28:26,489 INFO success: gunicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024/09/13 10:28:25 | stdout | 2024-09-13 02:28:25,245 INFO success: beat entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024/09/13 10:28:25 | stdout | 2024-09-13 02:28:25,244 INFO spawned: 'gunicorn' with pid 1075
2024/09/13 10:28:25 | stdout | 2024-09-13 02:28:25,002 INFO exited: gunicorn (exit status 1; not expected)
2024/09/13 10:28:24 | stdout | 2024-09-13 02:28:24,126 INFO spawned: 'beat' with pid 1072
2024/09/13 10:28:24 | stdout | 2024-09-13 02:28:24,094 INFO exited: beat (exit status 1; not expected)
2024/09/13 10:28:23 | stdout | 2024-09-13 02:28:23,341 INFO success: gunicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024/09/13 10:28:22 | stdout | 2024-09-13 02:28:22,090 INFO success: beat entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024/09/13 10:28:22 | stdout | 2024-09-13 02:28:22,090 INFO spawned: 'gunicorn' with pid 1069
2024/09/13 10:28:21 | stdout | 2024-09-13 02:28:21,846 INFO exited: gunicorn (exit status 1; not expected)
2024/09/13 10:28:20 | stdout | 2024-09-13 02:28:20,975 INFO spawned: 'beat' with pid 1066
`

一直进行这样的循环。

MySQL的日志是正常的：
`
2024/09/13 10:14:03 | stderr | 2024-09-13T02:14:03.164311Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '9.0.1'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.
2024/09/13 10:14:03 | stderr | 2024-09-13T02:14:03.164260Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /var/run/mysqld/mysqlx.sock
2024/09/13 10:14:02 | stderr | 2024-09-13T02:14:02.944219Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
2024/09/13 10:14:02 | stderr | 2024-09-13T02:14:02.894205Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
2024/09/13 10:14:02 | stderr | 2024-09-13T02:14:02.894182Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
2024/09/13 10:13:58 | stderr | 2024-09-13T02:13:58.950668Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
2024/09/13 10:13:48 | stderr | 2024-09-13T02:13:47.765626Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
2024/09/13 10:13:48 | stderr | 2024-09-13T02:13:47.759222Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 9.0.1) starting as process 1
2024/09/13 10:13:47 | stderr | 2024-09-13T02:13:47.576843Z 0 [System] [MY-015015] [Server] MySQL Server - start.
2024/09/13 10:13:47 | stdout |  
2024/09/13 10:13:47 | stdout | 2024-09-13 02:13:47+00:00 [Note] [Entrypoint]: MySQL init process done. Ready for start up.
`

mtw的配置如下：
`version: '3'

services:
  music-tag:
    image: xhongc/music_tag_web:latest
    container_name: music-tag-web
    ports:
      - "8002:8002"
    volumes:
      - /volume2/media/music:/app/media
      - /volume1/docker/mtw/config:/app/data
    environment:
      - PUID=1026
      - PGID=1000
      - MYSQL_HOST=10.0.0.6 # mysql 局域网ip地址（没有可以不填，默认使用 sqlite）
      - MYSQL_PASSWORD=123456 # mysql密码（没有可以不填，默认使用 sqlite）
      - MYSQL_DB_NAME=music_tag # 数据表名称（没有可以不填，默认使用 sqlite）
      - MYSQL_USER=root # mysql 用户名（默认使用 root）
      - MYSQL_PORT=3306 # mysql 端口（默认使用 3306）
      - WORKER_NUM=8 #  后台并发执行任务的worker数量
    restart: always
`

mysql的配置如下

version: '3'
services:
  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      PUID: 1026
      PGID: 1000
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: music_tag
    volumes:
      - /volume1/docker/mysql/data:/var/lib/mysql

**Comment by xhongc** [comment]
msyql 需要开放端口地址
