### ISSUE TITLE
文件路径有问题

### ISSUE THREAD

**Issue by alinihao** [xhongc/music-tag-web#249]
因为自动刮削整理文件夹时，无法识别语言，都会放到《未知》文件夹里，所以刮削好后我会手动整理，但容器还是以刮削后的文件路径为依据，实际文件已经不在了，找不到文件，所以我的小爱音箱无法播放音乐，web页面也无法播放音乐，在歌曲列表里点击某首歌的编辑，会显示“文件夹为空”

**Comment by xhongc** [comment]
确保语言 标签里有值

**Comment by alinihao** [comment]
> 确保语言 标签里有值

^. ^||||||||||||||||||||||||||||||||||||||||||
