### ISSUE TITLE
文件排序

### ISSUE THREAD

**Issue by WarlockFish** [xhongc/music-tag-web#25]
当文件或文件夹多的时候，需要排序功能，如时间，名称，大小
![图片](https://github.com/xhongc/music-tag-web/assets/30708115/75473ad2-6747-4ff5-a5b4-6bddc34debdb)

**Comment by xhongc** [comment]
yeah，新增排序功能 ，在镜像1.1.5

**Comment by xhongc** [comment]
hi，我创建一个交流群（二维码在 readme页面），感兴趣可以加入。群里会谈论项目新进展，和玩nas的交流，你有需要增加的功能可也沟通交流，期待你的加入！

ps. 不想被打扰，不加群也没关系，issue提的问题我也会回答。
