### ISSUE TITLE
无法登入，画面一闪而过。

### ISSUE THREAD

**Issue by aho206** [xhongc/music-tag-web#258]
我尝试在unraid以及群晖部署。 都是遇到 :8001 输入 admin/admin 无法登入情况。 输入之后，那个耳机画面会一闪而过，然后又回到登入页面。在输入，在闪，又回到登入页面。
换过浏览器也是一样。

**Comment by xhongc** [comment]
什么版本的

**Comment by aho206** [comment]
前天部署的，用的latest。
