### ISSUE TITLE
操作日志中的查看详情没有数据

### ISSUE THREAD

**Issue by huangkeyuan** [xhongc/music-tag-web#259]
操作日志中的查看详情没有数据
![WX20241012-101238](https://github.com/user-attachments/assets/480bfe83-2b88-4d1f-aa86-d9157e6f9117)

**Comment by xhongc** [comment]
请先告诉我你是 V1 还是 V2 版本，v1 是没有详情

**Comment by huangkeyuan** [comment]
是V1版本的
