### ISSUE TITLE
music_tag_web:1.1.4的mysql数据库结构怎么获取

### ISSUE THREAD

**Issue by shawn996** [xhongc/music-tag-web#26]
使用开发版库里面的local.yml部署的，但缺少数据库结构，这个怎么获取啊

**Comment by xhongc** [comment]
> 使用开发版库里面的local.yml部署的，但确实数据库结构，这个怎么获取啊

使用 ./compose/local/django/Dockerfile 文件来构建镜像

**Comment by xhongc** [comment]
开发版本 只需要构建 docker镜像即可，不需要其他组件

**Comment by shawn996** [comment]
哦，好的，我试试

**Comment by shawn996** [comment]
感谢，测试可以。把./compose/local/django/Dockerfile复制到项目的主目录，通过docker build编译后顺利运行。谢谢。
