### ISSUE TITLE
【Bug问题】: 下载歌词时只能显示原文，无中文翻译

### ISSUE THREAD

**Issue by blanketbathe** [xhongc/music-tag-web#260]
### docker镜像版本

latest

### MusicTagWeb 版本

V2

### bug 描述

在下载kaf的专辑《魔法》里各个单曲的歌词时，发现刮削的歌词皆为日文，而相应刮削源的歌词都有中文翻译

**Comment by xhongc** [comment]
不是 bug，目前没有这功能
