### ISSUE TITLE
【问题交流】: 音轨号和光碟号

### ISSUE THREAD

**Issue by mysteriousHerb** [xhongc/music-tag-web#262]
### docker镜像版本

最新

### MusicTagWeb 版本

V2

### 预期行为

1. 经常刮削的音乐是有音轨号，但是光碟号是有一些有有一些没有，在navidrome里面就很尴尬，因为会变成两张碟
2. 在gui里面没有显示音轨和光碟号，没法直观看到哪些有问题，而且没法选中多音乐一起改？

### 实际行为

1.
2.
3

### 原因分析(如果可以)

1.
2.
3

### 问题重现步骤

1.
2.
3

**Comment by xhongc** [comment]
有音轨和光碟号

**Comment by mysteriousHerb** [comment]
> 有音轨和光碟号

在哪里？？ 
![image](https://github.com/user-attachments/assets/83fe3a18-a031-4321-8076-2da28294047b)

而且这也不是全部问题的解决，你一个专辑十首歌一半有碟一半没有，就会变成两张碟。
没必要在解决问题之前就急匆匆关闭

**Comment by xhongc** [comment]
<img width="383" alt="image" src="https://github.com/user-attachments/assets/2ef8b0a8-499d-4071-a9a0-68d0708d5d2c">

**Comment by xhongc** [comment]
<img width="325" alt="image" src="https://github.com/user-attachments/assets/0a14fd10-9446-49fd-bbd0-2257d401df9d">
啥都没提供，还不能关闭 issue 吗

**Comment by xhongc** [comment]
<img width="1418" alt="image" src="https://github.com/user-attachments/assets/ef54c434-91fe-4197-9ccf-6ffb39be70bc">

**Comment by mysteriousHerb** [comment]
谢谢你的解答
