### ISSUE TITLE
加载Flac文件失败

### ISSUE THREAD

**Issue by Juusttiinn** [xhongc/music-tag-web#263]
在左侧选中flac音乐文件时弹出提醒：“加载文件失败, 请检查文件的元数据是否损坏:file said 1819568500 bytes, read 23719055 bytes“。虽然可以在右侧搜索数据和一键写入中间的信息框，但是无法保存。
这些加载失败的flac音乐文件都可以在各个平台正常播放，只是没有元数据显示。
如果只是元数据损坏或缺失，但是音频数据是完整的话，可以增加直接把元数据删除/覆写的功能吗？不然很难统一处理。谢谢～

**Comment by xhongc** [comment]
网盘音乐？发一首我看看

**Comment by Juusttiinn** [comment]
我又用工具测了一下发现元数据是能读出来的，但不知道为什么在music tag web会出现这个问题。。
filebin.net/qotdnsxcljbcmjug

**Comment by Juusttiinn** [comment]
> 网盘音乐？发一首我看看

找到bug了嘛作者大大，是音源的问题吗？

**Comment by xhongc** [comment]
确实是元数据损坏或不合法

**Comment by Juusttiinn** [comment]
这样的话不可以直接把整个元数据覆盖写入嘛，毕竟都损坏了。。

**Comment by Juusttiinn** [comment]
> 确实是元数据损坏或不合法

想问一下作者大大如果直接覆盖元数据区域写入这个功能具有可行性吗

**Comment by xhongc** [comment]
你不是第一个要求这个功能，我进行过尝试，技术能力有限，没能实现这个功能😂

**Comment by OcrSu** [comment]
> 你不是第一个要求这个功能，我进行过尝试，技术能力有限，没能实现这个功能😂

我有个类似的遭遇，

我下载的flac音乐文件无法写入元数据
经过我的排查，是因为下载这个音乐的工具以为下载的音源是flac版本的，但是实际上是320k的mp3版本。

由于下载工具是按照它程序设定的下载方式下载的，
即无论服务器给的是什么音源版本，用户只要选择了flac格式，就会自动保存为flac后缀。

因为文件后缀是flac，但实际上文件应该是mp3后缀，导致了无法正常写入元数据。

作者大大可以在文档里记录上这个问题，以免有人和我有相同的遭遇而不知道该怎么处理。

**Comment by baili168** [comment]
> 你不是第一个要求这个功能，我进行过尝试，技术能力有限，没能实现这个功能😂

我自己写了一个小工具：检测是否损坏（能否正常读取元数据） 如果损坏，将伪flac文件转换成mp3，再整理就没问题了。

**Comment by xhongc** [comment]
> > 你不是第一个要求这个功能，我进行过尝试，技术能力有限，没能实现这个功能😂
> 
> 我有个类似的遭遇，
> 
> 我下载的flac音乐文件无法写入元数据
> 经过我的排查，是因为下载这个音乐的工具以为下载的音源是flac版本的，但是实际上是320k的mp3版本。
> 
> 由于下载工具是按照它程序设定的下载方式下载的，
> 即无论服务器给的是什么音源版本，用户只要选择了flac格式，就会自动保存为flac后缀。
> 
> 因为文件后缀是flac，但实际上文件应该是mp3后缀，导致了无法正常写入元数据。
> 
> 作者大大可以在文档里记录上这个问题，以免有人和我有相同的遭遇而不知道该怎么处理。
> 
> 

感谢你的补充，现在才看到

**Comment by xhongc** [comment]
> > 你不是第一个要求这个功能，我进行过尝试，技术能力有限，没能实现这个功能😂
> 
> 我自己写了一个小工具：检测是否损坏（能否正常读取元数据） 如果损坏，将伪flac文件转换成mp3，再整理就没问题了。

怎么判断要转成 mp3 还是其他格式呢

**Comment by baili168** [comment]
> > > 你不是第一个要求这个功能，我进行过尝试，技术能力有限，没能实现这个功能😂
> > 
> > 
> > 我自己写了一个小工具：检测是否损坏（能否正常读取元数据） 如果损坏，将伪flac文件转换成mp3，再整理就没问题了。
> 
> 怎么判断要转成 mp3 还是其他格式呢

我觉得这个不需要过多的纠结，这种伪flac文件一般来说是很早的资源了。其次这种伪flac文件的体积比一般正常的flac文件都要小，如果需要增加这个功能，可以改成配置化，让用户在界面手工选就行。
我现在用Java写的小工具，大体功能：
1.检查目录下所有的文件是否能正常读取（musicTag已经有这部分逻辑）
2.不能读取的文件使用ffmpeg转成mp3 (当前我只发现有部分flac有这种问题)，同时将伪flac文件移动到损坏目录。
ps. 由于我是第一次使用musictag如果有什么说的不对，或者这部分已经有了勿怪。图片为我当前存在问题的flac文件对比

![Image](https://github.com/user-attachments/assets/583f7569-17e5-41b8-98a2-836d27400dd3)

建议：已经使用musicTag进行整理的用户，针对这部分文件，如果不懂代码会很头痛，建议新增损坏文件移动，移动到当前文件同级目录的已损坏目录，这样可以方便剔除这部分无法处理的文件。

当然这部分所有的功能改动，都交给用户自己决定是否需要启用就好哒。
还嫌弃就只能说已经尽力了

----------------------------2025年4月8日21:04:40-------------------------
刚思考了一番，已经对应的解决方案，当然是基于Java语言，我已经测试通过。大概流程如下：
1.检测文件是否存在元数据读取问题 
2.检测真实格式并修复
    2.1. 首先使用文件头检测 （获取到正确的文件格式，失败在采用2.2方式）
    2.2. 使用FFmpeg检测文件格式
    2.3.使用FFmpeg转换音频文件格式  （获取到正确的文件格式，将其转换）

如果你需要我可以提供我的Java代码

**Comment by xhongc** [comment]
感谢你生动表达，很需要你的 java 代码，能发我一首伪 flac 的音乐更好了，还有出现这种 flac 读取元数据一般是报什么错误呢，我的想法是遇到这种文件在操作记录详情给列出来，提供批量修复的操作（就是你提到的检测修复方式）
