### ISSUE TITLE
【功能请求】: 希望上架飞牛os应用中心

### ISSUE THREAD

**Issue by 2247ds** [xhongc/music-tag-web#264]
### 功能描述

1.希望可以上架飞牛os应用中心
2.
3

**Comment by xhongc** [comment]
怎么上架飞牛 os，没有看到官方有文档说明

**Comment by 2247ds** [comment]
https://trim-nas.feishu.cn/share/base/form/shrcn5m4MsyeqvEh6c4tm97pQKb

**Comment by xhongc** [comment]
哦，提交了，看命运了
