### ISSUE TITLE
您好，请问可以提供arm版本的docker镜像吗

### ISSUE THREAD

**Issue by 94kai** [xhongc/music-tag-web#266]
### 功能描述

我用树莓派作为音乐服务器，希望可以提供一个arm版本的镜像，感谢

**Comment by xhongc** [comment]
armv7吗，v8支持

**Comment by 94kai** [comment]
> armv7吗，v8支持

arm v8的 有如图warning  且浏览器访问web拒绝，另一台x86电脑没问题(抱歉电脑上不了github所以拍照)
![IMG_20241026_115140.jpg](https://github.com/user-attachments/assets/f6fd05ed-8ae5-4d69-8bd2-8c0fded0b345)

**Comment by 94kai** [comment]
难道是我这个镜像地址的img太老了？ 我的树莓派连不了外网😂

**Comment by xhongc** [comment]
阿里云镜像可能没有吧

**Comment by 94kai** [comment]
> 阿里云镜像可能没有吧

最新的是啥时候，我看我下载到的是12天前的
