### ISSUE TITLE
【Bug问题】: 如下图，点击右侧那个箭头总是触发底层标签缩放

### ISSUE THREAD

**Issue by sky9639** [xhongc/music-tag-web#267]
### docker镜像版本

laster

### MusicTagWeb 版本

V2

### bug 描述

我发现...
![image](https://github.com/user-attachments/assets/d680127b-5252-42dd-ba17-1379e125cf4b)
![image](https://github.com/user-attachments/assets/31b72296-8d2c-4b0a-9edb-2a99c8314355)

每次到这个页面，当左右两侧有侧边栏时，点击右侧那一排箭头，如果恰好是位于和底部页面标题栏缩放触发的位置，就会导致触发底部页面的收缩，而不是上层侧边栏的信息写入，感觉是页面遮罩没处理好的BUG，请作者看一下

**Comment by defpis** [comment]
我甚至没法保存，点击保存信息没有任何反应
