### ISSUE TITLE
【Bug问题】: 操作记录界面点击查看详情报403

### ISSUE THREAD

**Issue by dark-code** [xhongc/music-tag-web#268]
### docker镜像版本

lastest

### MusicTagWeb 版本

V1

### bug 描述

我发现操作记录界面点击查看详情报403
![screenshot-20241030-175631](https://github.com/user-attachments/assets/f4e68a4c-d093-471b-a69a-d470be7b73af)

**Comment by xhongc** [comment]
是的，v1 同步执行的，没有记录详情，所以是没有查看详情这个功能的
