### ISSUE TITLE
【问题交流】: 流派标签相关

### ISSUE THREAD

**Issue by everink404** [xhongc/music-tag-web#272]
### docker镜像版本

2.25

### MusicTagWeb 版本

V1

### 预期行为

1.能够自定义新流派
2.可通过后台对预设流派进行编辑
3

### 实际行为

1.选择被限制到预设的几种
2.能够编辑，但编辑内容无法应用到前端
3

### 原因分析(如果可以)

1.
2.
3

### 问题重现步骤

1.
2.
3

**Comment by xhongc** [comment]
风格是可以自定义编辑的， 需要按回车 确认 才会生效
