### ISSUE TITLE
【功能请求】: 变量值有没有可能增加一个年份变量 ${year} 类似这样

### ISSUE THREAD

**Issue by oliver556** [xhongc/music-tag-web#274]
### 功能描述

1. 早年爬虫下来的专辑格式大多是按找：【周杰伦/2000《Jay》 /周杰伦 - 可爱女人.flac】 这个格式进行保存的。后来新增的一些专辑也希望能保留该格式整理继续保留，不过现在能下到的大多是：【周杰伦/Jay/周杰伦 - 可爱女人.flac】。
2. 咱容器可以整理文件夹歌曲信息，也提供了便捷的变量，本来想着第一层为专辑艺术家，第二层为 年份《专辑名》，重新整理下，发现咱没有年份的变量可以使用，专辑量有点大，手动整理也是件头疼的事，希望作者可以采纳
3. 我觉得可以在已经存在有年份的一些内置标签后，整理可以使用年份变量，如若没有刮削到年份的，一般也会手动补充。如若没补充的，则放空即可。
4. 自定义变量的话，我觉得可以设计成这样 ${year}《${title}》，写着写着发现是不是可以用正则来对一些变量进行控制，有则填入，没有则使用 ${null} 这样的空字符串。

感谢作者到时候能耐心看完，如果表述有不清楚的，到时候我会尽力去配合解释好。Thanks♪(･ω･)ﾉ

**Comment by xhongc** [comment]
看了半天，🤦‍♂️ 本来就有$｛year｝变量，现在就是没值是空字符

**Comment by oliver556** [comment]
感谢感谢，我是看[变量文档](https://xiers-organization.gitbook.io/music-tag-web-v2/ming-ci-jie-shi#bian-liang)里头的描述没有看到年的变量，生怕表达得不清楚，于是从头说了一遍，这个issue可以关了哈
