### ISSUE TITLE
【Bug问题】: 操作台中“专辑”文件夹排序混乱

### ISSUE THREAD

**Issue by vipnetant** [xhongc/music-tag-web#275]
### docker镜像版本

2.2.6

### MusicTagWeb 版本

V2

### bug 描述

我发现在歌手文件夹下，专辑排序混乱。
我是“年份 专辑名”，按道理应该是按年份顺序顺延，但实际上是乱序。

![LDXHBC 59X2(8 GETE 0 {X](https://github.com/user-attachments/assets/22181bba-3a9b-439d-b04e-7604516ae6ae)
![图片](https://github.com/user-attachments/assets/d4d98413-50df-4011-b144-efdf9df7b90f)
![图片](https://github.com/user-attachments/assets/c1881529-8971-4566-bdb8-0f8f76afe418)

**Comment by xhongc** [comment]
可以排序
