### ISSUE TITLE
【功能请求】: 建议${filename}只包含文件名，和后缀名分开

### ISSUE THREAD

**Issue by vipnetant** [xhongc/music-tag-web#276]
### 功能描述

有些音乐tag乱码或信息不全，需要用${filename}替换title，结果后缀也一起添加到title了。
建议${filename}只包含文件名，和后缀名分开，或者给后缀名一个单独的变量。

![8 U0V$8YA7BS QK(3D(DRG](https://github.com/user-attachments/assets/33c77f4c-f0dc-4129-96d8-147910f8aa43)

**Comment by xhongc** [comment]
👌
