### ISSUE TITLE
【功能请求】: 能否在设置里列出已经被添加到音乐收藏的路径，手动批量修改疑问（已入Vip）

### ISSUE THREAD

**Issue by oliver556** [xhongc/music-tag-web#277]
### 功能描述

1. 目前映射的路径为最外层的父路径，二级路径下有多个文件夹，musici 为整理后的，还有同级的 待整理文件夹。选择待整理文件夹中的专辑进行自动刮削，还未移动到 music 中去，也会出现在音乐收藏当中，个人感觉较为混乱。也会直接将刮削出来，但是在刮削出来实际不对的情况下，识别出了艺术家在音乐收藏中。重新手动修改完后，对于错误的艺术家，还需要再手动删除不存在的音乐收藏。
2. 在全选刮削后的歌曲，选择手动编辑的时候，经常会出现左侧的弹出窗显示的可修改内容丢失一部分，有时候又能全部显示，不知道是不是在特定的情况下才会显示全。
![iShot_2024-11-12_18 33 25](https://github.com/user-attachments/assets/6437abd5-09eb-41b7-a236-68a3f0c257f5)
大多数时候在导出图片下面是还有可以选择手动批量修改专辑类型，音轨等等那些的，最近确实经常不知道为啥就显示不出来了。

**Comment by oliver556** [comment]
没改过任何设置，过了段时间来看，手动批量修改又出现了最下面的可编辑内容了
![iShot_2024-11-12_22 04 33](https://github.com/user-attachments/assets/9473e9c0-7bcc-4608-92ec-b635207feed1)

**Comment by xhongc** [comment]
第一点，在系统设置，取消勾选本地音乐写入音乐收藏，就不出现刮削，编辑会进入音乐收藏的情况了

**Comment by oliver556** [comment]
第一点明白了，第二点的情况，我看了下前端的页面代码，项目是 vue 跟 react 一起写的，大概率盲猜测是在循环的时候，对于 DOM 的 index 出现了不是唯一值导致，DOM节点直接不生成了。不知道这个部分的代码大佬是放在v1还是v2中的，我试试看代码拉下来，能不能找到是为啥
![iShot_2024-11-12_22 41 41](https://github.com/user-attachments/assets/b8b89096-ec91-4e4f-a52f-febe3df13d67)

**Comment by oliver556** [comment]
看到了代码中的几个循环大佬是直接 for 的 index 作为 key，建议不要用 key，因为它很容易不稳定，最好是个唯一值，拼接，递增销毁、递减销毁等等，拼凑进去，也会减少性能的开销。

【来自GPT解释】：在 Vue 的虚拟DOM算法中，key的作用是唯一标识每个节点，以便在更新过程中进行高效的重用和重新排序。 使用索引作为key值可能会导致一些问题。 不稳定的排序： 使用索引作为key值会导致节点的顺序在重新渲染时不稳定。

希望作者有空可以排查看看，前端部分如果我能帮上忙的话那就太好了（小菜鸟勿喷）

**Comment by xhongc** [comment]
发现问题了，
<img width="1076" alt="image" src="https://github.com/user-attachments/assets/64a0f63c-fa75-4372-9bb1-866385420a45">
在上图配置重新保存一下，然后刷新页面就会出现， 原因：抽屉组件那里也是读取的这里的配置，然而这里默认是全部，保存一下写入 local store ，那边就同步了
