### ISSUE TITLE
【Bug问题】: 关于酷我音乐的歌词的时间戳问题

### ISSUE THREAD

**Issue by dazzy2003** [xhongc/music-tag-web#279]
### docker镜像版本

2.2.6

### MusicTagWeb 版本

V1

### bug 描述

酷我音乐的歌词的时间格式和其他平台的歌词时间格式不一样，导致歌词滚动出现问题。能否修改一下酷我音乐的歌词时间格式，感谢。

**Comment by xhongc** [comment]
能举一个例子吗，酷狗什么格式，正确是什么格式

**Comment by dazzy2003** [comment]
> 能举一个例子吗，酷狗什么格式，正确是什么格式

其他平台的歌词时间格式为[00:00.00]，酷我音乐的歌词时间格式是[0:00:00]，就是后面的这种格式会导致有些应用歌词滚动出现问题

**Comment by xhongc** [comment]
> > 能举一个例子吗，酷狗什么格式，正确是什么格式
> 
> 其他平台的歌词时间格式为[00:00.00]，酷我音乐的歌词时间格式是[0:00:00]，就是后面的这种格式会导致有些应用歌词滚动出现问题


单个出问题的情况，可以在操作台进行格式化
哪个平台不支持酷哥时间戳格式呀

**Comment by dazzy2003** [comment]
> > > 能举一个例子吗，酷狗什么格式，正确是什么格式
> > 
> > 
> > 其他平台的歌词时间格式为[00:00.00]，酷我音乐的歌词时间格式是[0:00:00]，就是后面的这种格式会导致有些应用歌词滚动出现问题
> 
> 单个出问题的情况，可以在操作台进行格式化 哪个平台不支持酷哥时间戳格式呀

不是酷狗是酷我，酷我的歌词我点格式化没有反应
