### ISSUE TITLE
大佬你好，能否开放一个自己加 tag的自定义字段

### ISSUE THREAD

**Issue by cnlaok** [xhongc/music-tag-web#28]
你好：
       我是用plex用户，plex在艺术家页面会按普通专辑，ep，live 等分类。但普通tag并无专辑分类字段，而plex 是读取Muiscbrainz的分类，如果Muiscbrainz没有专辑分类则无效，需要自己在Muiscbrainz提交分组，十分不便，或者自己修改文件tag【加字段】来分组。
相应软件是可以设置，不过我的音乐均存在服务器本地修改会非常慢。如果music tag web 能有这个功能就好了。
当然如果可以直接有一个字段（plex里用RELEASETYPE【FLAC】，MusicBrainz Album Type【MP3】），
而plex 该字段有5个识别类型album;compilation【合辑】，album;live【现场】，ep【单曲或ep】，album;soundtrack【原声】，以及无该字段则为普通专辑，在批量修改文件时能选择专辑类型是否可以实现？不修改则为普通专辑。

**Comment by xhongc** [comment]
你可以发我一个 己修改文件tag【加字段】来分组 的音乐文件给我看一下，

**Comment by cnlaok** [comment]
![Snipaste_2023-08-08_13-40-56](https://github.com/xhongc/music-tag-web/assets/43554749/e9214fb5-f0db-4728-bd16-da5182377787)


以上为音乐文件的标签设置及音乐文件。
[莫文蔚、吕俊哲 - 那么爱你为什么 (Live).zip](https://github.com/xhongc/music-tag-web/files/12287723/-.Live.zip)

**Comment by cnlaok** [comment]
我已经运行了一些测试，您可以将哪些内容放入发布类型嵌入标记中：

album;compilation    “合辑”
album;soundtrack     “原声带”
album;remix              “混音”
album;live                  “现场专辑”
album;demo              “演示”
single                       “单曲和 EP”
ep                            “单曲和 EP”
album;album            “普通专辑”

就确切的帧名称而言：
FLAC/Vorbis：RELEASETYPE
id3v2：（TXXX:MusicBrainz Album Type

**Comment by cnlaok** [comment]
已上传文件。

**Comment by xhongc** [comment]
更新在1.1.7
