### ISSUE TITLE
【功能请求】: 增加按文件夹添加歌单的功能

### ISSUE THREAD

**Issue by michaelggr** [xhongc/music-tag-web#280]
### 功能描述

1.目前很多歌是按歌单分好文件夹的，手动创建比较麻烦，智能歌单里可以设置一个文件夹路径功能，此文件夹下音乐创建为动态歌单。比如轻音乐歌单，会经常往里面放歌
![image](https://github.com/user-attachments/assets/0add2bc2-82f4-439b-9076-c4232b473574)

2.或者自动扫描m3u，m3u8等歌单文件，自动创建播放列表。这种方式就需要用第三方软件手动挨个生成歌单文件。有的资源是自带歌单文件的
![image](https://github.com/user-attachments/assets/d8669ed3-8956-4b40-9c49-c97d13c61159)

**Comment by xhongc** [comment]
第一点我考虑该怎么实现
