### ISSUE TITLE
【问题交流】: 对于多个音乐的艺术家不同但却属于同一专辑的情况讨论

### ISSUE THREAD

**Issue by LightYear512** [xhongc/music-tag-web#284]
### docker镜像版本

2.2.7

### MusicTagWeb 版本

V2

### 预期行为

1. 一个影视原声带在刮削时设置了同一个专辑, 同时在音乐收藏中也显示为一个专辑
2. 专辑艺术家可以自定义

### 实际行为

1. 当我设置专辑艺术家为空时, 在音乐收藏中出现了多个同名的专辑, 显示发行者为艺术家

### 原因分析(如果可以)

原因： 怀疑是因为目前专辑艺术家无法自定义, 且当没有专辑艺术家时, 默认将艺术家作为专辑艺术家使用, 导致形如影视原声带这样的, 各个音乐的艺术家不同但却属于同一专辑的, 无法在音乐收藏中显示为同一个专辑

解决方案: 是否可以考虑专辑艺术家支持自定义，或者有其他更好的元数据设置方案

### 问题重现步骤

添加《在暴雪时分 电视剧影视原声带》中任意2~3首艺术家不同的歌曲会出现如下的情况
![image](https://github.com/user-attachments/assets/f2ce89c0-71eb-4617-8b9b-a66734e01c02)

**Comment by xhongc** [comment]
首先你问题描述很详细，是一个好的 issue 模板样例。

**Comment by xhongc** [comment]
首先你问题描述很详细，是一个好的 issue 模板样例。
原因如你分析的一致，在不存在专辑艺术家时，会取艺术家的第一个歌手入库保存
<img width="468" alt="image" src="https://github.com/user-attachments/assets/085516b0-0889-4058-ac04-e887dc7a007b">
自动刮削，手动刮削都是支持修改专辑艺术家的

**Comment by LightYear512** [comment]
很高兴得到您的回复, 确实可以通过手动刮削来自定义专辑艺术家, 十分感谢
