### ISSUE TITLE
【Bug问题】: 替换文本功能在风格上失效

### ISSUE THREAD

**Issue by VoidX0** [xhongc/music-tag-web#286]
### docker镜像版本

2.2.7

### MusicTagWeb 版本

V2

## 文本替换功能在替换风格时失效
- 所有选中歌曲（不管是否匹配的），都会被替换为${genre}
- 全文替换与正则替换都会出现该问题

## 截图
![image](https://github.com/user-attachments/assets/13b7a15d-ffbf-470b-bd07-3ccfd9a178ad)
![image](https://github.com/user-attachments/assets/b13aaac7-1ca6-4cbf-9fdc-427a80730306)
![image](https://github.com/user-attachments/assets/a8caa165-20bd-4462-8f99-a2fb93a6abf8)

**Comment by xhongc** [comment]
下个版本将修复

**Comment by VoidX0** [comment]
2.3.0 问题已修复
