### ISSUE TITLE
建议搜索的时候同时搜索歌名和艺术家

### ISSUE THREAD

**Issue by shawn996** [xhongc/music-tag-web#29]
由于现在翻唱的太多，建议搜索同时对歌名和艺术家进行搜索，这样出来的信息更准确。今天使用批量修改的功能，发现很多歌曲因为翻唱在前，填充的信息是错误的。

**Comment by xhongc** [comment]
现在搜索根据文件名搜索，做不到读取音乐中的艺术家再搜索，这样会比较慢

**Comment by xhongc** [comment]
你可以进行整理文件，按艺术家专辑分类，就能发现这个问题。是吧

**Comment by shawn996** [comment]
我现在遇到的问题是这样：有几千首歌曲，想批量进行tags信息的完善。使用批量修改功能后，发现很多歌曲被填充了错误的艺术家，特别是热门的网络歌曲，更是重灾区。好在文件名是艺术家-歌曲名的格式，只好一首首歌曲查看信息并进行比对，从而找出错误的进行修改。
在修改了几百首歌曲后，觉得这个“批量修改”功能不可靠，因为会填充错误信息。如果搜索是根据艺术家、歌曲名来搜索，准确率至少翻倍，但同样存在很多不正确的，为了准确性，人工识别后进行修改是最好的办法。所以建议提供快捷键的设置，比如通过方向键可以切换选中的歌曲，快捷键的保存、搜索等设置，以加快人工编辑的速度。
至于批量修改功能，鉴于目前的匹配度，最好是可以对修改前和修改后信息进行对比，人工选择那些主要信息没问题的进行批量修改。

**Comment by xhongc** [comment]
你使用的是严格模式吗，严格模式是根据 歌曲名 和 艺术家进行限制的

**Comment by shawn996** [comment]
是严格模式，我也认为会按照比较严格的规则进行处理。试了几百首最近2-3年的歌曲，结果就是人工对比了一下午。

**Comment by xhongc** [comment]
错误的情况是歌曲名一致，艺术家不对吗

**Comment by shawn996** [comment]
是的。我的主要歌曲来源是qq和网易，匹配用的源是指纹、qq、网易。
