### ISSUE TITLE
An error occurred

### ISSUE THREAD

**Issue by xiasi0** [xhongc/music-tag-web#290]
### docker镜像版本

latest

### MusicTagWeb 版本

V1

### bug 描述

Sorry, the page you are looking for is currently unavailable.
Please try again later.

If you are the system administrator of this resource then you should check the error log for details.

Faithfully yours, nginx.
![image](https://github.com/user-attachments/assets/2dff73bf-cd98-40e8-a495-a604556ea4fc)
![image](https://github.com/user-attachments/assets/cb9a3474-6377-4382-a3e1-3805cb2b68e2)

![image](https://github.com/user-attachments/assets/6d9837b3-b1a1-475b-827a-8e5cabbc529d)

![image](https://github.com/user-attachments/assets/5f9e78c5-ea76-4c9a-8777-d312459e0426)

**Comment by Lukchard007** [comment]
我也有同样问题，请问怎么解决。
