### ISSUE TITLE
【功能请求】: 音乐收藏中歌曲、专辑、艺术家等列表增加滚动条

### ISSUE THREAD

**Issue by Nothend** [xhongc/music-tag-web#291]
### 功能描述

1.音乐收藏中的歌曲较多时，有时候需要翻到最下面，没有滚动条很不方便。没有滚动条需要用鼠标滚轮翻好久。
2.音乐收藏中的艺术家较多时，有时候需要翻到最下面，没有滚动条很不方便。没有滚动条需要用鼠标滚轮翻好久。
3.音乐收藏中的专辑较多时，有时候需要翻到最下面，没有滚动条很不方便。没有滚动条需要用鼠标滚轮翻好久。

**Comment by xhongc** [comment]
我认为没有场景需要把列表滚动到最下面的情况

如果你想找到一首歌，善用搜索的更好方法

**Comment by Nothend** [comment]
> 我认为没有场景需要把列表滚动到最下面的情况
> 
> 如果你想找到一首歌，善用搜索的更好方法

主要是有时候想不起来歌名是什么了，只能通过添加时间来查找。搜索这个正常人都会啊

**Comment by xhongc** [comment]
歌曲是动态加载，不是一次性全部加载出来的。
不记得歌名拖到底部就能找到吗，
我觉得你的困惑是找到这首歌，而不是拖到底部

**Comment by Nothend** [comment]
> 歌曲是动态加载，不是一次性全部加载出来的。 不记得歌名拖到底部就能找到吗， 我觉得你的困惑是找到这首歌，而不是拖到底部

谢谢博主大佬回复。
1.找歌的问题：歌名不记得的前提下，只依稀记得添加的时间，所以通过时间排序后，需要滚动条先拉到大概位置，然后在仔细找。当然用鼠标滚轮也行，只是没那么方便。
2.昨晚一个列表：不管是歌曲列表、专辑列表、艺术家列表，诸如此类的列表信息，即便没有滚动条，弄一个分页也是可以的吧。说实话，还没遇到这么多信息的展示，只能通过鼠标滚轮进行滑动的。如果不能进行滚动查找，放置这样一个信息列表有何意义？

以上个人看法，谢谢博主！
