### ISSUE TITLE
【Bug问题】: Nginx Traefik 修改密码报错 CSRF

### ISSUE THREAD

**Issue by LeeVinBin** [xhongc/music-tag-web#294]
### docker镜像版本

latest

### MusicTagWeb 版本

V2

### bug 描述

建议修改 `django_vue_cli/settings.py` 为：

```python
CORS_ORIGIN_WHITELIST = os.getenv('CORS_ORIGIN_WHITELIST', 'http://127.0.0.1:8080').split(',')
```

用户可以通过  `docker-compose.yaml` 指定环境变量：

```yaml
    environment:
      - CORS_ORIGIN_WHITELIST=http://127.0.0.1:8080,https://domain,http://domain
```

**Comment by xhongc** [comment]
反代进入后台页面确实会有问题，出于框架的安全限制。
感谢你提供的方案，这个方案是否经过成功验证了。

**Comment by LeeVinBin** [comment]
不，我目前没有对应开发环境，正常应该是OK的，如果可能修复后，我可以协助进行 Nginx 或 Traefik 反代测试、验证。

**Comment by xhongc** [comment]
> 不，我目前没有对应开发环境，正常应该是OK的，如果可能修复后，我可以协助进行 Nginx 或 Traefik 反代测试、验证。

我在 xhong/music_tag_web:beta 中增加这个功能，你有空可以测试一下哈，谢谢～

**Comment by LeeVinBin** [comment]
我细看了一下服务的启动逻辑，是通过 supervisord 来启动 Nginx 进行反代的，只需要修改 Nginx 配置如下所示，确保在 Nginx 配置中添加如下头信息转发设置，以便 Django 能够正确接收请求头信息即可。  

```nginx
        location / {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_pass http://127.0.0.1:8001;
            root   /app/templates;
            index  index.html;
        }
```

验证 Nginx、Traefik 反代修改密码成功，如下图所示：

<img width="1576" alt="iShot2024-12-03 19 25 05" src="https://github.com/user-attachments/assets/33de50d3-f6f0-4bcb-819c-6f6897e7bb96">

**Comment by xhongc** [comment]
你是修改环境变量没有效果，修改 nginx 配置是有效的吗

**Comment by LeeVinBin** [comment]
是的，修改环境变量不生效，修改 Nginx 配置后生效。
