### ISSUE TITLE
【问题交流】: V1激活V2失败

### ISSUE THREAD

**Issue by karlzrick** [xhongc/music-tag-web#295]
### docker镜像版本

latest

### MusicTagWeb 版本

V1

### 预期行为

1. 按照文档说明使用激活码在v1激活
2. 填入激活码点击激活
3. 正常激活v2版本

### 实际行为

1. 填入激活码激活
2. 请求一直挂起
3. 返回504错误
![image](https://github.com/user-attachments/assets/6f59a3ed-1da2-456b-87b4-804796d92851)

### 问题重现步骤

1. 重新拉镜像，docker部署使用host网络

**Comment by karlzrick** [comment]
使用bridge网络激活成功

**Comment by xhongc** [comment]
哦～
