### ISSUE TITLE
【Bug问题】: 点击修复乱码提示“创建失败”

### ISSUE THREAD

**Issue by Elgalas** [xhongc/music-tag-web#297]
### docker镜像版本

2.2.8

### MusicTagWeb 版本

V2

### bug 描述

Emby曲库中部分日语可以正常显示，部分日语显示为？？？
![image](https://github.com/user-attachments/assets/6823ef5e-26d0-47ca-9fb5-d32c296451bd)
![image](https://github.com/user-attachments/assets/42d66625-a18f-41a6-9c55-e3b1b362beda)
想到可能是编码问题，尝试使用乱码修复功能，发现music tag内显示是正常的，选中并点击修复后提示“创建失败”
![image](https://github.com/user-attachments/assets/a8106b9a-e6b6-4825-83e5-8e02d0db0f73)

**Comment by xhongc** [comment]
发一首文件给我测试看看吧
