### ISSUE TITLE
【功能请求】: docker镜像能支持一下arm v7吗

### ISSUE THREAD

**Issue by Hosiang1026** [xhongc/music-tag-web#299]
### 功能描述

1. 希望镜像支持一下arm v7

**Comment by xhongc** [comment]
docker pull xhongc/music_tag_web:armv7

**Comment by Hosiang1026** [comment]
<img width="1599" alt="屏幕截图 2024-12-23 100453" src="https://github.com/user-attachments/assets/59c6ee17-367a-44dc-bae0-e40bea8008ab" />
docker部署运行不起来
