### ISSUE TITLE
[Feat] 请增加歌词下载

### ISSUE THREAD

**Issue by LiXin-x** [xhongc/music-tag-web#3]
一键（批量）将歌词保存为 `<文件名>.lrc` 便于本地需要通过 lrc 匹配的软件进行识别

现在好像自动批量还没实现？是禁用状态。

最后，非常感谢你的项目，macOS 平台，华语音乐的刮削还得是你的项目好用！

**Comment by xhongc** [comment]
很高兴我的项目能帮到你，我会采纳你的建议。 ：）））

**Comment by xhongc** [comment]
hi，我创建一个交流群（二维码在 readme页面），感兴趣可以加入。群里会谈论项目新进展，和玩nas的交流，你有需要增加的功能可也沟通交流，期待你的加入！

ps. 不想被打扰，不加群也没关系，issue提的问题我也会回答。
