### ISSUE TITLE
反馈问题，mp3专辑类型无法保持，FLAC可以

### ISSUE THREAD

**Issue by cnlaok** [xhongc/music-tag-web#30]
感谢大佬.更新神速啊。

专辑类型测试了下，FLAC修改专辑类型可以修改，MP3修改后保存出错。
测试了不同的专辑里的mp3均不能保存，FLAC均可以。不知道哪里出了问题。

**Comment by xhongc** [comment]
确实存在mp3格式 保存出错，我修复一下

**Comment by xhongc** [comment]
因为我们有用过plex，你可以把打好专辑类型标签的mp3格式也发我一下。
（如果有其他格式的也可一并发我测试

**Comment by xhongc** [comment]
因为我没有用过plex，你可以把打好专辑类型标签的mp3格式也发我一下。
（如果有其他格式的也可一并发我测试

**Comment by cnlaok** [comment]
[01 爱情余味 MP3.zip](https://github.com/xhongc/music-tag-web/files/12297313/01.MP3.zip)
我上传一个mp3格式的，其他标签已经打好。
其他因为限制25mb无法上传，我测试了其他格式的均不行。

**Comment by cnlaok** [comment]
我测试了DSF，WAV。两种格式，也无法保存。
还有一个我之前发现的问题，部分wav格式，无法读取且会造成程序卡死（无法操作网页里内容），刷新后回复正常。
wav音乐文件在服务器播放及本地播放均正常。

**Comment by cnlaok** [comment]
https://nas.laok.pw:66/sharing/TgRk5d5Fc 分享我服务器的下载链接，为DSF格式
https://nas.laok.pw:66/sharing/QWXfp4baP 此链接为wav格式
其中wav格式文件在music tag web 中打开卡死。

**Comment by xhongc** [comment]
ok收到

**Comment by xhongc** [comment]
nas大佬！

**Comment by xhongc** [comment]
plex的识别规则 是 flac，ogg 格式的音频 识别RELEASETYPE字段为 专辑分类
其他格式音频识别 MUSICBRAINZALBUMTYPE为 专辑分类
对吗？

**Comment by cnlaok** [comment]
MUSICBRAINZALBUMTYPE，这个字段应该时只对mp3的【应该是支持id3v2标签的格式】，我在plex论坛看是这么理解的
![Snipaste_2023-08-09_09-55-02](https://github.com/xhongc/music-tag-web/assets/43554749/f2fb8e33-b2b2-4d77-ad0e-411a7f7c089b)

**Comment by cnlaok** [comment]
因为有大量音乐，我批量改的时候是不分mp3还是flac等格式，直接给所有音乐文件打2个字段。
RELEASETYPE：XXXXXX
MUSICBRAINZALBUMTYPE:XXXXXX
这样我就不区分音乐格式了，不过这样有点不完美。

**Comment by xhongc** [comment]
更新在1.1.8

**Comment by xhongc** [comment]
id3 格式 改为TXXX: MUSICBRAINZALBUMTYPE
flac 格式 RELEASETYPE
thank you for your sponsorship

**Comment by cnlaok** [comment]
问题解决万分感谢

**Comment by cnlaok** [comment]
喝杯咖啡提提神，辛苦大佬了。

**Comment by xhongc** [comment]
hi，我创建一个交流群（二维码在 readme页面），感兴趣可以加入。群里会谈论项目新进展，和玩nas的交流，你有需要增加的功能可也沟通交流，期待你的加入！

ps. 不想被打扰，不加群也没关系，issue提的问题我也会回答。
