### ISSUE TITLE
【Bug问题】: 正常部署后， 登录用户端失败，提示未鉴权， 但是管理端可以登录

### ISSUE THREAD

**Issue by tianting123** [xhongc/music-tag-web#301]
### docker镜像版本

latest

### MusicTagWeb 版本

V1

### bug 描述

故障现象如下：
![image](https://github.com/user-attachments/assets/fa0e0999-db94-45bf-9270-c7ec5857c0e5)
![image](https://github.com/user-attachments/assets/59ed0a1e-5859-4646-b0dd-32597804d7b0)
日志如下：
![image](https://github.com/user-attachments/assets/06084161-33d4-49d9-bf2a-0a8aa7c9df53)
部署配置如下：
![image](https://github.com/user-attachments/assets/61ca819b-cabe-4274-9b4e-e958dbc1c2b3)

**Comment by TMTBO** [comment]
你好, 请教一下, 你登陆的问题处理好了吗? 我这边更新完也遇到相同的问题了. 管理端也登陆不上.

**Comment by tianting123** [comment]
我在没有更新版本的情况下， 某一天回家打开自动就好了， 不清楚构成原因是什么，没法帮到你

Tobyo Tenma ***@***.***> 于2024年12月16日周一 18:15写道：

**Comment by TMTBO** [comment]
又更新了一次, 正常了, 可能是上一次更新有什么没更新完整

**Comment by xhongc** [comment]
okk, 我也很疑惑
