### ISSUE TITLE
【Bug问题】: 使用远程SMB映射的目录，操作台看不到歌曲

### ISSUE THREAD

**Issue by shinobiii163** [xhongc/music-tag-web#302]
### docker镜像版本

2.3.0

### MusicTagWeb 版本

V2

### bug 描述

docker版映射的是远程SMB目录，操作台可以看到目录，但是选择该目录不会显示歌曲。
本地目录就能看到歌曲。

SMB目录看不到歌曲：
![image](https://github.com/user-attachments/assets/8655ca76-1a1e-45ed-936b-95f90f3bf954)

本地目录可以看到：
![image](https://github.com/user-attachments/assets/752d7821-de89-44f4-a4bc-18f747ffe215)

**Comment by xhongc** [comment]
应该是 smb 没有读写权限
