### ISSUE TITLE
【功能请求】: 文件转移整理

### ISSUE THREAD

**Issue by junyuyuan** [xhongc/music-tag-web#303]
### 功能描述

1.识别下载文件夹中的音频文件（自动或手动）
2.硬链接到目标文件夹中，并按固定格式重命名
3.将刮削下来的媒体元数据保存在目标文件夹中

**Comment by junyuyuan** [comment]
应该是已有功能。

**Comment by junyuyuan** [comment]
发现只能配置下载目录，并无目标目录的设置，重新打开

**Comment by xhongc** [comment]
整理文件里可以配置目标目录和层级关系

**Comment by xhongc** [comment]
点整理文件 右侧会有弹窗填写

（切换转移文件再次点回来）

**Comment by junyuyuan** [comment]
我研究一下，先关闭issue了。
