### ISSUE TITLE
【问题交流】: exec /entrypoint.sh: exec format error

### ISSUE THREAD

**Issue by Jackie264** [xhongc/music-tag-web#304]
### docker镜像版本

latest（2024-12-16 01-49-24）

### MusicTagWeb 版本

V2

### 预期行为

1.
2.
3

### 实际行为

exec /entrypoint.sh: exec format error

### 原因分析(如果可以)

1.
2.
3

### 问题重现步骤

最近更新拉取了镜像更新后，运行就出错了，但之前一直是正常运行的。

**Comment by xhongc** [comment]
正在修复中

**Comment by sykeswzq** [comment]
我以为是我问题呢。。。坐等修复，辛苦了！

**Comment by banjunxiao** [comment]
我也以为是我的问题，感谢修复

**Comment by TC-Chaos** [comment]
> 正在修复中

大佬加油

**Comment by xhongc** [comment]
@all 修复好了，重新拉一下新版本

**Comment by sykeswzq** [comment]
好的 好的 我先去试试

**Comment by sykeswzq** [comment]
完美 能用了
