### ISSUE TITLE
【Bug问题】:  ffmpeg 格式转换失败 

### ISSUE THREAD

**Issue by yn36** [xhongc/music-tag-web#309]
### docker镜像版本

laster

### MusicTagWeb 版本

V1

### bug 描述

<img width="1910" alt="image" src="https://github.com/user-attachments/assets/c514c3ae-f3b1-4162-920e-8312cd6f5696" />

docker-compose 部署的

services:
  music-tag:
    image: xhongc/music_tag_web:latest
    container_name: music-tag-web
    ports:
      - "4534:8002"
    volumes:
      - /volume1/music:/app/media:rw
      - /opt/configs/music_tag_web:/app/data:rw
      - /usr/bin:/app/data/bin:ro    # ffmpeg 在此路径
    restart: always

**Comment by xhongc** [comment]
请查看文档，ffmpeg 不应该在此路径
