### ISSUE TITLE
之前自定义标签提供有误

### ISSUE THREAD

**Issue by cnlaok** [xhongc/music-tag-web#31]
![Snipaste_2023-08-09_13-46-33](https://github.com/xhongc/music-tag-web/assets/43554749/65c591c8-7d41-435c-a3c1-fb87473f6552)
是“MusicBrainz Album Type”【测试通过】，而非“MusicBrainzAlbumType”【测试无法生效】，单词之间有空格，之前表达有误，向大佬报告下这个情况。

**Comment by cnlaok** [comment]
发现一个问题，整理文件夹，没有专辑艺术家选项，导致XX专辑中某曲目有2位艺术家，然后整理文件夹的时候会生成一个2位艺术家名字的专辑XX以及艺术家XX两个文件，建议加一个专辑艺术家选项。

**Comment by xhongc** [comment]
get

**Comment by xhongc** [comment]
更新在1.1.8
