### ISSUE TITLE
【Bug问题】: 后台刮削整理文件无效，已自动刮削过的，会一直在download目录

### ISSUE THREAD

**Issue by ttyob** [xhongc/music-tag-web#310]
### docker镜像版本

lastet

### MusicTagWeb 版本

V2

### bug 描述

如题
![微信截图_20241220183911](https://github.com/user-attachments/assets/a25fe130-7bdc-4520-a81c-e57de5647f2e)
![微信截图_20241220183948](https://github.com/user-attachments/assets/a2a51d50-7f5c-47fc-8210-4165361494fd)

**Comment by everfeng** [comment]
同样的问题我也遇到了  后面我误打误撞又成功了
不知道是否是该因素影响
后台刮削设置里 我一开始全打上了勾  也是一直刮削但不移动文件，操作记录里每三分钟都会重新刮削所有，并无任何错误日志，data里的log文件夹看不到日志，docker容器日志也没有明显报错
后面我把手动刮削取消了 就可以了  下面是部分截图
![1](https://github.com/user-attachments/assets/66e0d9ae-69a7-416d-a249-af70f2ecdf43)
![2](https://github.com/user-attachments/assets/6c08625b-a0d0-42ab-9a6d-d2b466ac8fbd)
![3](https://github.com/user-attachments/assets/723f99a9-a06e-472d-b614-960d5f4084f1)

![Snipaste_2025-01-07_15-42-05](https://github.com/user-attachments/assets/e5454009-4288-4cf4-b2c3-abfb57bc0beb)
