### ISSUE TITLE
说一下几点问题

### ISSUE THREAD

**Issue by ljw98** [xhongc/music-tag-web#32]
首先不得不说docker部署很实用，体验也挺好的，不过还是遇到几点问题
1.不能修改和设置密码
2.部署创建以后会多出music文件夹（虽然可以删除不影响）
3.最好就是可以定时自动扫描音乐情况，可以自动匹配，而无需手动去选择再批量自动匹配
4.音乐分类更加倾向于按语言分类（国语，日语，英语）这样，自动整理好目录
5.上面提到的3，其实最好给一个专门目录，整理过的分类好，没整理的一个目录，这样就知道那些有没有整理了
6.显示信息可以切换为常规的列表这样比较好一次看里面信息，现在需要一个个点才能显示

**Comment by xhongc** [comment]
很高兴该项目能帮到你。你的反馈建议非常重要。
1:修改密码可以在项目后台处理 地址是/admin 使用默认账号密码登录后修改
2:后续优化掉
3:之前考虑过周期任务问题，需要引入 celery redis 组件支持，提升部署成本，后期会考虑
4:可以考虑新增一个语言字段，便于整理分类
6:指的是需要点击每个音乐才能看到详情吗？因为是读取音乐软件元数据，做成列表显示会较慢，目前是没扫描写入数据库

**Comment by jialin4567** [comment]
非常好的项目，对本地大量音乐来说简直福音，有个疑问歌词只能内嵌吗？我现在本地音乐管理是plex！但是无法识别内嵌歌词，只能外挂

**Comment by xhongc** [comment]
> 非常好的项目，对本地大量音乐来说简直福音，有个疑问歌词只能内嵌吗？我现在本地音乐管理是plex！但是无法识别内嵌歌词，只能外挂


保存歌词开关打开就可以

**Comment by xhongc** [comment]
hi，我创建一个交流群（二维码在 readme页面），感兴趣可以加入。群里会谈论项目新进展，和玩nas的交流，你有需要增加的功能可也沟通交流，期待你的加入！

ps. 不想被打扰，不加群也没关系，issue提的问题我也会回答。
