### ISSUE TITLE
修改文件名称报错

### ISSUE THREAD

**Issue by pubg-Eddie** [xhongc/music-tag-web#33]
![M)HGYF _DEAO1C9R~6{G6$5](https://github.com/xhongc/music-tag-web/assets/70614635/90177bf8-2490-4313-a6ae-cb76fedc05eb)
![_X((@K~BZIMS_DGW1B6JS`0](https://github.com/xhongc/music-tag-web/assets/70614635/11662b5b-093d-4c99-bea8-2a7a58c4bf2f)

**Comment by xhongc** [comment]
为什么你的排版都是错乱的

**Comment by pubg-Eddie** [comment]
> 为什么你的排版都是错乱的

不太清楚，我的就是音乐文件编码有问题所以准备在这里修改文件名

**Comment by xhongc** [comment]
而且你的标题是后缀名，文件名却不带，这明显是相反的。

**Comment by xhongc** [comment]
你的镜像版本是多少，如果最新版本也有问题，你可以上传你的 mp3 给我，我排查之下错误

**Comment by pubg-Eddie** [comment]
> 你的镜像版本是多少，如果最新版本也有问题，你可以上传你的 mp3 给我，我排查之下错误

最新的那一版，我更新了镜像

[背影 - 林宥嘉.zip](https://github.com/xhongc/music-tag-web/files/12329737/-.zip)

**Comment by pubg-Eddie** [comment]
![image](https://github.com/xhongc/music-tag-web/assets/70614635/e9e8cb20-6719-4885-a245-3ced6119765a)

**Comment by xhongc** [comment]
<img width="951" alt="image" src="https://github.com/xhongc/music-tag-web/assets/29135056/c5c19f0c-4157-40cb-8c3f-b207da14c43d">
你点的是这个按钮？

**Comment by xhongc** [comment]
我用你的文件可以正常修改，修改文件名后要刷新一下

**Comment by xhongc** [comment]
勾选的时候是 批量操作 ，你要操作单个文件的话 点选名称就可以进去 编辑页面修改

**Comment by xhongc** [comment]
你看我的部署的demo站 都不会有你这样的排版啊，真实奇怪

**Comment by pubg-Eddie** [comment]
> ![image](https://user-images.githubusercontent.com/70614635/260309886-e9e8cb20-6719-4885-a245-3ced6119765a.png)
是的

**Comment by pubg-Eddie** [comment]
> 勾选的时候是 批量操作 ，你要操作单个文件的话 点选名称就可以进去 编辑页面修改

我的点名称没有反应

**Comment by pubg-Eddie** [comment]
我试了一下，发现我点文件名称乱码的是没有没有反应的，无法进行单个修改，是否跟环境或者权限有关系呢？
我录了个操作视频，见压缩包
[meeting_01.zip](https://github.com/xhongc/music-tag-web/files/12334182/meeting_01.zip)

**Comment by xhongc** [comment]
感觉还是文件名称编码问题，你上面发我的mp3我测试是没问题

**Comment by pubg-Eddie** [comment]
> 感觉还是文件名称编码问题，你上面发我的mp3我测试是没问题

支持什么编码呢

**Comment by xhongc** [comment]
中文啊

**Comment by xhongc** [comment]
你试试1.2.1 ，我转换了文件名编码

**Comment by pubg-Eddie** [comment]
> 你试试1.2.1 ，我转换了文件名编码

好的

**Comment by pubg-Eddie** [comment]
我点击文件名称修改还是报错，我已经升级到最新版本了
![image](https://github.com/xhongc/music-tag-web/assets/70614635/1fca26b1-babc-45e4-a52a-1e4443ca2313)

**Comment by pubg-Eddie** [comment]
我的音乐文件在linux系统显示也有乱码，是否跟这个有关系呢？
![image](https://github.com/xhongc/music-tag-web/assets/70614635/70a2c533-dc66-4c77-aa0e-dc921d326e06)

**Comment by xhongc** [comment]
是的，music-tag 在读取音乐文件元数据时，找不到文件，可能名称乱码找不到

**Comment by xhongc** [comment]
你之前发的背影.mp3 你是能点开的吗

**Comment by pubg-Eddie** [comment]
> 你之前发的背影.mp3 你是能点开的吗

点不开

**Comment by pubg-Eddie** [comment]
> 是的，music-tag 在读取音乐文件元数据时，找不到文件，可能名称乱码找不到

我的linux系统里面是中文的，文件夹中文名称能正常显示，但是音乐文件名称不能正常显示

**Comment by xhongc** [comment]
<img width="941" alt="image" src="https://github.com/xhongc/music-tag-web/assets/29135056/e5a31a87-c089-4b9d-85e2-008efefb2f26">
我是能点开的啊

**Comment by xhongc** [comment]
> > 是的，music-tag 在读取音乐文件元数据时，找不到文件，可能名称乱码找不到
> 
> 我的linux系统里面是中文的，文件夹中文名称能正常显示，但是音乐文件名称不能正常显示

说明你的音乐文件不是中文，没错

**Comment by pubg-Eddie** [comment]
> > > 是的，music-tag 在读取音乐文件元数据时，找不到文件，可能名称乱码找不到
> > 
> > 
> > 我的linux系统里面是中文的，文件夹中文名称能正常显示，但是音乐文件名称不能正常显示
> 
> 说明你的音乐文件不是中文，没错

已解决，windows文件名称编码默认是GB2312，linux默认是UTF-8，通过convmv即可进行修改。
convmv安装方式：
Centos系统命令：yum -y install convmv
Debian系统命令：apt-get install convmv
格式:convmv -f 源编码 -t 新编码 [选项] 文件名/目录名
示例：convmv -f gb2312 -t UTF-8 --notest -r 目录

希望遇到这种问题的时候可以帮到大家

**Comment by xhongc** [comment]
hi，我创建一个交流群（二维码在 readme页面），感兴趣可以加入。群里会谈论项目新进展，和玩nas的交流，你有需要增加的功能可也沟通交流，期待你的加入！

ps. 不想被打扰，不加群也没关系，issue提的问题我也会回答。
