### ISSUE TITLE
多艺术家支持及id3v1编码问题

### ISSUE THREAD

**Issue by shawn996** [xhongc/music-tag-web#34]
![image](https://github.com/xhongc/music-tag-web/assets/3212828/cb4dd3ad-f833-41b7-992d-e99574bbe03b)
左侧为修改后文件，右侧为原文件。
1.不知何故，修改后id3v1的汉字全部为乱码。
2.很多歌曲是多艺术家的，建议增加多艺术家支持。

**Comment by shawn996** [comment]
![image](https://github.com/xhongc/music-tag-web/assets/3212828/91467a17-0a57-47fd-9725-784a71d9bce0)
id3v1倒是也没啥用，可否添加个选项，选择是否删除id3v1信息。

**Comment by xhongc** [comment]
多艺术家的 填写多个人名 逗号分割不能识别么
id3v1 我也不清楚是什么

**Comment by shawn996** [comment]
整理歌曲的时候发现，对于多艺术家，id3v1的是逗号分隔，id3v2.4是多个tpe(n)标识。目前软件生成的信息是id3v2.4的，同时导致了id3v1的中文乱码。

**Comment by xhongc** [comment]
我也不清楚怎么做

**Comment by shawn996** [comment]
save方法有个参数是v1=False
```
if remove_v1:
                    id3.save(filename, v1=False)
                else:
                    id3.save(filename)
```
id3v2.4之后才支持utf8，不知道现在是否都是utf8格式，如果是这样，那么所有v1版本的tags都会是乱码，可以考虑默认都删除v1版本。

**Comment by shawn996** [comment]
这里有个关于[多艺术家的讨论](https://community.mp3tag.de/t/tag-tracks-with-multiple-artists/13777)，大部分支持分号分割，不知道对于多艺术家的歌曲，接口是返回什么格式的？如果接口可以返回多艺术家，建议兼容下。

**Comment by xhongc** [comment]
好呀，我会进行修改

**Comment by shizuku723** [comment]
> ![image](https://user-images.githubusercontent.com/3212828/261469235-cb4dd3ad-f833-41b7-992d-e99574bbe03b.png) 左侧为修改后文件，右侧为原文件。 1.不知何故，修改后id3v1的汉字全部为乱码。 2.很多歌曲是多艺术家的，建议增加多艺术家支持。

想问一下这个是用什么软件查看的

**Comment by xhongc** [comment]
你这个有id3v1标签的文件上传给我吧

**Comment by shawn996** [comment]
> 

beyond compare，看音频只是附带的……

**Comment by shawn996** [comment]
> 你这个有id3v1标签的文件上传给我吧

已发qq邮箱

**Comment by xhongc** [comment]
你为什么要删掉id3v1的标签，按理说只要你用这个软件读取的时候才显示出来吧

**Comment by shawn996** [comment]
对这款软件来说，是因为会把id3v1的汉字改成乱码。既然是乱码，就不如直接删除了。有些mp3播放器会使用v1版本的显示乱码，最好的当然是保持v1的正确，删除是最简单的解决办法。

**Comment by xhongc** [comment]
因为没那么好删除，我需要花费更多的精力去开发不必要的功能，读取v1 版本mp3 已经是很老的，是时候被淘汰了

**Comment by shawn996** [comment]
id3.save(filename, v1=False) 这个办法不可行吗？根据使用的类库，是支持这样操作的。v2.4版本已经存在20多年了，相信很少有使用这么久的mp3设备了吧？所以v1并没有那么容易消失。
这个功能修改只是提议，花费太多精力确实不值得，毕竟造成乱码这种问题是引用的类库导致的。

**Comment by xhongc** [comment]
我是使用musit-tag库去修改，中间已经封装了一层
引用的类库不会去改动v1的元数据的，只会改v2.4的，只能说明你的音乐文件一开始就是乱码的吧

**Comment by shawn996** [comment]
俩截图都说明原来是正确的，只有修改后才变得乱码。

**Comment by xhongc** [comment]
好像是的

**Comment by xhongc** [comment]
你用的播放器能识别v2.4吗？能识别就不改了

**Comment by xhongc** [comment]
支持多为艺术家 ，版本在1.2.1

**Comment by shawn996** [comment]
> 我是使用musit-tag库去修改，中间已经封装了一层 引用的类库不会去改动v1的元数据的，只会改v2.4的，只能说明你的音乐文件一开始就是乱码的吧

没仔细研究代码，但看到是用的musit-tag，而且musit-tag的save直接使用的mutagen的save，而mutagen是支持id3.save(filename, v1=False)，这样去掉v1的。
参考链接：https://mutagen.readthedocs.io/en/latest/api/id3.html?highlight=save#mutagen.id3.ID3.save

**Comment by shawn996** [comment]
> 我是使用musit-tag库去修改，中间已经封装了一层 引用的类库不会去改动v1的元数据的，只会改v2.4的，只能说明你的音乐文件一开始就是乱码的吧

上面回复的链接也说明，默认是修改v1版本的，而且v2版本默认指定的是4.

**Comment by xhongc** [comment]
很抱歉，超出我想修改的范围了。不在计划中去修改~

**Comment by xhongc** [comment]
hi，我创建一个交流群（二维码在 readme页面），感兴趣可以加入。群里会谈论项目新进展，和玩nas的交流，你有需要增加的功能可也沟通交流，期待你的加入！

ps. 不想被打扰，不加群也没关系，issue提的问题我也会回答。
