### ISSUE TITLE
很多常见的歌都不能识别出来

### ISSUE THREAD

**Issue by hiseab** [xhongc/music-tag-web#35]
很多常见的歌都不能识别出来,是不是右边的信息列表没有展现完整啊?比如beyond的长城这首歌都没有
![QQ截图20230819172811](https://github.com/xhongc/music-tag-web/assets/8234973/ec4a68e9-fec5-441e-98cb-65b8c5eb9d53)

**Comment by xhongc** [comment]
设置里面换一个标签源，有的平台没有收录

**Comment by hiseab** [comment]
换了,源都换了了的

**Comment by xhongc** [comment]
被禁的歌曲是搜不到的，因为搜索范围是国内的音乐源

**Comment by xhongc** [comment]
hi，我创建一个交流群（二维码在 readme页面），感兴趣可以加入。群里会谈论项目新进展，和玩nas的交流，你有需要增加的功能可也沟通交流，期待你的加入！

ps. 不想被打扰，不加群也没关系，issue提的问题我也会回答。
