### ISSUE TITLE
[功能需求] 获取音乐平台提供的歌词译文

### ISSUE THREAD

**Issue by kasuha07** [xhongc/music-tag-web#36]
> 首先想要感谢开发者，我也是用 Navidrome 搭建的个人音乐服务，这款应用真的帮了我很多。

关于 #18 提到的歌词翻译问题的补充，希望开发者能够增加 获取音乐平台提供的歌词译文 的功能。例如在QQ音乐上 https://y.qq.com/n/ryqq/songDetail/000g0uA94RBYYa 这是一首日语歌，并且QQ音乐平台提供了歌词的译文(如下图)。
[[QQ音乐平台截图]](https://github.com/xhongc/music-tag-web/assets/95362537/54731263-fd6d-46e1-864d-0eaa2594af18)

希望开发者能支持这个功能，就像上图中这样一行原文一行译文。另外，有一个开源项目([jitwxs/163MusicLyrics](https://github.com/jitwxs/163MusicLyrics))实现了这个功能，并且实现了网易云音乐和QQ音乐的API，希望能给开发者提供参考。
![image](https://github.com/xhongc/music-tag-web/assets/95362537/6e56c777-5283-454c-9ef9-8dbc749a122a)

**Comment by xhongc** [comment]
开源项目([jitwxs/163MusicLyrics](https://github.com/jitwxs/163MusicLyrics)) 看了一下源码，好像也是使用翻译 歌词给出的，music-tag-web中翻译不可使用吗

**Comment by kasuha07** [comment]
很抱歉我之前的描述可能造成误解，如下图，开源项目([jitwxs/163MusicLyrics](https://github.com/jitwxs/163MusicLyrics)) 的设置中可以勾选歌词`原始译文`，这个翻译是由音乐平台提供的，而不是由翻译API机翻的。当勾选了这一项时，下图中左侧输出的歌词中会出现QQ音乐翻译著作权声明，也可以说明这一点。换句话说就是，这个译文是从QQ音乐爬取下来的。

另外，有一些歌曲可能音乐平台并没有提供译文，[jitwxs/163MusicLyrics](https://github.com/jitwxs/163MusicLyrics) 提供了翻译API的配置，让用户可以选择是否调用机翻，您看到的有可能是这部分的源码。

还有就是我看到了您的 支持歌词翻译的 commits，感谢您的辛勤付出，但是在我使用过程中并没有出现翻译，我不知道它是否是默认启用的，也没找到配置的选项，还想向您请教一下如何使用。

最后，音乐的歌词往往是精心编排的，在断句与用词方面可能与日常的说话方式和习惯有所区别，个人认为音乐歌词使用机翻可能不太妥当，只有在实在没办法时可能才会采取机翻，所以还是希望开发者能够支持`获取音乐平台提供的原始译文`的功能。

![](https://user-images.githubusercontent.com/95362537/262259314-6e56c777-5283-454c-9ef9-8dbc749a122a.png)

**Comment by xhongc** [comment]
ok，我了解了你的需求，我需要研究各平台是否有提供歌词译文
