### ISSUE TITLE
自动批量修改无效

### ISSUE THREAD

**Issue by qinfengge** [xhongc/music-tag-web#37]
使用自动批量修改没有保存信息
![image](https://github.com/xhongc/music-tag-web/assets/35164697/6caf3580-cc66-4faa-a672-4d865cfe6229)
日志也是正常的
![image](https://github.com/xhongc/music-tag-web/assets/35164697/32323518-8231-4485-81fa-48e81d992046)
请大佬解答下是我姿势不对还是需要什么参数吗？万分感激

**Comment by xhongc** [comment]
多选两个标签源，可能你的歌曲在网易云没有

**Comment by qinfengge** [comment]
这是从网易云导出的歌曲，理论上网易云是OK的。
即使改成全匹配，还是不行，甚至在匹配到酷我后会报错
![image](https://github.com/xhongc/music-tag-web/assets/35164697/2fd75869-a250-4042-84ff-f31d72374dfe)

**Comment by xhongc** [comment]
酷我 修改了加密算法，暂时不能用

**Comment by xhongc** [comment]
单个修改试试

**Comment by qinfengge** [comment]
依然不行，只显示创建成功，没有保存结果，但列表中文件名变为红色
![image](https://github.com/xhongc/music-tag-web/assets/35164697/93f69b9e-119d-421b-b5e6-3a09f791f815)

**Comment by xhongc** [comment]
我意思是 单个手动查看有没有结果 ，不是勾选的形式，点击歌曲名称手动改
<img width="1418" alt="image" src="https://github.com/xhongc/music-tag-web/assets/29135056/15c51510-11c2-4014-aba5-814cddf9bc60">

**Comment by qinfengge** [comment]
单个是可以的，手动选的话几百首歌太麻烦了😂

**Comment by xhongc** [comment]
是让你排查原因啦，可能是严格模式没匹配 艺术家和标题吗

**Comment by qinfengge** [comment]
我好像找到原因了，你批量时好像请求错API了
请求的是这个batch_auto_update_id3
![image](https://github.com/xhongc/music-tag-web/assets/35164697/6922306b-500d-4c0c-b004-585e5931fde5)
但是我看代码里面是batch_update_id3
![image](https://github.com/xhongc/music-tag-web/assets/35164697/32a03125-2cfb-4347-bdf2-806cd4e333d1)
然后我用apifox请求了一下下面的接口成功了
![image](https://github.com/xhongc/music-tag-web/assets/35164697/04ce8aaf-41f1-4041-8ebd-5d0acc2a91c0)

**Comment by xhongc** [comment]
no,
 batch_auto_upadate_id3 对应
<img width="529" alt="image" src="https://github.com/xhongc/music-tag-web/assets/29135056/8a64806e-ce0a-4908-bfe9-d7b7c32debf7">

自动批量和手动批量的差别

**Comment by qinfengge** [comment]
抱歉，我不太懂python🥹
我看到在自动任务中，会打印**开始匹配**并进到match_song方法
![image](https://github.com/xhongc/music-tag-web/assets/35164697/4c527348-6485-4e51-8d6f-c4295f7408ce)
在match_song中如果匹配成功会输出下面一行
![image](https://github.com/xhongc/music-tag-web/assets/35164697/e596ae37-a3f7-4d9a-82c4-de5fa7f2c5f6)
那根据现有的日志看就没有匹配成功
![image](https://github.com/xhongc/music-tag-web/assets/35164697/4c698a8b-e6d8-45c9-a712-c06ae1149ac6)
我没有看懂这个匹配的逻辑，因为即使在宽松模式下它依然失败了

**Comment by xhongc** [comment]
嗯，可能是没匹配上规则，你上传几个音乐文件给我

**Comment by qinfengge** [comment]
找到问题了。。。是标题的问题
![image](https://github.com/xhongc/music-tag-web/assets/35164697/aff01ad1-4bfb-418f-886e-730b79da87b1)
标题不能带歌手名
把歌手名去掉后宽松匹配就对上了
![image](https://github.com/xhongc/music-tag-web/assets/35164697/5cfd1579-0b94-4ed2-ad1c-eb7a8c006567)
能请大大在代码中优化一下吗🤗，另外我看到有翻译歌词的接口，但在web中怎么使用呢🤨

**Comment by qinfengge** [comment]
使用箭头单个匹配的话带歌手的标题是ok的，但是批量匹配就不行了

**Comment by xhongc** [comment]
翻译的话 在歌词右边有个箭头是翻译

**Comment by xhongc** [comment]
3q 4 u sponsor ，手机突然播报 社死现场

**Comment by xhongc** [comment]
![image](https://github.com/xhongc/music-tag-web/assets/29135056/14689df4-604f-48c6-a5ff-886355a4db07)
你的艺术家是空的，严格模式匹配不到

**Comment by qinfengge** [comment]
好的，因为是批量从网易云下载的，所以没有元信息。
希望大佬优化一下批量匹配中的标题问题，感激不尽😊

**Comment by qinfengge** [comment]
另外，如果能在批量匹配中使用翻译歌词那就再好不过了

**Comment by xhongc** [comment]
- version： 1.2.2 优化自动打标签匹配算法

**Comment by xhongc** [comment]
hi，我创建一个交流群（二维码在 readme页面），感兴趣可以加入。群里会谈论项目新进展，和玩nas的交流，你有需要增加的功能可也沟通交流，期待你的加入！

ps. 不想被打扰，不加群也没关系，issue提的问题我也会回答。
