### ISSUE TITLE
专辑缺失

### ISSUE THREAD

**Issue by itodouble** [xhongc/music-tag-web#39]
能搜索到 但是专辑对应不上
![图片](https://github.com/xhongc/music-tag-web/assets/13508120/735aed1a-e648-4a2b-8d73-7733595aa34e)
![图片](https://github.com/xhongc/music-tag-web/assets/13508120/8057886d-dd5a-46c4-8a29-5d0d974f6d65)

**Comment by xhongc** [comment]
不同的标签源中匹配的专辑 可能不同

**Comment by itodouble** [comment]
标签来源用的是QQ音乐
还有一个 可不可以在这里加个搜索
![image](https://github.com/xhongc/music-tag-web/assets/13508120/0cb8b296-1f49-410a-a036-7b51ce6f78bc)

**Comment by xhongc** [comment]
没看懂 是什么搜索，灵魂画图

**Comment by itodouble** [comment]
就是第一次搜索的时候把原本歌曲里面带的（中间部分）歌曲名、歌手和专辑给到右边的框框里面（右边部分）
如果没有想要的东西 自己改搜索的关键字

**Comment by xhongc** [comment]
懂你的意思了， 那我直接把 最符合的放在第一个，按符合情况排序，是不是也能满足且更方便一些

**Comment by xhongc** [comment]
按歌曲名找不到 ，一般是在这个平台没有的了，需要换标签源

**Comment by xhongc** [comment]
thank you for your sponsorship

**Comment by xhongc** [comment]
新增智能刮削的标签源，会把所有平台的标签整合在一起，然后根据匹配相似度 排序，这样应该是满足的
镜像版本 1.2.3
