### ISSUE TITLE
在刮削的时候指定了 专辑名称 还是会刮削到别的

### ISSUE THREAD

**Issue by hbmask** [xhongc/music-tag-web#40]
在刮削的时候指定了 专辑名称 还是会刮削到别的，
![image](https://github.com/xhongc/music-tag-web/assets/13974172/de99dcba-88f6-4aec-9aae-6404b29e106a)
如图 这样，在什么信息都没有的时候是否可以使用自动批量修改？
是需要先手动还是需要指定什么信息才可以批量刮削？
这个艺术家名称和专辑艺术家，到底是那个属性对应右边框里面的歌手。
![image](https://github.com/xhongc/music-tag-web/assets/13974172/956929eb-fa37-4f8d-991c-de9d1bd99d8e)
是要 把信息填写好在点自动批量修改吗？
文件名中的 ${title}-${album} 要怎么使用，能有个文档说明么？
![image](https://github.com/xhongc/music-tag-web/assets/13974172/33a078e6-9b5b-4bfc-b588-444c8ebd8b08)
就是这里说是歌手 但是 左边框里面的艺术家和 专辑艺术家到底取的哪一个值？
![image](https://github.com/xhongc/music-tag-web/assets/13974172/14fa9a4b-8f69-4fc7-81d3-541d031a6a90)

希望大佬能出一个使用教程。有点蒙.必须支持

**Comment by hbmask** [comment]
补充一下：希望增加日志功能，至少能知道哪里有问题。好调整。

**Comment by hbmask** [comment]
![image](https://github.com/xhongc/music-tag-web/assets/13974172/f6588dec-b726-420b-aec3-6c34089ae3fa)
还有 一种情况，可能在pt下载音乐包，上传者没有修改标签，导致 标题可能是顺序号的问题。
希望 能过滤掉顺序号，自动把 文件名称 写入到标题的选项。
。。。
但是我也不清楚这样如何能快速的批量自动。。。
在自动批量修改，哪些参数选项是必须填的呢？
标题中的支持批量修改要如何修改。

**Comment by xhongc** [comment]
Q：如图 这样，在什么信息都没有的时候是否可以使用自动批量修改？
是需要先手动还是需要指定什么信息才可以批量刮削？
A： 自动批量修改 不需要填写 表单里的内容，会根据音乐文件的元数据 进行刮削，所以你至少要有标题 信息。

**Comment by hbmask** [comment]
您的来信我已经收到，我会尽快回复你。

**Comment by xhongc** [comment]
Q：这个艺术家名称和专辑艺术家，到底是那个属性对应右边框里面的歌手。
A： 对应右边框的歌手。这里文本确实没统一，会有歧义

**Comment by xhongc** [comment]
Q: 文件名中的 ${title}-${album} 要怎么使用，能有个文档说明么？
A： 文档还在制作中 ，变量用于手动修改的时候 ，填写到输入框中就能改为变量的值

**Comment by xhongc** [comment]
> 补充一下：希望增加日志功能，至少能知道哪里有问题。好调整。

日志功能也在制作中...

**Comment by xhongc** [comment]
> ![image](https://user-images.githubusercontent.com/13974172/263230998-f6588dec-b726-420b-aec3-6c34089ae3fa.png) 还有 一种情况，可能在pt下载音乐包，上传者没有修改标签，导致 标题可能是顺序号的问题。 希望 能过滤掉顺序号，自动把 文件名称 写入到标题的选项。 。。。 但是我也不清楚这样如何能快速的批量自动。。。 在自动批量修改，哪些参数选项是必须填的呢？ 标题中的支持批量修改要如何修改。

这也是个问题，可能也有歌曲名称是 数字的情况，会误判成顺序号，
你这个问题的操作是，先用文件名变量 ${filename} 手动批量替换给 标题，然后进行刮削

**Comment by hbmask** [comment]
好的,我都看明白了,给这个回复效率点赞,空了弄个群呗

**Comment by hbmask** [comment]
![image](https://github.com/xhongc/music-tag-web/assets/13974172/e11bba26-7a3f-47cf-b819-39d4ae7ac697)
问:自动批量刮削,如果繁体字,是无法被匹配上的,只能手动一个一个匹配.

**Comment by xhongc** [comment]
- version： 1.2.4 支持繁体匹配，新增消息中心展示自动刮削不匹配的数据

**Comment by xhongc** [comment]
hi，我创建一个交流群（二维码在 readme页面），感兴趣可以加入。群里会谈论项目新进展，和玩nas的交流，你有需要增加的功能可也沟通交流，期待你的加入！

ps. 不想被打扰，不加群也没关系，issue提的问题我也会回答。
