### ISSUE TITLE
自动化任务功能

### ISSUE THREAD

**Issue by BruceSuen720** [xhongc/music-tag-web#41]
大佬您好，这个项目的功能正是刚需，这边有个小小的需求，就是可以增加自动话任务，例如监测目录内容变化，触发自动任务，自动进行整理任务。
大佬如果有交流群的话，可否申请加入

**Comment by xhongc** [comment]
这个功能比较复杂还在规划中
建群了通知大家，大家比较倾向什么群，qq 微信，还是电报？

**Comment by BruceSuen720** [comment]
微信群吧，QQ也可以，还有你贴的微信打赏码打赏不了，截图不能打赏的

**Comment by xhongc** [comment]
这样啊，难怪打赏的都是扫支付宝
