### ISSUE TITLE
移动端支持

### ISSUE THREAD

**Issue by wangxiaoerYah** [xhongc/music-tag-web#42]
希望添加移动端支持。使用现有的网页，比如demo在手机浏览器上打开时显示是正常的。
但是当点击输入框或者选择刮削源后，网页比例就会变形。

**Comment by xhongc** [comment]
为什么会有移动端的 操作。
也只能刮削 你服务器上的音乐文件啊

**Comment by wangxiaoerYah** [comment]
> 为什么会有移动端的操作。 也只能删你服务器上的音乐文件啊

恩嗯，是这样的，我使用了nextcloud，后端接了s3储存，然后navidrome挂载了s3储存。
因为手动找音乐很麻烦，我一般就是直接挂的bt，通过aria2下载好了自动上传，因为不确定什么时候会上传成功，所以我都是看navidrome检测到了新音乐，这时候也许身边没有电脑，就想随时打开您开发的刮削服务来随时随地的一键编辑音乐。

因为我很少在pc上听歌一般是使用navidrome api兼容的app，所以关注到音乐库有变更时更多时候是在手机上。

也因为您的软件的便利性，我很多时候其实不需要编辑太多信息，只需要从音乐网站的源上一键应用即可（这点很感谢）,所以我觉得如果页面便利于手机操作的话就很完美了。

另外我注意到您的docker镜像好像有个127.0.0.1：2080的代理端口，因为我没找到您的docker file文件，所以不确定容器内的这个接口是用什么配置的，支持环境变量吗？在1.2.5版本的容器上如果不设置一个代理好像无法进行搜索。

**Comment by xhongc** [comment]
dockerfile文件是 compose/local/django/Dockerfile
我并没有配置有2080的代理端口 啊

**Comment by xhongc** [comment]
- version： 1.2.6 简单适配H5端，支持手机端访问

**Comment by xhongc** [comment]
hi，我创建一个交流群（二维码在 readme页面），感兴趣可以加入。群里会谈论项目新进展，和玩nas的交流，你有需要增加的功能可也沟通交流，期待你的加入！

ps. 不想被打扰，不加群也没关系，issue提的问题我也会回答。
