### ISSUE TITLE
希望docker镜像增加latest标签

### ISSUE THREAD

**Issue by itodouble** [xhongc/music-tag-web#43]
nas里面不能直接更改版本
要使用新的版本需要手动重新创建一个新的 latest不需要

**Comment by xhongc** [comment]
好的，已经打包了一个 latest版，为最新版

**Comment by xhongc** [comment]
dockerhub 镜像

**Comment by itodouble** [comment]
thank you

**Comment by xhongc** [comment]
hi，我创建一个交流群（二维码在 readme页面），感兴趣可以加入。群里会谈论项目新进展，和玩nas的交流，你有需要增加的功能可也沟通交流，期待你的加入！

ps. 不想被打扰，不加群也没关系，issue提的问题我也会回答。
