### ISSUE TITLE
WMA文件无法匹配及批量自动匹配

### ISSUE THREAD

**Issue by sfcboy** [xhongc/music-tag-web#44]
1.WMA文件无法匹配，会提示ASF format not implemented
2.批量自动匹配是不是只能选择一个文件夹？同时选择多个文件夹或者文件夹中还有文件夹就不能批量
2.1测试了，似乎是一次性选择的音乐文件数量有限制，太多就不能批量匹配

**Comment by xhongc** [comment]
1:你可以上传报错的文件，让我排查是什么问题
2:支持多个文件夹，但有限制文件夹深度是 2 层，例如：文件夹下的文件夹下的文件夹不会被搜索到
2.1 可能是中间有一个音乐文件报错了导致，异常取消批量任务

**Comment by sfcboy** [comment]
每一个WMA都是这个提示，随便传一个
[周杰伦-彩虹.zip](https://github.com/xhongc/music-tag-web/files/12531527/-.zip)

**Comment by xhongc** [comment]
下载不了这个文件

**Comment by sfcboy** [comment]
你看看

**Comment by xhongc** [comment]
可以下了

**Comment by xhongc** [comment]
lastest 版本 修复这个问题。
但是找不到wma 文件修改 专辑封面的方案，
目前 wma 不能修改专辑封面

**Comment by sfcboy** [comment]
WMA解决了。自动匹配能不能加个碰到错误直接跳过

**Comment by sfcboy** [comment]
[群星－因为爱（韩）.zip](https://github.com/xhongc/music-tag-web/files/12537395/default.zip)
这个MP3提示can't sync to MPEG frame

**Comment by xhongc** [comment]
ok，已修复在 latest 版本

**Comment by xhongc** [comment]
hi，我创建一个交流群（二维码在 readme页面），感兴趣可以加入。群里会谈论项目新进展，和玩nas的交流，你有需要增加的功能可也沟通交流，期待你的加入！

ps. 不想被打扰，不加群也没关系，issue提的问题我也会回答。
