### ISSUE TITLE
flac格式歌曲有时候会无法保存结果

### ISSUE THREAD

**Issue by windmakeppcool** [xhongc/music-tag-web#45]
手动修改flac歌曲信息的时候，经常会出现修改失败的情况

**Comment by xhongc** [comment]
例如

**Comment by windmakeppcool** [comment]
![1694078971851](https://github.com/xhongc/music-tag-web/assets/53427316/4d18e86c-7dcc-4ecf-8dd0-13f41bcc1451)
可以看下后台的报错信息，凡是出现ivalid的，都是没法保存的

**Comment by windmakeppcool** [comment]
如果有需要我可以提供一个flac文件供大佬debug一下，或者有没有群之类的

**Comment by windmakeppcool** [comment]
![1694079497312](https://github.com/xhongc/music-tag-web/assets/53427316/522a2ca2-3049-4550-ae78-15a481e7f215)
这边提供一个手动保存报错的后台输出，详细的，会不会和python版本有关系

**Comment by xhongc** [comment]
因为 音轨号或光盘号需要是 数字，你的是 1/1这种是 不行的，
明天我优化一下， 你先手动修改掉试试

**Comment by xhongc** [comment]
目前还没有 群，你可以先加我为微信，就足够3人建群了

**Comment by xhongc** [comment]
已经修复在 latest版本
