### ISSUE TITLE
左侧文件浏览模块希望能追加一个滚动条功能

### ISSUE THREAD

**Issue by tywg001** [xhongc/music-tag-web#52]
请求左侧追加滚动条
![image](https://github.com/xhongc/music-tag-web/assets/1572723/08b6ae74-4d76-457a-9c0c-a4ea7ad4a6f9)
歌曲太多的时候用鼠标滚轮需要太多时间,希望能追加一个滚动条功能

**Comment by xhongc** [comment]
可以滚动，只是没显示滚动条而已，可以使用滚轮滚动

**Comment by xhongc** [comment]
后续我把 红色的可以排序在顶部就可以了
