### ISSUE TITLE
[求助]群晖新的Docker容器配置完无法进入界面

### ISSUE THREAD

**Issue by ZijieFeng** [xhongc/music-tag-web#56]
1.在群晖的Container Manager里拉取了xhongc/music_tag_web 
2.创建了新的容器，网关选择host
3.输入 本地IP地址：8001/admin 无法连接，127.0.0.1:8001/admin也无法连接。
没找到在哪里运行：docker run -d -p 8001:8001 -v /path/to/your/music:/app/media --restart=always xhongc/music_tag_web:latest。

**Comment by xhongc** [comment]
我没用群晖不太清楚，可以问问群里的大佬们，
应该群晖有界面端可以操作吧。

**Comment by ZijieFeng** [comment]
感谢回复，请问咋进群呀？

**Comment by xhongc** [comment]
readme 里有微信群的邀请二维码
