### ISSUE TITLE
希望可以增加音轨号和碟号的属性，可以根据这两个变量进行重命名

### ISSUE THREAD

**Issue by CVBN7625** [xhongc/music-tag-web#58]
<img width="774" alt="image" src="https://github.com/xhongc/music-tag-web/assets/82645050/6b9ea2a1-9416-4c97-8512-4cffc51e5377">
plex对一张专辑里面不同CD的歌曲命名要包含碟号，如上图所示，大佬有时间希望支持一下

**Comment by xhongc** [comment]
有这两个变量啊

**Comment by CVBN7625** [comment]
我的疏忽，不好意思，不过音轨号和光盘编号好像不能用变量名的形式用于文件重命名，不知道是否能够添加

**Comment by xhongc** [comment]
这个也有，忘记提示出来了
音轨号 ： ${tracknumber}
光盘编号 ： ${discnumber}
