### ISSUE TITLE
可否考虑支持批量自动下载标签呢？

### ISSUE THREAD

**Issue by jinglingxiaoguin** [xhongc/music-tag-web#6]
项目非常不错，不过好像只能一个个修改，能否做成像[MusicTag v1.0.9.0](https://www.cnblogs.com/vinlxc/p/11347744.html)一样可以批量自动匹配标签并保存呢？

**Comment by xhongc** [comment]
> 项目非常不错，不过好像只能一个个修改，能否做成像[MusicTag v1.0.9.0](https://www.cnblogs.com/vinlxc/p/11347744.html)一样可以批量自动匹配标签并保存呢？

批量没办法保证准确率啊，你没办法认为哪个是正确的标签数据？

**Comment by WarlockFish** [comment]
请问批量下载不会匹配歌词吗，只能单独匹配时才有歌词

**Comment by xhongc** [comment]
> 请问批量下载不会匹配歌词吗，只能单独匹配时才有歌词

匹配的吧

**Comment by xhongc** [comment]
hi，我创建一个交流群（二维码在 readme页面），感兴趣可以加入。群里会谈论项目新进展，和玩nas的交流，你有需要增加的功能可也沟通交流，期待你的加入！

ps. 不想被打扰，不加群也没关系，issue提的问题我也会回答。
