### ISSUE TITLE
[功能需求]希望批量刮削时，可以自动保存歌词

### ISSUE THREAD

**Issue by wdmJieyao** [xhongc/music-tag-web#60]
![image](https://github.com/xhongc/music-tag-web/assets/47850366/5c07bb43-c77b-42a9-96aa-4d9373b85b68)

![image](https://github.com/xhongc/music-tag-web/assets/47850366/5f429376-75c9-46c3-804f-b662a4af5b59)

批量刮削时，发现不能自动保存歌词和专辑封面，恳请大大新增自动保存或批量保存的按钮，感谢~

**Comment by xhongc** [comment]
保存歌词文件吗
