### ISSUE TITLE
对Flac和mp3的支持不完善

### ISSUE THREAD

**Issue by RobberZQ** [xhongc/music-tag-web#61]
目录里的音乐是全的  但无法识别
![Snipaste_2023-09-27_10-54-53](https://github.com/xhongc/music-tag-web/assets/124328601/ec83f6fb-7517-43e4-ad3f-87002fd60522)
![Snipaste_2023-09-27_10-57-13](https://github.com/xhongc/music-tag-web/assets/124328601/d842417d-1ee7-4a77-9438-246fe6e66b11)

**Comment by xhongc** [comment]
什么版本

**Comment by RobberZQ** [comment]
在程序里没找到版本号的地方  是用群晖docker拉的latest

**Comment by xhongc** [comment]
你这不像是 latest 版本呢，是今天拉的么

**Comment by RobberZQ** [comment]
> 你这不像是 latest 版本呢，是今天拉的么
拉了还没超过3天   
![Snipaste_2023-09-27_16-47-57](https://github.com/xhongc/music-tag-web/assets/124328601/abcac743-1831-45f2-9539-31d6086d5cbf)

**Comment by RobberZQ** [comment]
> 你这不像是 latest 版本呢，是今天拉的么

看来是拉错库了   抱歉
