### ISSUE TITLE
希望增加Apple Music数据来源，自动读写音乐风格、光盘碟号、音轨号等标签

### ISSUE THREAD

**Issue by juneix** [xhongc/music-tag-web#63]
之前一直用另一个同名[音乐标签](https://www.cnblogs.com/vinlxc/p/11347744.html)，但它只有PC和安卓版，没有Mac版。偶然找到博主你这个web版很好的补足了这个空缺，简单体验了一下还不错，但数据来源和自动填充标签不够完美。

我使用plex/plexamp作为播放器，支持的音乐标签分类还蛮丰富的，但试了目前music-tag-web内置的网易云、QQ、指纹识别（MusicBrainz？）数据来源都无法识别并填充**专辑艺术家**、**光盘碟号**、**音轨号**、**（自定义）音乐风格**、**专辑类型**等。之前用同名软件的**Apple Music数据来源**，这些标签都是齐全的，而且Apple Music的专辑封面分辨率是最高的，基本1000x1000到3000x3000。

- 音乐类型（流派/风格）如果细分比较多，建议除了对接Apple Muisc数据来源，增加一个自定义选项，目前只能在常见的流行、摇滚等固定类型里选。
- 网易云和QQ音乐应该支持光盘碟号、音轨号标签，都没有读取出来。

**Comment by xhongc** [comment]
目前还不支持Apple Muisc数据来源
网易云和QQ音乐未找到光盘碟号、音轨号标签
