### ISSUE TITLE
不知是否可以刮削歌手头像？

### ISSUE THREAD

**Issue by JKnuts** [xhongc/music-tag-web#65]
进入歌手页面查看时，少数歌手有头像，大部分歌手没有头像，如下：

![image](https://github.com/xhongc/music-tag-web/assets/91355283/f8fcaee6-5c1e-4677-b2d2-aecf113529a7)
![image](https://github.com/xhongc/music-tag-web/assets/91355283/afb8dba1-06a9-4fb1-abf5-2bd0d3c7c6bd)

在网页上还好，没什么大影响，在手机端查看歌手就比较不舒服了：
![IMAGE 2023-10-03 12:01:23](https://github.com/xhongc/music-tag-web/assets/91355283/036a90b6-00d0-411d-9971-29caa232c2fa)

不知道大家能不能刮到歌手头像，我就反馈一下，也不是什么大问题，并不影响使用，只是想更美观点，有点强迫症。

感谢一下大佬的辛苦劳动。

**Comment by xhongc** [comment]
没有接口提供艺术家的头像，只能支持到手动上传头像
