### ISSUE TITLE
[bug] 搜索时要增加专辑才搜索得到

### ISSUE THREAD

**Issue by itodouble** [xhongc/music-tag-web#67]
搜索时 如果没有在标题上增加专辑的名字 搜索不到具体的

![image](https://github.com/xhongc/music-tag-web/assets/13508120/78ed0b86-6147-4641-a36f-62b5dbe19395)
![image](https://github.com/xhongc/music-tag-web/assets/13508120/3186822c-e60f-4d18-adc4-da1bfb3db7e5)

**Comment by xhongc** [comment]
这应该是这个音乐平台的搜索规则
