### ISSUE TITLE
[bug] 整理文件夹 提示创建失败

### ISSUE THREAD

**Issue by itodouble** [xhongc/music-tag-web#69]
![image](https://github.com/xhongc/music-tag-web/assets/13508120/90ffc55a-fd65-4e36-b6dc-cbc45c88f5e2)
```
{result: false, code: "50000", message: "系统异常,请联系管理员处理", data: null}
```
![image](https://github.com/xhongc/music-tag-web/assets/13508120/51cefbc5-74c4-4c61-b974-a9ca2eda4fb4)
![image](https://github.com/xhongc/music-tag-web/assets/13508120/7d8a8675-6e21-40c3-a0a7-9200c7687048)

**Comment by xhongc** [comment]
应该是掉线了，清除浏览器缓存试试
