### ISSUE TITLE
问一个和本项目无关的问题

### ISSUE THREAD

**Issue by SnowMeteors** [xhongc/music-tag-web#7]
https://github.com/xhongc/music-tag-web/blob/master/img_2.png
想问下，作者上面图片用的什么本地音乐播放器，很好看

**Comment by xhongc** [comment]
> https://github.com/xhongc/music-tag-web/blob/master/img_2.png 想问下，作者上面图片用的什么本地音乐播放器，很好看

navidrome

**Comment by xhongc** [comment]
hi，我创建一个交流群（二维码在 readme页面），感兴趣可以加入。群里会谈论项目新进展，和玩nas的交流，你有需要增加的功能可也沟通交流，期待你的加入！

ps. 不想被打扰，不加群也没关系，issue提的问题我也会回答。
