### ISSUE TITLE
【功能需求】歌曲标题显示在左侧树中，左侧树增加滑动条，歌曲播放

### ISSUE THREAD

**Issue by diaodeng** [xhongc/music-tag-web#72]
你好，能否增加下面的功能，感谢
1.歌曲标题显示在左侧树中
    应为有些歌曲文件名是正常的，但是歌曲原数据是乱码，这样放标找出信息乱码的歌曲来修改
2.左侧树增加滑动条
    左侧文件夹或者歌曲较多的时候只能鼠标滚轮滑动很难滑到顶部或者底部，也不方便滑动查找内容
3.歌曲播放
   选中歌曲后播放可以辨别歌曲信息，有的歌曲同名或者名字不对的仅靠歌曲信息无法分辨

**Comment by diaodeng** [comment]
基于作者的加了显示内容切换、搜索框固定、显示滚动条，播放音乐还没实现
https://github.com/diaodeng/music-tag-web/tree/dev_1.0_diaodeng
![image](https://github.com/xhongc/music-tag-web/assets/108243171/99066be7-894f-4faa-b73c-1a193429fe71)

**Comment by xhongc** [comment]
👍 每次都要从音乐文件里读取元数据，数据量多了会有些慢，所以我没有做这个功能

**Comment by diaodeng** [comment]
获取元数据确实会变慢很多，试着用协程似乎没什么效果，后面试着用多线程试试；
样式问题能帮忙优化下不，我增加的选择显示内容的那个样式有点丑。。。
在编辑页面使用audio标签增加了个播放功能，不容易区分的歌曲可以播放听听来判断。
![image](https://github.com/xhongc/music-tag-web/assets/108243171/61715240-52e9-4865-be57-43e0180dc9dc)

**Comment by xhongc** [comment]
是的，你做的很好
但是我在实现 v2 的版本了
<img width="1406" alt="image" src="https://github.com/xhongc/music-tag-web/assets/29135056/50ccc2b0-e348-41e3-bd27-f394591a25ad">

**Comment by diaodeng** [comment]
好期待
