### ISSUE TITLE
几个小建议

### ISSUE THREAD

**Issue by doudou0424** [xhongc/music-tag-web#75]
首先说明一下，非常棒的软件，体验很好。
其次有个小的建议：
- 自动修改的修改范围增加标题选项，我有好多歌名是繁体，我想替换成刮削出来的简体，目前好像只能手动。
- 修改文件名貌似没有效果。
最后感谢大佬的无私奉献，献上我的祝福以及star。

**Comment by xhongc** [comment]
- 采纳
- 批量修改文件名吗

**Comment by doudou0424** [comment]
第二点我没有说清楚，我补充一下
我使用手动批量修改，将文件名使用变量${tracknumber}. ${title}，然后点击手动修改，显示修改成功，但实际情况文件名没有更改

**Comment by xhongc** [comment]
已经修复了
