### ISSUE TITLE
繁体转换简体时乱码

### ISSUE THREAD

**Issue by xheia** [xhongc/music-tag-web#77]
自动繁体转换简体后乱码。PLEX读取转换后文件乱码了。

**Comment by xhongc** [comment]
很抱歉，我没有 plex 软件进行测试 你提的问题，
plex 乱码 应该是 id3v1 不支持 utf-8
 我改了一些代码，不知道能不能生效

**Comment by xheia** [comment]
感谢大佬，乱码问题已经解决。
