### ISSUE TITLE
docker部署项目后默认显示文件夹切换不方便

### ISSUE THREAD

**Issue by wesmile8** [xhongc/music-tag-web#78]
这是我docker内的目录
![image](https://github.com/xhongc/music-tag-web/assets/75376418/d173fcbd-25a8-4ad4-aea9-308eb95f7081)
这是网页端默认打开的目录
![image](https://github.com/xhongc/music-tag-web/assets/75376418/0cc392df-106c-49c4-b027-8219794685ab)
每次我需要刮削的时候都要手动把/Users/macbookair/Music/my_music/music/music_lyc改成/app/media,网页刷新一下也会变成默认的/Users/macbookair/Music/my_music/music/music_lyc目录，请问有什么办法修改默认刮削目录吗

**Comment by xhongc** [comment]
打错包了，这是我本地开发的目录，明天再次打包
