### ISSUE TITLE
Unraid平台下进行的Docker部署,进入主界面所有简繁转换和繁简转换不能选择,设置权限重新部署后依然无效.

### ISSUE THREAD

**Issue by 95121808** [xhongc/music-tag-web#79]
Unraid平台下进行的Docker部署,进入主界面简繁转换和繁简转换不能选择,设置权限重新部署后依然无效.

手动修改,自动修改在遇到单文件出错时不能跳过,会终止进程.

![image](https://github.com/xhongc/music-tag-web/assets/66406177/933e2e7b-a265-40e0-9f3d-2b8af3dfb025)

辛苦作者给予解答.

**Comment by 95121808** [comment]
我这次扫描19725首歌曲

**Comment by xhongc** [comment]
试试扫描少一些

**Comment by 95121808** [comment]
好吧,我已换说明中的阿里镜像,目前还在测试

&nbsp;


Docker-D
***@***.***







&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月7日(星期二) 中午1:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xhongc/music-tag-web] Unraid平台下进行的Docker部署,进入主界面所有简繁转换和繁简转换不能选择,设置权限重新部署后依然无效. (Issue #79)





 
试试扫描少一些

**Comment by xhongc** [comment]
no 阿里镜像
 yes dockerhub

**Comment by 95121808** [comment]
dockerhub link ?&nbsp; 链接是什么?



&nbsp;


Docker-D
***@***.***







&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月7日(星期二) 下午3:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xhongc/music-tag-web] Unraid平台下进行的Docker部署,进入主界面所有简繁转换和繁简转换不能选择,设置权限重新部署后依然无效. (Issue #79)





 
no 阿里镜像
 yes dockerhub

**Comment by xhongc** [comment]
docker pull xhongc/music_tag_web:latest

**Comment by 95121808** [comment]
我再重装试试

&nbsp;


Docker-D
***@***.***







&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月7日(星期二) 下午4:55
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xhongc/music-tag-web] Unraid平台下进行的Docker部署,进入主界面所有简繁转换和繁简转换不能选择,设置权限重新部署后依然无效. (Issue #79)





 
docker pull xhongc/music_tag_web:latest
