### ISSUE TITLE
支持一下qq音乐

### ISSUE THREAD

**Issue by gdzhu8023** [xhongc/music-tag-web#8]
大佬有计划支持一下qq音乐的数据源信息吗

**Comment by xhongc** [comment]
> 大佬有计划支持一下qq音乐的数据源信息吗

可以考虑

**Comment by xhongc** [comment]
> 大佬有计划支持一下qq音乐的数据源信息吗

已经支持 qq音乐了， @gdzhu8023 新的版本号是1.0.1，可以直接recreate，请知悉！

**Comment by xhongc** [comment]
hi，我创建一个交流群（二维码在 readme页面），感兴趣可以加入。群里会谈论项目新进展，和玩nas的交流，你有需要增加的功能可也沟通交流，期待你的加入！

ps. 不想被打扰，不加群也没关系，issue提的问题我也会回答。
