### ISSUE TITLE
Genre会被转换为全大写

### ISSUE THREAD

**Issue by EdwardJunyan** [xhongc/music-tag-web#80]
修改接口
<img width="1857" alt="iShot_2023-11-08_00 38 13" src="https://github.com/xhongc/music-tag-web/assets/44671927/880f66fe-3bf5-4371-8ca6-255b6a99311f">

回显接口
<img width="1792" alt="iShot_2023-11-08_00 39 40" src="https://github.com/xhongc/music-tag-web/assets/44671927/8c0dcf3b-6e70-499e-896e-2a214c81249c">

第二次修改的时候又会覆盖成全大写了

GENRE和LANGUAGE这两个标签，可以自定义内容吗？GENRE目前可以手输，但回显变全大写了，LANGUAGE这个标签还是写死的列表选择
(感谢大佬提供的工具

**Comment by xhongc** [comment]
修复
