### ISSUE TITLE
后台管理用默认密码进不去

### ISSUE THREAD

**Issue by AlleNPooh** [xhongc/music-tag-web#81]
后台管理用默认密码进不去
多尝试几次就进去了

**Comment by xhongc** [comment]
是不是你密码输入错误了

**Comment by AlleNPooh** [comment]
应该没有输入错误，出现了几次空白页，上头有一行错误代码，后边就正常了，我是第一次部署。

**Comment by AlleNPooh** [comment]
我一并在这里进行反馈吧：在文件整理的时候后台出现了这样的报错，然后就中止了，没有进一步的信息出现了，但是音乐好像是正常的，我现在删除了这首歌，重新进行整理。
文件读取错误: /app/media/3000首华语经典歌曲永流传.FLAC无损歌库/0014.Cheri-谭维维.flac, 错误信息: '/app/media/3000首华语经典歌曲永流传.FLAC无损歌库/0014.Cheri-谭维维.flac' is not a valid FLAC file

**Comment by xhongc** [comment]
你可以上传这首报错的音乐 给我试试

**Comment by xhongc** [comment]
整理文件报错不会终止，你要等待他执行完成

**Comment by AlleNPooh** [comment]
让我给删除了

**Comment by xhongc** [comment]
ok

**Comment by AlleNPooh** [comment]
现在的日志看起来不太方便，还需要刷新，可否用shell来看日志，这样检查也方便

**Comment by AlleNPooh** [comment]
还有一个问题，就是我不知道刮削任务是否完成了，最近我这个机器很慢，刮削实践很长，页面一刷新状态就没有了，就会无法得知任务是否完成。

**Comment by xhongc** [comment]
少量多次的刮削吧，一次性不要勾选太多

**Comment by AlleNPooh** [comment]
> 少量多次的刮削吧，一次性不要勾选太多

下载的都在一个文件里，不太好选择。我正在用整理的功能。目前日志还没有任何的信息。开始、结束都没有

**Comment by AlleNPooh** [comment]
操作了整理文件夹以后，没有任何的反应，后台的操作记录里也没有任何的生成记录，这个是啥情况

**Comment by AlleNPooh** [comment]
文件读取错误: /app/media/1031.金刚经-王菲.flac, 错误信息: [Errno 2] No such file or directory: '/app/media/1031.金刚经-王菲.flac'

**Comment by AlleNPooh** [comment]
我的所有歌曲，怎么都这样，尴尬了

**Comment by AlleNPooh** [comment]
之前在群辉环境的docker下， 我决定换一个环境，用Unraid再试试，

**Comment by xhongc** [comment]
整理文件 ，你要等它 loading 结束才能再操作，这里的操作是同步的

**Comment by AlleNPooh** [comment]
如果您这个是开源项目，我试着一起修改一下，确实在使用的时候遇到不少的问题。

**Comment by AlleNPooh** [comment]
删除空文件也会提示创建失败，有点不理解了

**Comment by AlleNPooh** [comment]
![截图-自动整理结果](https://github.com/xhongc/music-tag-web/assets/32183010/47f73c5f-095a-4f70-8008-f495b91c22dd)

**Comment by AlleNPooh** [comment]
这是一个自动整理的结果，好像也有问题

**Comment by xhongc** [comment]
尝试清空浏览器缓存试试

**Comment by xhongc** [comment]
F12 看一下 是否是报权限错误

**Comment by AlleNPooh** [comment]
清理了缓存，然后我再进行了整理，浏览器报错，看起来好像是权限，但是我是基于Unraid进行的docker部署，理论上不太可能有权限不让删除


       POST http://192.168.0.220:8001/api/remove_null_folder/ 403 (Forbidden)
________________________________
发件人: xier ***@***.***>
发送时间: 2023年11月9日 9:30
收件人: xhongc/music-tag-web ***@***.***>
抄送: AlexZhao ***@***.***>; Author ***@***.***>
主题: Re: [xhongc/music-tag-web] 后台管理用默认密码进不去 (Issue #81)


F12 看一下 是否是报权限错误

―

**Comment by xhongc** [comment]
是 这个项目的权限问题，你拉了最新镜像了吗

**Comment by AlleNPooh** [comment]
你latest镜像是不是不是最新的啊，我拉镜像，提示我现在就是最新了，但是好像是v1版本

**Comment by xhongc** [comment]
是最新的，那你试着退出登录，在重新登录呢

**Comment by AlleNPooh** [comment]
重新登录还是V1

**Comment by xhongc** [comment]
v1是正确的，V2 没有开放 ，有没有报错呢

**Comment by AlleNPooh** [comment]
不行，重新登录，刷新缓存都试了

**Comment by AlleNPooh** [comment]
整理文件还是权限不行

**Comment by xhongc** [comment]
message:"您没有执行该操作的权限。"
是报这个错误吗

**Comment by AlleNPooh** [comment]
'您没有执行该操作的权限。
![Uploading 微信图片_20231109094330.png…]()

**Comment by AlleNPooh** [comment]
`save to storage 192.168.0.220 
{router: '[{"path":"/","name":"home","component":"Home","met…ogin","component":"Login","meta":{"title":"登录"}}]', theme: 'light'}
vendor.f91f622….js:12 
 POST http://192.168.0.220:8001/api/remove_null_folder/ 403 (Forbidden)
app.4fee364….js:1 
{data: {…}, status: 403, statusText: 'Forbidden', headers: {…}, config: {…}, …}
config
: 
{transformRequest: {…}, transformResponse: {…}, timeout: 200000, xsrfCookieName: 'XSRF-TOKEN', adapter: ƒ, …}
data
: 
{result: false, code: '40302', message: '您没有执行该操作的权限。', data: null}
headers
: 
{access-control-allow-credentials: 'true', connection: 'keep-alive', content-length: '135', content-type: 'application/json', date: 'Thu, 09 Nov 2023 01:40:32 GMT', …}
request
: 
XMLHttpRequest {readyState: 4, timeout: 200000, withCredentials: true, upload: XMLHttpRequestUpload, onreadystatechange: ƒ, …}
status
: 
403
statusText
: 
"Forbidden"
[[Prototype]]
: 
Object
constructor
: 
ƒ Object()
hasOwnProperty
: 
ƒ hasOwnProperty()
isPrototypeOf
: 
ƒ isPrototypeOf()
propertyIsEnumerable
: 
ƒ propertyIsEnumerable()
toLocaleString
: 
ƒ toLocaleString()
toString
: 
ƒ toString()
valueOf
: 
ƒ valueOf()
__defineGetter__
: 
ƒ __defineGetter__()
__defineSetter__
: 
ƒ __defineSetter__()
__lookupGetter__
: 
ƒ __lookupGetter__()
__lookupSetter__
: 
ƒ __lookupSetter__()
__proto__
: 
(...)
get __proto__
: 
ƒ __proto__()
set __proto__
: 
ƒ __proto__()`

**Comment by xhongc** [comment]
方便让我访问到你的站点吗

**Comment by AlleNPooh** [comment]
我开放个端口给你试试

**Comment by AlleNPooh** [comment]
我怎么发给你啊？

**Comment by AlleNPooh** [comment]
我加了你的微信群，你的昵称是啥，我加你微信吧

**Comment by xhongc** [comment]
我是 群主

**Comment by xhongc** [comment]
charles
