### ISSUE TITLE
语言标签回显默认为「英文」

### ISSUE THREAD

**Issue by EdwardJunyan** [xhongc/music-tag-web#86]
元信息中【语言】标签如果有值会回显为「英文」
如果没有值会回显为「未知」

1. 希望所有标签可以按原值回显，不自动设置默认值
2. 专辑图片上传限制了5MB大小，这个可以提高一点或者自定义设置吗？
3. QQ音乐的歌词源会有&apos;这种XML字符（表示单引号），可以加一个`replace("&apos;","'")`吗？

**Comment by xhongc** [comment]
问题描述的很清晰 ，我将会进行优化。
