### ISSUE TITLE
自动刮削，标题错误。

### ISSUE THREAD

**Issue by xheia** [xhongc/music-tag-web#87]
拉取镜像：xhongc/music_tag_web:latest   2023/11/14 14:27:44

全选使用自动刮削后发现部分文件识别异常，检查后发现如图，如果文件名称有带编号的，标题识别有问题。
<img width="715" alt="微信图片_20231115153002" src="https://github.com/xhongc/music-tag-web/assets/130902402/90e5bda4-6d35-4f70-b134-c173e5b7baef">

**Comment by xhongc** [comment]
先用拆分文件名的方法，把文件名称 ，赋值给 标题
