### ISSUE TITLE
可以在左侧目录搜索上增加一个一键选中红色（失败）的checkbox吗？

### ISSUE THREAD

**Issue by axdlee** [xhongc/music-tag-web#88]
可以在左侧目录搜索上增加一个一键选中红色（失败）的checkbox吗？
因为有时候严格模式自动修改会有好多失败的，需要一个个点checkbox选中再进行宽松模式自动修改。
所以，希望可以增加一个一键选中红色checkbox的按钮

**Comment by xhongc** [comment]
比较麻烦，后续考虑
