### ISSUE TITLE
希望作者添加或者优化自动获取歌曲信息批量修改，多加QQ音乐接口

### ISSUE THREAD

**Issue by wqj666666** [xhongc/music-tag-web#9]
感谢作者的开源项目，但是需要手动一个个点击添加歌词，自动批量修改不能使用。我根据查询Navidrome的数据库来调用项目的接口实现了自动化，我希望作者也能添加自动化封装歌词。同时多加QQ音乐接口，网易接口有一些歌曲识别没有。
这是我随便写的Java批量代码
```java

import com.alibaba.fastjson.JSONArray;
import com.alibaba.fastjson.JSONObject;
import kong.unirest.HttpResponse;
import kong.unirest.Unirest;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

@SpringBootTest
class MusicApplicationTests {

    @Test
    void contextLoads() {
        Connection conn = null;
        Statement stmt = null;
        ResultSet rs = null;
        //链接db
        try {
            // 加载 SQLite 驱动程序
            Class.forName("org.sqlite.JDBC");

            // 连接到 SQLite 数据库
            conn = DriverManager.getConnection("jdbc:sqlite:C:\\Users\\admin\\Desktop\\navidrome.db");

            // 创建 Statement 对象
            stmt = conn.createStatement();

            // 执行查询语句
            String sql = "SELECT path FROM media_file";
            rs = stmt.executeQuery(sql);
            // 将结果存储在列表中
            List<String> coverArtPaths = new ArrayList<>();
            // 遍历结果并打印 cover_art_path 字段的值
            while (rs.next()) {
                String coverArtPath = rs.getString("path");
						//	把Navidrome音乐的地址替换为本项目的音乐地址
                String replacedOutput = coverArtPath.replace("/music/", "/app/media//");
                coverArtPaths.add(replacedOutput);
            }
            for (int i = 1938; i < coverArtPaths.size(); i++) {
                String coverArtPathsList = coverArtPaths.get(i);
                System.out.println("歌曲顺序"+i);
                JSONObject jsonObject = new JSONObject();
                // 使用 File 类来处理路径
                File file = new File(coverArtPathsList);
                // 获取文件名
                String fileName = file.getName();
                // 获取目录部分
                int lastIndex = coverArtPathsList.lastIndexOf("/");
                String directory = coverArtPathsList.substring(0, lastIndex + 1);
                jsonObject.put("file_path",directory);
                jsonObject.put("file_name",fileName);


                System.out.println(jsonObject);
                //                jsonObject.put()
                HttpResponse<String> musicInfo = Unirest.post("http://baidu.com/api/music_id3/")
                        .header("Content-Type", "application/json")
                        .body(jsonObject.toString())
                        .asString();
                String body = musicInfo.getBody();
                JSONObject jsonMusicInfo = JSONObject.parseObject(body);
                JSONObject jsonMusicInfoData = jsonMusicInfo.getJSONObject("data");
                if (jsonMusicInfoData!=null){
                    System.out.println(jsonMusicInfo);
                    String lyrics = jsonMusicInfoData.getString("lyrics");
                    // "lyrics": ""
                    if (Objects.isNull(lyrics) || lyrics.isEmpty()){
                        System.out.println("歌词为空");
                        //搜索歌曲信息
                        JSONObject jsonMusicInfoSearch = new JSONObject();
                        String title = jsonMusicInfoData.getString("title");
                        jsonMusicInfoSearch.put("title",title);
                        jsonMusicInfoSearch.put("resource","netease");
                        System.out.println("要搜索的信息:"+jsonMusicInfoSearch);
                        HttpResponse<String> musicInfoSearch = Unirest.post("http://baidu.com/api/fetch_id3_by_title/")
                                .header("Content-Type", "application/json")
                                .body(jsonMusicInfoSearch.toString())
                                .asString();
                        String musicInfoSearchBody = musicInfoSearch.getBody();
                        JSONObject jsonObjectmusicInfo= JSONObject.parseObject(musicInfoSearchBody);
                        System.out.println("搜索到的结果："+musicInfoSearchBody);
                        JSONArray jsonObjecmusicInfoSearchData = jsonObjectmusicInfo.getJSONArray("data");
                        //遍历找出完全匹配的数据
                        //读取的歌词专辑名称
                        String album = jsonMusicInfoData.getString("album");
                        //读取的歌曲作者
                        String artist = jsonMusicInfoData.getString("artist");
                        jsonObjecmusicInfoSearchData.stream().forEach(s->{
                            String s1 = s.toString();
                            JSONObject jsonObjects = JSONObject.parseObject(s1);
                            //结果的专辑名称
                            String albums = jsonObjects.getString("album");
                            //结果的歌曲名称
                            String names = jsonObjects.getString("name");
                            //结果的歌曲作者
                            String artists = jsonObjects.getString("artist");
                            if (title.equals(names)&&artist.equals(artists)){
                                System.out.println("完全匹配搜索结果:"+s);
                                JSONObject jsonObjectLyric = new JSONObject();
                                Integer id = jsonObjects.getInteger("id");
                                jsonObjectLyric.put("song_id",id);
                                jsonObjectLyric.put("resource","netease");
                                HttpResponse<String> lyric = Unirest.post("http://baidu.com/api/fetch_lyric/")
                                        .header("Content-Type", "application/json")
                                        .body(jsonObjectLyric.toJSONString())
                                        .asString();
                                String bodyLyric = lyric.getBody();
                                JSONObject jsonLyric = JSONObject.parseObject(bodyLyric);
                                String dataLyric = jsonLyric.getString("data");
                                System.out.println("匹配到歌词");
                                //组装更新歌曲信息更新
                                JSONArray jsonArrayMusicup = new JSONArray();
                                JSONObject jsonMusicup = new JSONObject();
                                jsonMusicup.put("file_full_path",coverArtPathsList);
                                jsonMusicup.put("title",names);
                                jsonMusicup.put("artist",artists);
                                jsonMusicup.put("album",album);
                                //读取的歌曲类型
                                String genre = jsonMusicInfoData.getString("genre");
                                jsonMusicup.put("genre",genre);
                                String year = jsonMusicInfoData.getString("year");
                                jsonMusicup.put("year",year);
                                jsonMusicup.put("lyrics",dataLyric);
                                //读取的歌曲comment
                                String comment = jsonMusicInfoData.getString("comment");
                                jsonMusicup.put("comment",comment);
                                //读取的歌曲comment
                                String artwork = jsonMusicInfoData.getString("artwork");
                                jsonMusicup.put("artwork",artwork);
                                jsonMusicup.put("filename",fileName);
                                //保存歌词lrc
                                jsonMusicup.put("is_save_lyrics_file",false);
                                //专辑封面
                                String album_img = jsonMusicInfoData.getString("album_img");
                                jsonMusicup.put("album_img",album_img);

                                jsonArrayMusicup.add(jsonMusicup);
                                JSONObject jsonObject1 = new JSONObject();
                                jsonObject1.put("music_id3_info",jsonArrayMusicup);
                                HttpResponse<String> musicup = Unirest.post("http://baidu.com/api/update_id3/")
                                        .header("Content-Type", "application/json")
                                        .body(jsonObject1.toString())
                                        .asString();
                                String musicupbody = musicup.getBody();
                                JSONObject jsonObject2 = JSONObject.parseObject(musicupbody);
                                if ("200".equals(jsonObject2.getString("code"))){
                                    System.out.println("歌词更新成功:"+musicupbody);
                                }else {
                                    System.out.println("歌词更新失败"+musicupbody);
                                }
                                try {
                                    Thread.sleep(1000); // 等待1秒
                                } catch (InterruptedException e) {
                                    throw new RuntimeException(e);
                                }


                            }
                        });

                    }else {
                        System.out.println("歌词不为空");
                    }
                }else {
                    System.out.println("搜索不到歌词");
                }
//                Thread.sleep(3000);
//                System.out.println("等待3秒");
            }
        } catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace();
        } finally {
            // 关闭 ResultSet、Statement 和 Connection
            try {
                if (rs != null) {
                    rs.close();
                }
                if (stmt != null) {
                    stmt.close();
                }
                if (conn != null) {
                    conn.close();
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }
}




```

**Comment by xhongc** [comment]
🥱

**Comment by bao3** [comment]
需要能批量更改整个专辑的封面、年代的方法。现在需要每个歌手动改太累。而且很多歌在现有的 网易和咪咕上根本搜不到。

**Comment by xhongc** [comment]
> 需要能批量更改整个专辑的封面、年代的方法。现在需要每个歌手动改太累。而且很多歌在现有的 网易和咪咕上根本搜不到。

我写这个应用的初衷是为了对个别音乐差缺补漏，按理说用先用打标签工具 先处理一遍

**Comment by xhongc** [comment]
> 感谢作者的开源项目，但是需要手动一个个点击添加歌词，自动批量修改不能使用。我根据查询Navidrome的数据库来调用项目的接口实现了自动化，我希望作者也能添加自动化封装歌词。同时多加QQ音乐接口，网易接口有一些歌曲识别没有。 这是我随便写的Java批量代码
> 
> ```java
> import com.alibaba.fastjson.JSONArray;
> import com.alibaba.fastjson.JSONObject;
> import kong.unirest.HttpResponse;
> import kong.unirest.Unirest;
> import org.junit.jupiter.api.Test;
> import org.springframework.boot.test.context.SpringBootTest;
> 
> import java.io.File;
> import java.sql.Connection;
> import java.sql.DriverManager;
> import java.sql.ResultSet;
> import java.sql.SQLException;
> import java.sql.Statement;
> import java.util.ArrayList;
> import java.util.List;
> import java.util.Objects;
> 
> @SpringBootTest
> class MusicApplicationTests {
> 
>     @Test
>     void contextLoads() {
>         Connection conn = null;
>         Statement stmt = null;
>         ResultSet rs = null;
>         //链接db
>         try {
>             // 加载 SQLite 驱动程序
>             Class.forName("org.sqlite.JDBC");
> 
>             // 连接到 SQLite 数据库
>             conn = DriverManager.getConnection("jdbc:sqlite:C:\\Users\\admin\\Desktop\\navidrome.db");
> 
>             // 创建 Statement 对象
>             stmt = conn.createStatement();
> 
>             // 执行查询语句
>             String sql = "SELECT path FROM media_file";
>             rs = stmt.executeQuery(sql);
>             // 将结果存储在列表中
>             List<String> coverArtPaths = new ArrayList<>();
>             // 遍历结果并打印 cover_art_path 字段的值
>             while (rs.next()) {
>                 String coverArtPath = rs.getString("path");
> 						//	把Navidrome音乐的地址替换为本项目的音乐地址
>                 String replacedOutput = coverArtPath.replace("/music/", "/app/media//");
>                 coverArtPaths.add(replacedOutput);
>             }
>             for (int i = 1938; i < coverArtPaths.size(); i++) {
>                 String coverArtPathsList = coverArtPaths.get(i);
>                 System.out.println("歌曲顺序"+i);
>                 JSONObject jsonObject = new JSONObject();
>                 // 使用 File 类来处理路径
>                 File file = new File(coverArtPathsList);
>                 // 获取文件名
>                 String fileName = file.getName();
>                 // 获取目录部分
>                 int lastIndex = coverArtPathsList.lastIndexOf("/");
>                 String directory = coverArtPathsList.substring(0, lastIndex + 1);
>                 jsonObject.put("file_path",directory);
>                 jsonObject.put("file_name",fileName);
> 
> 
>                 System.out.println(jsonObject);
>                 //                jsonObject.put()
>                 HttpResponse<String> musicInfo = Unirest.post("http://baidu.com/api/music_id3/")
>                         .header("Content-Type", "application/json")
>                         .body(jsonObject.toString())
>                         .asString();
>                 String body = musicInfo.getBody();
>                 JSONObject jsonMusicInfo = JSONObject.parseObject(body);
>                 JSONObject jsonMusicInfoData = jsonMusicInfo.getJSONObject("data");
>                 if (jsonMusicInfoData!=null){
>                     System.out.println(jsonMusicInfo);
>                     String lyrics = jsonMusicInfoData.getString("lyrics");
>                     // "lyrics": ""
>                     if (Objects.isNull(lyrics) || lyrics.isEmpty()){
>                         System.out.println("歌词为空");
>                         //搜索歌曲信息
>                         JSONObject jsonMusicInfoSearch = new JSONObject();
>                         String title = jsonMusicInfoData.getString("title");
>                         jsonMusicInfoSearch.put("title",title);
>                         jsonMusicInfoSearch.put("resource","netease");
>                         System.out.println("要搜索的信息:"+jsonMusicInfoSearch);
>                         HttpResponse<String> musicInfoSearch = Unirest.post("http://baidu.com/api/fetch_id3_by_title/")
>                                 .header("Content-Type", "application/json")
>                                 .body(jsonMusicInfoSearch.toString())
>                                 .asString();
>                         String musicInfoSearchBody = musicInfoSearch.getBody();
>                         JSONObject jsonObjectmusicInfo= JSONObject.parseObject(musicInfoSearchBody);
>                         System.out.println("搜索到的结果："+musicInfoSearchBody);
>                         JSONArray jsonObjecmusicInfoSearchData = jsonObjectmusicInfo.getJSONArray("data");
>                         //遍历找出完全匹配的数据
>                         //读取的歌词专辑名称
>                         String album = jsonMusicInfoData.getString("album");
>                         //读取的歌曲作者
>                         String artist = jsonMusicInfoData.getString("artist");
>                         jsonObjecmusicInfoSearchData.stream().forEach(s->{
>                             String s1 = s.toString();
>                             JSONObject jsonObjects = JSONObject.parseObject(s1);
>                             //结果的专辑名称
>                             String albums = jsonObjects.getString("album");
>                             //结果的歌曲名称
>                             String names = jsonObjects.getString("name");
>                             //结果的歌曲作者
>                             String artists = jsonObjects.getString("artist");
>                             if (title.equals(names)&&artist.equals(artists)){
>                                 System.out.println("完全匹配搜索结果:"+s);
>                                 JSONObject jsonObjectLyric = new JSONObject();
>                                 Integer id = jsonObjects.getInteger("id");
>                                 jsonObjectLyric.put("song_id",id);
>                                 jsonObjectLyric.put("resource","netease");
>                                 HttpResponse<String> lyric = Unirest.post("http://baidu.com/api/fetch_lyric/")
>                                         .header("Content-Type", "application/json")
>                                         .body(jsonObjectLyric.toJSONString())
>                                         .asString();
>                                 String bodyLyric = lyric.getBody();
>                                 JSONObject jsonLyric = JSONObject.parseObject(bodyLyric);
>                                 String dataLyric = jsonLyric.getString("data");
>                                 System.out.println("匹配到歌词");
>                                 //组装更新歌曲信息更新
>                                 JSONArray jsonArrayMusicup = new JSONArray();
>                                 JSONObject jsonMusicup = new JSONObject();
>                                 jsonMusicup.put("file_full_path",coverArtPathsList);
>                                 jsonMusicup.put("title",names);
>                                 jsonMusicup.put("artist",artists);
>                                 jsonMusicup.put("album",album);
>                                 //读取的歌曲类型
>                                 String genre = jsonMusicInfoData.getString("genre");
>                                 jsonMusicup.put("genre",genre);
>                                 String year = jsonMusicInfoData.getString("year");
>                                 jsonMusicup.put("year",year);
>                                 jsonMusicup.put("lyrics",dataLyric);
>                                 //读取的歌曲comment
>                                 String comment = jsonMusicInfoData.getString("comment");
>                                 jsonMusicup.put("comment",comment);
>                                 //读取的歌曲comment
>                                 String artwork = jsonMusicInfoData.getString("artwork");
>                                 jsonMusicup.put("artwork",artwork);
>                                 jsonMusicup.put("filename",fileName);
>                                 //保存歌词lrc
>                                 jsonMusicup.put("is_save_lyrics_file",false);
>                                 //专辑封面
>                                 String album_img = jsonMusicInfoData.getString("album_img");
>                                 jsonMusicup.put("album_img",album_img);
> 
>                                 jsonArrayMusicup.add(jsonMusicup);
>                                 JSONObject jsonObject1 = new JSONObject();
>                                 jsonObject1.put("music_id3_info",jsonArrayMusicup);
>                                 HttpResponse<String> musicup = Unirest.post("http://baidu.com/api/update_id3/")
>                                         .header("Content-Type", "application/json")
>                                         .body(jsonObject1.toString())
>                                         .asString();
>                                 String musicupbody = musicup.getBody();
>                                 JSONObject jsonObject2 = JSONObject.parseObject(musicupbody);
>                                 if ("200".equals(jsonObject2.getString("code"))){
>                                     System.out.println("歌词更新成功:"+musicupbody);
>                                 }else {
>                                     System.out.println("歌词更新失败"+musicupbody);
>                                 }
>                                 try {
>                                     Thread.sleep(1000); // 等待1秒
>                                 } catch (InterruptedException e) {
>                                     throw new RuntimeException(e);
>                                 }
> 
> 
>                             }
>                         });
> 
>                     }else {
>                         System.out.println("歌词不为空");
>                     }
>                 }else {
>                     System.out.println("搜索不到歌词");
>                 }
> //                Thread.sleep(3000);
> //                System.out.println("等待3秒");
>             }
>         } catch (ClassNotFoundException | SQLException e) {
>             e.printStackTrace();
>         } finally {
>             // 关闭 ResultSet、Statement 和 Connection
>             try {
>                 if (rs != null) {
>                     rs.close();
>                 }
>                 if (stmt != null) {
>                     stmt.close();
>                 }
>                 if (conn != null) {
>                     conn.close();
>                 }
>             } catch (SQLException e) {
>                 e.printStackTrace();
>             }
>         }
>     }
> }
> ```

已经支持 qq音乐了， @wqj666666  新的版本号是1.0.1，可以直接recreate，请知悉！

**Comment by xhongc** [comment]
hi，我创建一个交流群（二维码在 readme页面），感兴趣可以加入。群里会谈论项目新进展，和玩nas的交流，你有需要增加的功能可也沟通交流，期待你的加入！

ps. 不想被打扰，不加群也没关系，issue提的问题我也会回答。
