### ISSUE TITLE
[v1]期望左侧的搜索能够搜索子目录

### ISSUE THREAD

**Issue by coolguy001tv** [xhongc/music-tag-web#93]
我本地的音乐放的比较乱，有些是 `artist-name.mp3` 有些是`artist/artist-name.mp3`等存在目录的结构。
以下图为例，当在根目录(`/app/media`)下搜索`Awake`时无法找到 这首`Skillet - Awake and Alive (The Quickening).mp3`，因为他在`/app/media/Skillet`下面，只能在`/app/media/Skillet`下去搜索这首歌。
感觉对于喜欢用`artist/artist-name.mp3`这种目录结构存歌的不太友好。

![image](https://github.com/xhongc/music-tag-web/assets/936825/30fb2927-1827-4b5c-975e-66382ebae2b5)
![image](https://github.com/xhongc/music-tag-web/assets/936825/dab05986-c455-42dc-b911-743b548b0850)

我有这个需求主要是，听歌的时候发现某一首歌的歌词对不上，所以想单独找到这首歌去重新搜索一下。然后就碰到了找不到的问题，进而提了2个issues 😆

**Comment by xhongc** [comment]
搜索不会深度搜索文件夹下的文件，这会导致搜索缓慢，所以没有考虑

**Comment by coolguy001tv** [comment]
是否考虑加个深度搜索开关项？搜索缓慢应该是对于音乐库比较大的时候吧。毕竟我觉得 用类似artist/artist-name.mp3的方式来整理音乐的应该挺多的（甚至估计还有artist/album/name.mp3这种整理方式），但有时候找歌可能就只记得了name。

**Comment by Qm-jmz** [comment]
音乐库中的音乐找不到本地存放目录的话可以靠在音乐库中查看歌曲信息解决，里面一般会提供歌曲地址。不一定要靠music- tag-web
