### ISSUE TITLE
删除歌词时间轴（功能建议）

### ISSUE THREAD

**Issue by siryul** [xhongc/music-tag-web#95]
希望添加客户端中的删除歌词的时间轴功能

**Comment by xhongc** [comment]
为什么会有删除时间轴的需求😶

**Comment by siryul** [comment]
> 为什么会有删除时间轴的需求😶

在将修改标签之后的歌曲上传至 Apple Music 上之后歌词展示页会将时间轴一同展示
![Uploading image.png…]()

**Comment by xhongc** [comment]
哦，加上了
