### ISSUE TITLE
大佬，需要邀请码吗？

### ISSUE THREAD

**Issue by yanggqi** [xhongc/music-tag-web#96]
用了几天现在登陆提示要邀请码？

**Comment by xhongc** [comment]
v1 版本不需要的，不用填就可以进入

**Comment by yanggqi** [comment]
![截屏2023-11-21 23 13 09](https://github.com/xhongc/music-tag-web/assets/44476296/620a253e-a357-4b22-8a23-84d5c8f03ec2)
现在进入，就是登陆界面。
docker版，镜像创新拉取也是这样。

**Comment by xhongc** [comment]
留空不填
