### ISSUE TITLE
[feature request] 希望增加 MusicBrainz 数据源

### ISSUE THREAD

**Issue by darwintree** [xhongc/music-tag-web#97]
感谢项目，最近几周一直在头疼navidrome曲库的管理。
请问能否增加MusicBrainz数据源的支持？谢谢

另：微信群链接好像失效了

**Comment by xhongc** [comment]
好，微信群链接已经更新

**Comment by taizilongxu** [comment]
+1 
专辑模式 MusicBrainz 刚方便
