### ISSUE TITLE
音乐风格一修改后，群晖中依然不变

### ISSUE THREAD

**Issue by jinfeng1985** [xhongc/music-tag-web#98]
如图
![IMG_0073](https://github.com/xhongc/music-tag-web/assets/22148953/942f8078-7148-4aa5-90c5-201dfa90a50e)
![IMG_0074](https://github.com/xhongc/music-tag-web/assets/22148953/9fe76c7e-a418-43e4-8896-620a52710f69)

**Comment by xhongc** [comment]
标签正常写入，群晖没读取到可能原因
 1. 群晖没有重新刷新读取 元数据
  2.群晖读取 风格的 字段 与写入的不一同一个
