### ISSUE TITLE
删除用户后，再添加同名用户提示重复

### ISSUE THREAD

**Issue by xinyue603** [xhongc/music-tag-web#99]
删除用户后，在右侧用户列表以及用户id还是会显示。
是不是数据库没有删除和刷新。

**Comment by xhongc** [comment]
哪里显示用户 id 和用户列表

**Comment by xinyue603** [comment]
![2](https://github.com/xhongc/music-tag-web/assets/97430272/e1d0d7de-2e31-4cc6-9b51-937fffd31916)

**Comment by xhongc** [comment]
<img width="673" alt="image" src="https://github.com/xhongc/music-tag-web/assets/29135056/6838f3f4-5962-4554-9e68-52ae39259f9d">
用于登录的用户 在这里创建哦

**Comment by xinyue603** [comment]
3Q

**Comment by xhongc** [comment]
好的 closed
